### ISSUE TITLE
VA>VSR - API - Récupérer les programmes liés à un secteur

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#106]
**Description du bug / Describe the bug**

La fiche information d'un secteur permet d'afficher la liste des programmes de ce dernier.
Pour un secteur dont l'identifiant = 10, voici la requête à utiliser : 

https://portail-test.sig.rennesmetropole.fr/tabou2/operations/10/programmes?asc=true

Elle retourne actuellement une **erreur 500**.

![image](https://user-images.githubusercontent.com/16317988/117773574-c3556b80-b238-11eb-9d49-e64e84c153a3.png)

**Reproduire le bug / To Reproduce**

1. Identifier une opération de type secteur (estSecteur = true)
2. Appeler l'API pour ce récupérer les programmes de ce secteur (ex: id =10)
https://portail-test.sig.rennesmetropole.fr/tabou2/operations/10/programmes?asc=true
3. Voir l'erreur 500 sans informations supplémentaires

**Comportement attendu / Exptected behavior**

L'API doit pouvoir retourner les programmes d'un secteur.

**Screenshots**

Pour l'exemple ci-dessus (opération de type estSecteur avec id = 10) :

![image](https://user-images.githubusercontent.com/16317988/117773294-6bb70000-b238-11eb-96e6-6d34eaeeef9d.png)

En rouge, le programme qui devrait être retourné. En vert, le secteur dont l'id = 10.

**Comment by dcottenc** [comment]
Cette anomalie est toujours en présente dans l'environnement RM (API v1.1.4)

**Comment by Gaetanbrl** [comment]
Champ à laisser vide le temps de la correction (non faite dans api 1.1.4).

**Comment by Gaetanbrl** [comment]
Passage en VSR

**Comment by dcottenc** [comment]
Correction prioritaire dans le sprint en cours. Reprise des devs le 24/08

**Comment by dcottenc** [comment]
@Gaetanbrl A confirmer mais cette anomalie est corrigée en v1.1.5 et n'est plus présente en VSR. La liste des programmes pour un secteur s'affiche correctement
