### ISSUE TITLE
API - N°ADS rend le programme non consultable par le plugin

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#107]
**Description du bug / Describe the bug**

Si un numéro ADS obligatoire pour accéder aux infos DDC (programme) est saisi, le programme ne peut plus être consulté par le plugin.

**Version**

API - 1.1.2 du 18/05

Vu avec @dcottenc .

**Comment by dcottenc** [comment]
Cette anomalie est corrigée

**Comment by Gaetanbrl** [comment]
A tester / a intégrer si besoin par @Gaetanbrl

**Comment by dcottenc** [comment]
Correction testée et validée
