### ISSUE TITLE
[MapStore] - Filtrer les données

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#108]
**Description du bug / Describe the bug**

Filtrer les données sur plusieurs valeurs via l'UI de filtre MapStore retourne une erreur.
Bug remonté à @catmorales le 07/05/2021.

Ce bug rend l'application de la recherche Tabou impossible car lors de la définition d'une recherche, nous filtrons une données sur un ou plusieurs ID.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Ouvrir un contexte carto MapStore (Tabou, Geojardins, autre...)
2. Ouvrir le menu de création de filtre d'une couche
3. Ajouter au moins deux filtres sur le même attribut (id ou objectid)
4. Appliquer
5. Constater le point d'exclamation en haut à droite de la fenêtre

**Comportement attendu / Exptected behavior**

Le filtre s'applique sur les données sans erreur.

**Screenshots**

![image](https://user-images.githubusercontent.com/16317988/119449786-59a68880-bd33-11eb-85da-e41361c36359.png)

**Comment by dcottenc** [comment]
@Gaetanbrl Correction effectuée par la DSI RM (modification du filtre sur les Url du Security proxy)
