### ISSUE TITLE
API - Type tiers associé non modifiable & infos manquantes

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#109]
### Niveau

Bloquant : Développements ne pouvant pas être terminés.

### Description

Lors de la récupération des tiers, il nous faut l'ID de l'association (pour modifier le type) et l'ID du tiers (pour tout associer).
En effet, un tiers peut être présent plusieurs fois (sous le même nom) mais avec des types différents. Seul l'ID permettra de différencier l'enregistrement.

Voici ce que donne l'appel des tiers pour l'operation avec id 3 :

```
{
  "elements": [
    {
      "nom": "JF. Golhen",
      "libelle": "Architecte"
    },
    {
      "nom": "Antonini et Darmon",
      "libelle": "Maître d'oeuvre"
    },
    {
      "nom": "Territoires Rennes",
      "libelle": "Maître d'ouvrage"
    },
    {
      "nom": "create17161",
      "libelle": "Maître d'ouvrage"
    },
    {
      "nom": "Atelier Jacqueline Osty & Associés",
      "libelle": "Paysagiste"
    },
    {
      "nom": "Jean",
      "libelle": "Paysagiste"
    },
    {
      "nom": "Reichen et Robert & Associés",
      "libelle": "Urbaniste"
    }
  ],
  "totalElements": 7
}
```

**Comment by dcottenc** [comment]
La correction est effective pour les opérations et les programmes.
La réponse est maintenant du type :
{
  "elements": [
    {
      "id": 1,
      "typeTiers": {
        "id": 1,
        "libelle": "Maître d'ouvrage",
        "createUser": null,
        "createDate": null,
        "dateInactif": null
      },
      "tiers": {
        "id": 23,
        "nom": "Espacil",
        "adresseNum": null,
        "adresseRue": null,
        "adresseCp": null,
        "adresseVille": null,
        "telephone": null,
        "telecopie": null,
        "email": null,
        "siteWeb": null,
        "contact": null,
        "estPrive": false,
        "dateInactif": null
      }
    },
    {
      "id": 2,
      "typeTiers": {
        "id": 3,
        "libelle": "Architecte",
        "createUser": "d.cottencin",
        "createDate": "2021-04-13T14:14:15.097+0000",
        "dateInactif": null
      },
      "tiers": {
        "id": 24,
        "nom": "JF. Golhen",
        "adresseNum": null,
        "adresseRue": null,
        "adresseCp": null,
        "adresseVille": null,
        "telephone": null,
        "telecopie": null,
        "email": null,
        "siteWeb": null,
        "contact": null,
        "estPrive": false,
        "dateInactif": null
      }
    },
    {
      "id": 3,
      "typeTiers": {
        "id": 3,
        "libelle": "Architecte",
        "createUser": "d.cottencin",
        "createDate": "2021-04-13T14:14:15.097+0000",
        "dateInactif": null
      },
      "tiers": {
        "id": 25,
        "nom": "Antonini et Darmon",
        "adresseNum": "8",
        "adresseRue": "8",
        "adresseCp": "75000",
        "adresseVille": "paris",
        "telephone": null,
        "telecopie": null,
        "email": "test@test.fr",
        "siteWeb": "test.fr",
        "contact": "nc",
        "estPrive": true,
        "dateInactif": null
      }
    }
  ],
  "totalElements": 3
}

**Comment by Gaetanbrl** [comment]
A intégrer / à tester dans plugin par @Gaetanbrl

**Comment by Gaetanbrl** [comment]
ok testé dans l'API.

A passer dans une évolution comme convenu dans le dernier COPIL de la v1.0 du plugin.
