### ISSUE TITLE
API ? - Régression sur la récupération de l'emprise au clic sur une entité (id nature obligatoire)

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#110]
**Description du bug / Describe the bug**

Lors du clic sur une entité non suivie (e.g opération sans id tabou) on récupère ces informations (dont la nature en string) depuis la carte  : 

```
amenageur: null
code: null
commune: "Rennes"
consommati: null
create_dat: null
create_use: null
dateautori: null
dateclotur: null
dateoperat: null
decision: null
descriptio: null
diffusion_: null
etape: null
id_emprise: 622
id_tabou: null
logementsp: null
maitriseou: null
modeamenag: null
modif_date: null
modif_user: null
nature: "ZA" <==== ICI
nom: "ZA de Bray"
num_ads: null
objectid: 357
operation: null
plhlogeme0: null
plhlogemen: null
ql3: null
scott: null
surface_to: null
territoire: null
vocation: null
```

Jusque là, à partir de la valeur de la nature (ici ZA) on peut récupérer toutes les emprises telles que cet appel suffisait : 
http://localhost:8081/tabou2/operations/emprises?nature=ZA&estSecteur=false

Hors, cette appel retourne maintenant une erreur 500 suite à cette modification commentée dans l'issue #60 par @dcottenc : 

> L'API GET /operations/emprises prend dorénavant l'ID de la nature disponible dans la liste chargée pour la liste déroulante

**Avantage :**
On a plus à se soucier du libellé de la nature.

**Inconvénient**
Ce qui fonctionnait très bien avant ne fonctionne plus... la fonction d'ajout d'une OA n'est donc plus fonctionnelle.

Un appel supplémentaire doit être réalisé pour avoir l'id de la nature. C'est une contrainte de l'API que le front subi vu les discordance entre les infos de la carte et les infos attendues par l'API.

@dcottenc Est-il possible d'appeler les emprise par id OU par nom et non uniquement par id ?
Vu que les valeurs de nature sont les mêmes dans l'API et les données carto, ca doit être possible.

**Comment by Gaetanbrl** [comment]
@dcottenc j'ai pu récupéré et stocker les infos de toutes les nature disponibles. Je dois pouvoir modifier mon appel d'emprise pour envoyer l'id et pas le libellé.

**Comment by dcottenc** [comment]
@Gaetanbrl  La correction demandée portait justement sur l'utilisation d'un libellé qui n'était pas cohérent avec celui retourné par la couche .Pour palier à ce risque, j'ai demandé l'utilisation de l'ID sans penser au CU du clic sur une entité non suivie.
Je peux demander à modifier le SW pour prendre en compte l'ID ou le libellé mais ca arrivera trop tard pour toi. Je suppose que tu utilises la requête Nature pour récupérer l'ID du libelle Nature de l'entité

**Comment by Gaetanbrl** [comment]
A clore, j'ai adapté le code du plugin en conséquence. Régressions à surveiller sur d'autres fonctionnalités.
