### ISSUE TITLE
Plugin - Erreur à l'ouverture d'un champs date

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#113]
**Niveau :** Majeur

**Description du bug / Describe the bug**

Lorsqu'on souhaite ouvrir le calendrier sur un champ de type date, on obtient un crash de l'application.
Ce comportement n'est pas reproductible sur l'environnement de dev. Uniquement sur la PF de test.

```
TypeError: Cannot read property 'time' of undefined
    at Object.getFormat (574.99f9797e.js:2)
    at p (574.99f9797e.js:2)
    at t._dates (574.99f9797e.js:2)
    at t.getInitialState (574.99f9797e.js:2)
    at new t (574.99f9797e.js:2)
    at bi (geOrchestra.js?63b7786f60ffbac2ebc7:2)
    at Ia (geOrchestra.js?63b7786f60ffbac2ebc7:2)
    at Fs (geOrchestra.js?63b7786f60ffbac2ebc7:2)
    at ol (geOrchestra.js?63b7786f60ffbac2ebc7:2)
    at nl (geOrchestra.js?63b7786f60ffbac2ebc7:2)
    at Zs (geOrchestra.js?63b7786f60ffbac2ebc7:2)
    at geOrchestra.js?63b7786f60ffbac2ebc7:2
    at t.unstable_runWithPriority (geOrchestra.js?63b7786f60ffbac2ebc7:2)
    at Bo (geOrchestra.js?63b7786f60ffbac2ebc7:2)
    at Ho (geOrchestra.js?63b7786f60ffbac2ebc7:2)
    at qo (geOrchestra.js?63b7786f60ffbac2ebc7:2)
```

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Ouvrir le contexte Tabou2
2. Ouvrir le plugin
3. Dans l'onglet "Recherche", cloquer sur l'icône calendrier pour afficher les dates
4. L'application crash

**Comportement attendu / Exptected behavior**

Le volet s'ouvre, on peut alors sélectionner une date.

**Screenshots**

![issue113](https://user-images.githubusercontent.com/16317988/120339508-76275f80-c2f5-11eb-814d-1855eb020338.gif)

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - Version tabou2 1.0.0

**Informations complémentaires / Additional context**

Version mapstore à upgrade sur l'environnement de dev.

**Comment by Gaetanbrl** [comment]
Issue non reproduite sur la branches MapStoreExtension 2021.01.xx 

https://github.com/geosolutions-it/MapStoreExtension/tree/2021.01.xx

**Comment by Gaetanbrl** [comment]
Bug reproduit uniquement dans un environnement mapstore2-georchetstra

**Comment by Gaetanbrl** [comment]
lié à https://github.com/georchestra/mapstore2-georchestra/issues/390

**Comment by Gaetanbrl** [comment]
Le plugin fonctionne dans la version non buildée (weppack) de mapstore2-georchestra.
Après build (npm run ext:build) et seulement après installation via l'IHM MapStore2, cette issue est reproductible.

Il est probable que le problème vienne du build webpack.

**Comment by dcottenc** [comment]
> Le plugin fonctionne dans la version non buildée (weppack) de mapstore2-georchestra.
> Après build (npm run ext:build) et seulement après installation via l'IHM MapStore2, cette issue est reproductible.
> Il est probable que le problème vienne du build webpack.

Juste pour confirmation, ces éléments très techniques sont bien ajoutés directement dans ton issue ouverte dans l'espace GeOrchestra/Mapstore ?

**Comment by Gaetanbrl** [comment]
> Juste pour confirmation, ces éléments très techniques sont bien ajoutés directement dans ton issue ouverte dans l'espace GeOrchestra/Mapstore ?

Oui Denis

**Comment by dcottenc** [comment]
Pour information, nous avons relancé GeoSolutions (Comment dans l'issue GitHub)

**Comment by Gaetanbrl** [comment]
Corrigé et visible sur contexte MapStore2-georchestra de test.
