### ISSUE TITLE
PLUI - Recherche par zone PLUI 

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#115]
## Description

**En tant que** élu d'une commune, 
**Je souhaite** accéder à un filtre zone PLUI
**Afin de** filtrer les couches PA, OA, SA par type de zonage

## (Si) Règles spécifiques - Règles métiers

Les types de zone PLUI sont saisies par les chargé d'opération.
L'API Tabou2 va permettre d'accéder à toutes les zones saisies et de proposer une liste à afficher dans une combo box (liste de choix) que l'on pourra intégrer dans le plugin Tabou2.

Comme les autres filtres, OA, PA, SA vont devoir croiser (intersection) une couche PLUI spécifique à créer dans GeoServer.

## Difficulté

La couche initiale PLUI n'intègre pas cette données de type de zone PLUI.

**Comment by dcottenc** [comment]
@Gaetanbrl cette demande avait pour but de faire un pre filtre pour la liste du zonage PLUi.
Cependant, l'autocomplétion récemment implémentée semble répondre à ce besoin, non? A valider par MAO

**Comment by Gaetanbrl** [comment]
En attente suite à :
* erreur 500 sur l'API /plui
* Attente retour MOA (l'autocomplétion pouvant permettre de rechercher par zone Ex: zone UA pour UA1 ou UAx)

**Comment by dcottenc** [comment]
La MOA a confirmé ce besoin mais il doit d'abord être implémenté dans les tables du PLUi.

**Comment by dcottenc** [comment]
Testé et validé en PF de test
