### ISSUE TITLE
VA front - Affichage fiche opération/secteur

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#116]
**Niveau : Mineur**

**Description du bug / Describe the bug**

L'anomalie concerne des libellés et des valeurs à corriger  dans la fiche de consultation des informations OA et SA.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Se connecter au contexte Tabou
2. Ouvrir le plugin Tabou
3. Cliquer sur une OA ou une SA qui est suivi dans Tabou (id_tabou non null)
4. Cliquer sur l'onglet de consultation de la fiche de cette entité

**Comportement attendu / Exptected behavior**

Bloc Identification : L'attribut Opération n' a pas lieu d'être présent. Il doit l'être uniquement pour les programmes : nom de l'opération parent)
Bloc Descriptif : L'attribut "Espace total" est incorrect. A remplacer par "Surface Totale"
Bloc Gouvernance : L'attribut "Promoteur" est à supprimer (MOA d'un PA). Pour les OA/SA la MOA correspond au champ Aménageur.
Bloc Activités : Il manque le champ QL1

**Screenshots**

**Environnement / Desktop**

 - Environnement : RM Portail Test 
 - Version Front v1.0

**Informations complémentaires / Additional context**

**Comment by Gaetanbrl** [comment]
Corrections en cours : 

- [ ] Bloc Identification : L'attribut Opération n' a pas lieu d'être présent. Il doit l'être uniquement pour les programmes : nom de l'opération parent)
- [ ] Bloc Descriptif : L'attribut "Espace total" est incorrect. A remplacer par "Surface Totale"
- [ ] Bloc Gouvernance : L'attribut "Promoteur" est à supprimer (MOA d'un PA). Pour les OA/SA la MOA correspond au champ Aménageur.
- [ ] Bloc Activités : Il manque le champ QL1

**Comment by Gaetanbrl** [comment]
> L'attribut "Promoteur" est à supprimer (MOA d'un PA)

@dcottenc ce champ "Promoteur" figure dans la description de la fiche PA :
https://github.com/sigrennesmetropole/geor_tabou2_front/issues/69

La demande est de finalement le supprimer si je comprend bien ?

**Comment by Gaetanbrl** [comment]
@dcottenc le champ `ql1` est inconnu des spécifications fournies dans l'issue #70 pour la fiche OA.
Ce n'est pas un bug.

![image](https://user-images.githubusercontent.com/16317988/123442122-d9df3880-d5d4-11eb-941c-a910a0ef41af.png)

**Comment by Gaetanbrl** [comment]
Suite à la livraison API 1.1.4 ==> Correctif apporté sur l'affichage des MOA dans le champ Aménageurs / promoteur.

**Comment by Gaetanbrl** [comment]
Je viens de pousser le correctif sur la branche develop, je met sur la PF de test.

Le champ ql1 est une évolution que j'intègre avec ces correctifs, il me faut cependant le détail comme pour les champs ql2 et ql3. Nous pourrons clore cette issue si seul ce test n'est pas validé. 

J'ouvre une autre issue pour le champ ql1 manquant en tant que évolution à traiter.

**Comment by dcottenc** [comment]
Pour revenir au champ ql1, je ne retrouve pas l'origine mais ma remarque concernait le champ Territoires donc ql3 ?! Je vais rechercher la bonne spec mais on est bien sur l'affichage d'un champ texte et d'un champ booleen.
Je confirme cela rapidement

**Comment by Gaetanbrl** [comment]
@dcottenc tu peux vérifier sur la PF de test et compléter l'issue #118 pour bien comprendre ce qu'il en est du champ ql1.

Actuellement on a 
* ql2 = SCOT
* ql3 = Territoire

**Comment by dcottenc** [comment]
> Bloc Activités : Il manque le champ QL1

Le champ ql1 n'est pas à afficher. Il y a eu une confusion de ma part avec le ql3

**Comment by Gaetanbrl** [comment]
@dcottenc ok pour le champ ql1.

En attente d'un retour sur les éléments ici corrigés : 

- [ ] Bloc Identification : L'attribut Opération n' a pas lieu d'être présent. Il doit l'être uniquement pour les programmes : nom de l'opération parent)
- [ ]  Bloc Descriptif : L'attribut "Espace total" est incorrect. A remplacer par "Surface Totale"
- [ ]  Bloc Gouvernance : L'attribut "Promoteur" est à supprimer (MOA d'un PA). Pour les OA/SA la MOA correspond au champ Aménageur.
- [ ]  Bloc Activités : Il manque le champ QL1

**Comment by dcottenc** [comment]
@Gaetanbrl  Correction testée : 

- Bloc Descriptif : L'attribut "Espace total" est incorrect. A remplacer par "Surface Total**E**" => **manque le e à "totale"**
- Bloc Activités : Il manque le champ QL1 : demande annulée

**Comment by Gaetanbrl** [comment]
@dcottenc correctif sur le nom "Surface totale" appliqué, déployé visible sur le contexte de VA.

**Comment by dcottenc** [comment]
Correction testée et validée
