### ISSUE TITLE
VA front - Annulation filtre individuelle

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#117]
**Description du bug / Describe the bug**

Lors de l'utilisation des fonctionnalités de filtrage avec plusieurs filtres, Il n'est pas possible d'annuler un filtre sans tous les annuler puis de les ressaisir.
Exemple : je recherche sur Rennes, quartier centre, avec la nature ZAC, les entités livrées entre le 01/01/2020 et 31/12/2020. Si je veux également avoir le résultat mais sur tout Rennes alors je suis obligé de supprimer tous les filtres avec le bouton et de les ressaisir (au lieu de supprimer uniquement le filtre secteur)

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type :  Voir exemple ci-dessus

**Comportement attendu / Exptected behavior**

Nous avons besoin de pouvoir annuler un filtre individuellement.

**Screenshots**

**Environnement / Desktop**

Environnement : RM Portail Test
Version Front v1.0

**Informations complémentaires / Additional context**

**Comment by Gaetanbrl** [comment]
@dcottenc as-tu essayé de supprimer la valeur dans la liste ?

![issue_117](https://user-images.githubusercontent.com/16317988/123437316-d5645100-d5cf-11eb-8719-b9ad3e0deba4.gif)

**Comment by Gaetanbrl** [comment]
Ce comportement avait déjà été montré en démo et diverses points.
Faut-il envisager une autre suppression d'un filtre ?

**Comment by dcottenc** [comment]
> @dcottenc as-tu essayé de supprimer la valeur dans la liste ?

Effectivement, la suppression du filtre est possible. Ni Cyril, ni moi, n'avions pensé à cela. 
Je vais leur présenter ce retour.

**Comment by Gaetanbrl** [comment]
Je vous l'avez montré mais je pense que ce comportement n'a pas été assez relevé.

**Comment by Gaetanbrl** [comment]
En attente retour utilisateur.

**Comment by dcottenc** [comment]
> En attente retour utilisateur.

Fonctionnement actuel validé par M. Baslé (cf. copie d'écran)
A clore.

![image](https://user-images.githubusercontent.com/76009802/127994712-ce057bf1-ea9d-4b30-98fe-cdbe13030224.png)
