### ISSUE TITLE
Champ ql1 manquant

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#118]
**Description du bug / Describe the bug**
==> Remonté en "bug" dans l'issue #116
==> Passé en évolution ici (à traiter) pour permettre de fermer l'issue 116

La description faite en issue #70 de la fiche identification des entités OA/SA pour le bloc "activité" ne contient pas le descriptif du champ `ql1` qui est alors manquant et à développer. 

![image](https://user-images.githubusercontent.com/16317988/123447541-4446a780-d5da-11eb-881a-6d0033cbd2eb.png)

**Comment by Gaetanbrl** [comment]
le code est intégré dans le commit 40cdf2a5536c8b6c91cfc0e6053505f9be57a699 mais doit être finalisé pour préciser le type et donc l'affichage en liste, ou checkbox, ou multi ou text.

**Comment by dcottenc** [comment]
Le champ ql1 n'existe pas. Il y eu confusion avec le champ ql3.
Ce ticket est à clôturer si tu es d'accord

**Comment by Gaetanbrl** [comment]
C'est noté, merci.
Je ferme.
