### ISSUE TITLE
VA front - Ajout Programme - Perte de l'emprise sélectionnée

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#119]
**Description du bug / Describe the bug**

Lors de l'ajout d'un programme à partir de son emprise, cette dernière est perdue lors de la sélection obligatoire de l'opération parent.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire l'anomalie : 
1. Se connecter au contexte Tabou
2. Ouvrir le plugin Tabou
3. Cliquer sur une emprise d'un programme non suivi (id tabou à Null)
4. Cliquer sur Ajouter
5. L'emprise est bien pré sélectionnée dans l'onglet Ajout
6. La sélection obligatoire de l'opération parent supprime la sélection de l'emprise

**Comportement attendu / Exptected behavior**

La sélection de l'emprise du programme ne doit pas être supprimée dans ce cas

**Screenshots**

Si possible, une capture d'écran pour nous aider à voir le problème décrit.
Etape 5
![image](https://user-images.githubusercontent.com/76009802/123450906-802f3c00-d5dd-11eb-9853-54c476378317.png)
Etape 6
![image](https://user-images.githubusercontent.com/76009802/123451044-a05efb00-d5dd-11eb-9043-23cc72697cc7.png)

**Environnement / Desktop**

Environnement : RM Portail Test
Version Front v1.0

**Informations complémentaires / Additional context**

**Comment by Gaetanbrl** [comment]
Vu, reproduis.

**Comment by Gaetanbrl** [comment]
Correctif testable sur l'environnement de test.

![tabou_issue_119](https://user-images.githubusercontent.com/16317988/123460156-81656680-d5e7-11eb-942c-35de119a7a79.gif)

**Comment by dcottenc** [comment]
**Description du bug / Describe the bug**

Le bug est bien corrigé dans ce cas mais du coup l'ajout d'un programme sans cliquer sur une emprise n'est plus possible

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire l'anomalie :

1. Se connecter au contexte Tabou
2. Ouvrir le plugin Tabou
3. Ouvrir l'onglet Ajouter
5. La sélection d'une emprise d'un programme n'est plus possible (pas de liste déroulante avec la liste des emprises disponibles)

**Comment by Gaetanbrl** [comment]
> Le bug est bien corrigé dans ce cas mais du coup l'ajout d'un programme sans cliquer sur une emprise n'est plus possible

En effet, il faut sélectionner l'opération pour débloquer l'emprise.

On avait convenu de deux workflow (voir les issues concernées) : 

- Scénario 1 

Un utilisateur rechercher une emprise selon une opération parente. S'il a cocher la case "Limiter les emprises selon l'opération" alors il doit en premier choisir une opération pour réduire la liste des emprises.

- Scénario 2

Un utilisateur recherche une emprise mais n'a pas cocher la case "Limiter les emprises à l'opération parente". Il faut tout de même choisir en premier une opération pour ensuite choisir l'emprise.


Donc dans tous les cas il faut en premier choisir une opération et ensuite la liste des emprises est sélectionnable. Seul le contenu de la liste "Emprise" doit changer selon l'état de la case à cocher (en cours de correction dans #121)

**Comment by dcottenc** [comment]
> En effet, il faut sélectionner l'opération pour débloquer l'emprise.

J'ai oublié de mettre cette étape dans ma description mais la liste déroulante n'est pas disponible même après avoir sélectionné l'opération

**Comment by Gaetanbrl** [comment]
Vu, corrigé. Le problème était différent et non lié à cette issue.

Je dois créer une issue pour les recherche sur emprise / PLUI car on a plus de 100 résultats par exemple pour les emprises opération de type zac, on a 142 résultats.

**Comment by Gaetanbrl** [comment]
Correction faite @dcottenc et visible sur l'environnement de test.

**Comment by dcottenc** [comment]
On a toujours l'anomalie. En suivant le scénario, on trouve maintenant l'emprise vide mais aussi l'OA.

**Comment by Gaetanbrl** [comment]
Vu pour l'emprise PA mais je ne vois pas pour l'OA.

**Comment by Gaetanbrl** [comment]
Scénario pour PA : 

1. Ouvrir Tabou
2. Cliquer sur une emprise PA sans id Tabou==> OK
3. Cliquer n'importe ou sur la carte en dehors d'une entité OA, PA, SA
4. Choisir "Programmes"
5. Choisir l'opération
6. Voir que l'emprise est en format de champ "text" ==> KO

**Comment by Gaetanbrl** [comment]
Corrigé et déployé.
A tester @dcottenc

**Comment by dcottenc** [comment]
@Gaetanbrl Ce n'est pas corrigé avec mon utilisation qui semble différer de la tienne car j'utilise le bouton Ajouter proposé. Mais en changeant d'onglet je n'ai pas l'emprise non plus. A voir en live ensemble

**Comment by Gaetanbrl** [comment]
> mon utilisation qui semble différer de la tienne

Une démo live est nécessaire, là je ne comprend pas.

**Comment by dcottenc** [comment]
L'affichage du nom de l'emprise est maintenant corrigé (dans Sélectionner une emprise).
Correction testée et validée
