### ISSUE TITLE
VA front - Evolution - Modification de la visualisation de la carte sur l'emprise des entités filtrées

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#122]
**Description du bug / Describe the bug**

Lors de l'utilisation des fonctionnalités de filtrage, serait-il possible lors de la validation du filtre, de centrer la carte sur l'emprise des entités filtrées ?

Exemple : j'effectue un filtre sur la commune de Betton, lors de la validation de ce filtre la carte se recentre sur l'emprise des entités filtrées. Ici l'emprise calculée pour afficher toutes les entités de Betton.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type :  Voir exemple ci-dessus

**Comportement attendu / Exptected behavior**

Recentrer la carte MapStore sur l'emprise qui contient toutes les entités filtrées.

**Screenshots**

**Environnement / Desktop**

Environnement : RM Portail Test
Version Front v1.0

**Informations complémentaires / Additional context**

**Comment by Gaetanbrl** [comment]
@dcottenc ce comportement est possible mais il n'est pas prévu pour la v1. Je le passe en évolution.

**Comment by Gaetanbrl** [comment]
> ce comportement est possible

A vérifier tout de même selon les possibilités MapStore2...

**Comment by dcottenc** [comment]
Oui c'est bien une evolution mais je n'ai pas eu le temps de mettre le label avant que tu répondes :p

**Comment by Gaetanbrl** [comment]
Le plus simple est de réaliser un zoom sur l'opération parente qui concerne la recherche.
Il est en effet complexe de calculer les extents des couches PA / SA / OA selon le résultat de la recherche, car MapStore2 ne prévoit que de de pouvoir réaliser un zoom sur une extent définie.

Cela permet de couvrir les cas suivants :

* Seule la couche PA est visible => Zoom sur l'étendu de la couche PA
* Seule la couche SA est visible => Zoom sur l'étendue des entités SA
* Seuls PA et SA sont visibles => Zoom sur l'étendu des entité SA parente concernées par la recherche
* Autres cas => Zoom sur l'étendue de la couche OA

Contrainte technique restante à soulever : 
* Pouvoir récupérer l'extent pour les cas précédemment cités

**Comment by dcottenc** [comment]
> Le plus simple est de réaliser un zoom sur l'opération parente qui concerne la recherche.

/!\ Attention, une couche peut être filtrée par plusieurs entités de couches différentes.
Si l'intersection de ces couches est possible et que l'on obtient un polygone de filtre spatial par couches alors cela pourrait également servir à contourner la limite sur le nombre d'entés filtrées, non?

**Comment by Gaetanbrl** [comment]
> Si l'intersection de ces couches est possible et que l'on obtient un polygone de filtre spatial par couches

Je ne suis pas bien sur de comprendre...

Pour ce type de zoom on réalise un focus sur l'étendue d'une géométrie (rectangle pour un zoomToExtent).
Il faut alors s'assurer que l'étendue de la géométrie est récupérable.

**Comment by dcottenc** [comment]
> Je ne suis pas bien sur de comprendre...

Désolé, je me suis emmêlé les pinceaux (note à moi même : ne pas faire de commentaire à l'heure de la sieste...)

**Comment by dcottenc** [comment]
Fonctionnalité non incluse dans ce marché
