### ISSUE TITLE
VA front - Fiche OA/PA - Liste déroulante Etape vide

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#125]
**Description du bug**

La liste déroulante "Etape" des fiches des OA et PA sont vides.
Elles devraient afficher la liste des étapes possibles obtenue avec l'API GET /operations/{operationId}/etapes (ou /programmes/{programmeId}/etapes)

**Reproduire le bug / To Reproduce**

1. Ouvrir le plugin Tabou
2. Cliquer sur une OA ou PA suivi dans Tabou (id_tabou non null)
3. L'onglet "Identifier" s'ouvre et affiche les informations de l'entité
4. Dans le groupe "Suivi opérationnel", cliquer sur le bouton de la liste déroulante pour l'étape
5. La liste est vide

**Comportement attendu**

Exemple pour l'OA avec l'ID 46 : 
La liste devrait contenir les deux valeurs ("En étude", "Annulé") obtenues avec l'appel suivant.
Le suivi de cet attribut est le plus important de la fiche.

Appel WS
`https://portail-test.sig.rennesmetropole.fr/tabou2/operations/46/etapes`

Résultat
```
[
  {
    "id": 5,
    "libelle": "En étude",
    "code": "EN_ETUDE_PUBLIC",
    "type": "NORMAL",
    "mode": "PUBLIC"
  },
  {
    "id": 8,
    "libelle": "Annulé",
    "code": "ANNULE_PUBLIC",
    "type": "NORMAL",
    "mode": "PUBLIC"
  }
]
```

**Screenshots**

Ex : affichage OA (id 46)
![image](https://user-images.githubusercontent.com/76009802/123998689-05499500-d9d2-11eb-8010-ba091be3dcef.png)

**Environnement**

Environnement : RM Portail Test
Version Front v1.0
API : v1.1.4

**Comment by Gaetanbrl** [comment]
La liste est vide car il y a la valeur "En projet" qui est reprise de l'élément cliqué, mais si on supprime la valeur du champ, on a bien les éléments de la liste.

Par exemple pour l'opération avec id tabou = 3 on a bien "En projet".
Le composant réalisant une auto complétion recherche "En projet" (valeur par défaut) et retourne une liste vide, étant donné que l'on a que "Annulé" ou "En étude".

Pour afficher les autres éléments, il faut supprimer la valeur initiale pour choisir une autre valeur.

Ce fonctionnement est identique à toutes les liste avec auto complétion gérée par le composant lui-même.

On a 2 options :
* Supprimer l'auto complétion pour ce type de liste
* Forcer l'affichage des valeurs (à voir si c'est possible)
* Placer la valeur par défaut en "placeholder" (donc valeur vide) et donc n'ayant pas de valeur par défaut, alors on a une liste pleine (l'auto complétion n'étant pas déclenchée)

Ce qui m'interpelle car la valeur "En projet" n'est pas retournée par l'API alors qu'on a bien cette valeur dans les données @dcottenc  ? C'est l'API qui retourne que les étapes suivantes ?

**Je passe ce bug de critique à mineur.**

**Comment by dcottenc** [comment]
>On a 3 options :
>  Supprimer l'auto complétion pour ce type de liste
>  Forcer l'affichage des valeurs (à voir si c'est possible)
>  Placer la valeur par défaut en "placeholder" (donc valeur vide) et donc n'ayant pas de valeur par défaut, alors on a une liste pleine (l'auto complétion n'étant pas déclenchée)

Les utilisateurs ne vont pas avoir le reflexe de supprimer la valeur de l'étape pour pouvoir voir les options possibles dans ce type de liste.
La solution de supprimer l'auto complétion pour ce type de liste (Etape) me parait la plus simple et judicieuse.

Ok pour le changement de criticité puisque le changement d'étape est possible.

**Comment by Gaetanbrl** [comment]
Code disponible sur branche develop, pas encore visible dans le contexte (plugin à redéployer)

**Comment by dcottenc** [comment]
Validé, à clore
