### ISSUE TITLE
VA front - Fiche PA - Modification OA parent impossible

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#126]
**Description du bug**

Dans la fiche PA, l'attribut OA parent est non modifiable.
Cet attribut doit pouvoir être modifié à partir de la liste des opérations (cf. onglet ajout PA)

**Reproduire le bug**

1. Ouvrir le plugin Tabou
2. Cliquer sur une PA suivi dans Tabou (id_tabou non null)
3. L'onglet "Identifier" s'ouvre et affiche les informations de l'entité
4. Dans le groupe "Identification", l'attribut Opération est en lecture seule

**Comportement attendu**

L'attribut Opération devrait être modifiable à partir d'une liste déroulante identique à celle présente dans l'onglet Ajout PA

**Screenshots**

![image](https://user-images.githubusercontent.com/76009802/124000255-aab13880-d9d3-11eb-818d-33e022c157ba.png)

**Environnement**

Environnement : RM Portail Test
Version Front v1.0
API : v1.1.4

**Comment by Gaetanbrl** [comment]
Vu, reproduis.

La spécification faite par @dcottenc en #69 est précise, c'est une erreur pendant les développements.

**Comment by Gaetanbrl** [comment]
Code disponible sur branche develop, pas encore visible dans le contexte (plugin à redéployer)

**Comment by dcottenc** [comment]
Le champ est bien modifiable mais le contenu de la liste déroulante n'est pas celui attendu.
On a soit une seule proposition identique à l'OA en cours (ex sur Baud Chardonnet) soit une liste vide.
Attendu = > liste des OA identique à celle de l'onglet Ajout pour les PA

**Comment by Gaetanbrl** [comment]
> On a soit une seule proposition identique à l'OA en cours (ex sur Baud Chardonnet) soit une liste vide.

Il faut supprimer la valeur affichée pour voir les autres OA.
Je ne reproduis pas de bug, je vois bien la liste des OA pour une PA suivie et cliquée.

Ce cas de test est-il le même que tu as essayé ou je déroule le mauvais ?

![PAOA126](https://user-images.githubusercontent.com/16317988/128496827-936c3c22-00ab-45a0-abbe-4325499b7f78.gif)

**Comment by dcottenc** [comment]
Fonctionnement validé.
Mais le contenu de la liste devrait contenir la liste des opérations suivies dans Tabou (comme celle utilisée lors de l'ajout d'un programme).

**Comment by dcottenc** [comment]
@Gaetanbrl Peux-tu m'indiquer avec quelle API tu peuple cette liste déroulante ?

![image](https://user-images.githubusercontent.com/76009802/128510332-c7039493-f1d7-4ed3-8d90-73aa710d2490.png)

**Comment by dcottenc** [comment]
@Gaetanbrl normalement cela devrait etre https://portail-test.sig.rennesmetropole.fr/tabou2/operations?estSecteur=false&asc=true mais elle retourne les 155 objets complets opérations :s

**Comment by Gaetanbrl** [comment]
J'utilise https://portail-test.sig.rennesmetropole.fr/tabou2/operations

Je n'ai pas mis de paramètres.

**Comment by dcottenc** [comment]
> Je n'ai pas mis de paramètres.
Le paramètre estSecteur est nécessaire car sinon on propose des secteurs. Or un programme ne peut être rattaché qu'à une opération (RG du CCTP).

**Comment by Gaetanbrl** [comment]
Je viens de rajouter les paramètres dans l'appel comme tu viens de le préciser. Je déploie le plugin.

Pour la limite, on retombe sur le même problème.
Toutes les liste OA / PA / etc... seront à passer avec un système d'autocomplétions. Sinon à l'API de tout délivrer.

**Comment by dcottenc** [comment]
> Je viens de rajouter les paramètres dans l'appel comme tu viens de le préciser. Je déploie le plugin.

Ok merci
Pour cette API, la recherche nom avec un caractère générique existe et permet donc de réaliser un filtrage de la liste à la place de l'auto complétion du composant

**Comment by Gaetanbrl** [comment]
> Pour cette API, la recherche nom avec un caractère générique existe et permet donc de réaliser un filtrage de la liste à la place de l'auto complétion du composant

C'est une autre issue différente de celle-ci. Pour moi c'est contenu dans la #123.

**Comment by Gaetanbrl** [comment]
la valeur "En diffus" s'intègre dans l'API du type  "En%2520Diffus", ce qui provoque une mauvaise réponse.

**Comment by Gaetanbrl** [comment]
@dcottenc pour la modification d'une opération dans une fiche PA, il n'a pas été précisé que cette liste doit contenir les OA qui corresponde à la nature affichée. Sinon on peut choisir une OA de type "En diffus" alors qu'il est saisi que l'OA parent est de type "ZAC".

Non ?

**Comment by dcottenc** [comment]
> pour la modification d'une opération dans une fiche PA, il n'a pas été précisé que cette liste doit contenir les OA qui corresponde à la nature affichée

La liste des opérations parents ne tient pas compte de la nature. L'OA parent portera la nature associée.

**Comment by Gaetanbrl** [comment]
> La liste des opérations parents ne tient pas compte de la nature. L'OA parent portera la nature associée.

Ok, au rechargement de la fiche donc la nature devra s'affiché selon l'OA parent sélectionnée.

**Comment by dcottenc** [comment]
Correction testée et validée
