### ISSUE TITLE
VA>VSR front - Ajout et Fiche OA/PA - Gestion enregistrement

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#127]
**Description du bug**

Lors de l'enregistrement d'une OA (ou PA) à partir de l'onglet Ajout ou Identifier, l'utilisateur n'a aucune information sur le bon (ou mauvais) déroulement de l'opération.

**Reproduire le bug**

1. Ouvrir le plugin Tabou
2. Cliquer sur une OA ou PA suivi dans Tabou (id_tabou non null)
3. L'onglet "Identifier" s'ouvre et affiche les informations de l'entité
4. Modifier un des attributs de l'entité
5. Cliquer sur Enregistrer => pas d'information

**Comportement attendu**

A partir de l'étape 5, 
6. un message apparait indiquant que l'enregistrement est réussi ou qu'une erreur a eu lieu.
7. dans le cas de l'ajout, bascule sur l'onglet identifier de l'entité ajoutée
8. Refresh de la carte

**Environnement**

Environnement : RM Portail Test
Version Front v1.0
API : v1.1.4

**Comment by Gaetanbrl** [comment]
Ticker pris en compte.

**Comment by dcottenc** [comment]
>Comportement attendu
> 8. Refresh de la carte

**Description complémentaire**
L'étape 8 est à compléter avec le refresh de la fiche du plugin 

**Reproduire le bug**

1. Ouvrir le plugin Tabou
2. Cliquer sur une OA ou PA suivi dans Tabou (id_tabou non null)
3. L'onglet "Identifier" s'ouvre et affiche les informations de l'entité
4. Modifier l'étape de l'entité
5. Cliquer sur Enregistrer 
6. L'étape est bien celle enregistrée mais si on affiche la liste des étapes possibles on a toujours celle de l'ancienne étape

**Comment by Gaetanbrl** [comment]
> L'étape 8 est à compléter avec le refresh de la fiche du plugin

Je sépare les issues.

**Comment by Gaetanbrl** [comment]
- [] Affichage d'un message à la réussie (la traduction sera affichée correctement) :

![image](https://user-images.githubusercontent.com/16317988/124439795-24ea1000-dd7a-11eb-9d0c-6f8ee7e5b991.png)

**Comment by Gaetanbrl** [comment]
> L'onglet "Identifier" s'ouvre et affiche les informations de l'entité

Comportement en cours de réalisation.
L'application de ce comportement n'a pas été remonté auparavant et n'avait pas été prévu.

Actuellement, l'affichage des informations est déclenché au clic sur la carte (workflow natif).
Les données proviennent donc de la carte (getFeatureInfo) et des appels Tabou.

Ici, les données proviennent de la réponse de la création ou alors il faut reproduire le clic sur la feature. Ce qui pose des contraintes / difficultés techniques.

**Comment by dcottenc** [comment]
> L'onglet "Identifier" s'ouvre et affiche les informations de l'entité

Le soucis c'est qu'actuellement, après avoir enregistré  l'entité on peut toujours modifier les champs et enregistrer de nouveau. 

C'est une proposition qui vise à clore le processus de création. On peut également proposer le verrouillage de tous les champs de la fiche de création lorsque l'ajout s'est déroulé correctement ou l'affichage d'un message invitant à consulter le détail dans l'onglet "consulter" du style de celui ci-dessous
![image](https://user-images.githubusercontent.com/76009802/124467913-c84a1d80-dd98-11eb-9e8d-fb66f340ac4e.png)

**Comment by Gaetanbrl** [comment]
> Le soucis c'est qu'actuellement, après avoir enregistré l'entité on peut toujours modifier les champs et enregistrer de nouveau.

Oui j'ai également constaté. Je vais trouver quelque chose pour que ce soit fluide.

**Comment by Gaetanbrl** [comment]
@dcottenc voici un rendu avec rechargement du getFeatureInfo pour consulter une feature qui a été cliquée puis saisie.

Voici le fonctionnement si la saisie provient d'une feature issue de la carte :

* Saisie d'une emorise
* Validation
* Affichage du message de succès de la création
* Update du Get Feature Info (click sur la carte simulé avec les dernières infos de click)
* Affichage de l'onglet "Identifier"

Testable sur : 
https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/Tabou2_Recette

![tabou_127](https://user-images.githubusercontent.com/16317988/124473883-23cbd980-dda0-11eb-8442-8f97cec08783.gif)


Reste à faire sur ce comportement :

* Afficher les infos pour une emprise saisie sans cliquer sur la carte avant
* Test avec SA / OA
* Par défaut, sélectionner la feature saisie

**Comment by Gaetanbrl** [comment]
- [x] Fiche infos : Affichage d'un message à la réussie
- [x] Fiche infos : Affichage d'un message en cas d'échec

Code réalisé, à tester (Données en cours d'intégration par @dcottenc). En attente pour test et fin des développements sur cette issue.

**Comment by dcottenc** [comment]
La solution actuelle semble convenir mais reste à tester complétement quand l'enregistrement des OA sera opérationnel

**Comment by Gaetanbrl** [comment]
A tester dans phase VSR

**Comment by dcottenc** [comment]
Correction testée et validée
