### ISSUE TITLE
VA - Refresh fiche info

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#128]
>Comportement attendu
> 8. Refresh de la carte

**Description complémentaire**
L'étape 8 est à compléter avec le refresh de la fiche du plugin 

**Reproduire le bug**

1. Ouvrir le plugin Tabou
2. Cliquer sur une OA ou PA suivi dans Tabou (id_tabou non null)
3. L'onglet "Identifier" s'ouvre et affiche les informations de l'entité
4. Modifier l'étape de l'entité
5. Cliquer sur Enregistrer 
6. L'étape est bien celle enregistrée mais si on affiche la liste des étapes possibles on a toujours celle de l'ancienne étape

1. Aller sur la page https://ma.page.fr
2. Cliqué sur Rechercher
3. Saisir quelque chose
4. Voir que rien ne se passe (ou l'erreur si identifiable)

**Comportement attendu / Exptected behavior**

Une description courte de ce que vous auriez voulu voir, ce qui ce serait passé sans le problème.

**Comment by Gaetanbrl** [comment]
liée à #127

**Comment by Gaetanbrl** [comment]
Lors de la modification ou sauvegarde d'une fiche, selon le retour de l'API (succès  / échec) on lance un appel de la feature en cours de consultation.

Ce comportement n'a pas pu être finalisé pendant la v1.0.0, étant donné que l'API ne permettait pas la modification / sauvegarde d'une entité Tabou.

**Comment by dcottenc** [comment]
Ce souci est plus général que le simple fait de provoquer un refresh. En effet, les performances actuelles vont sans doute nous contraindre à utiliser des fonctionnalités de cache  pour les couches. Il sera donc impossible d'avoir l'affichage des modifications pendant la durée de validité des couches en cache.
