### ISSUE TITLE
VA Front - Onglet Ajout Programme - Liste déroulante Etape

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#129]
**Description du bug**

Dans l'onglet Ajout, pour un programme, le contenu de la liste déroulante des étapes correspond à celui des opérations et non des programmes

**Reproduire le bug**

1. Ouvrir le plugin Tabou
2. Cliquer sur l'onglet "Ajouter une entité"
3. Sélectionner Programme
4. Ouvrir la liste déroulante des étapes => le contenu contient le choix "Opérationnel" qui n'est pas une étape d'un programme mais d'une opération.

**Comportement attendu**

La liste devrait contenir le contenu proposé par l'API GET /programmes/etapes
```
{
  "elements": [
    {
      "id": 9,
      "libelle": "Annulé",
      "code": "ANNULE_PUBLIC"
    },
    {
      "id": 3,
      "libelle": "Annulé",
      "code": "ANNULE_OFF"
    },
    {
      "id": 8,
      "libelle": "Clôturé",
      "code": "CLOTURE_PUBLIC"
    },
    {
      "id": 6,
      "libelle": "En chantier",
      "code": "EN_CHANTIER_PUBLIC"
    },
    {
      "id": 2,
      "libelle": "En étude",
      "code": "EN_ETUDE_OFF"
    },
    {
      "id": 5,
      "libelle": "En étude",
      "code": "EN_ETUDE_PUBLIC"
    },
    {
      "id": 1,
      "libelle": "En projet",
      "code": "EN_PROJET_OFF"
    },
    {
      "id": 4,
      "libelle": "En projet",
      "code": "EN_PROJET_PUBLIC"
    },
    {
      "id": 7,
      "libelle": "Réalisé",
      "code": "ACHEVE_PUBLIC"
    }
  ],
  "totalElements": 9
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/76009802/124448124-61216e80-dd82-11eb-9f03-14af1b593454.png)

**Environnement**

Environnement : RM Portail Test
Version Front v1.0
API : v1.1.4

**Comment by Gaetanbrl** [comment]
Comment les utilisateurs vont-ils faire la différence entre "En projet" et "En projet" ?

**Comment by dcottenc** [comment]
> Comment les utilisateurs vont-ils faire la différence entre "En projet" et "En projet" ?

Les libellés étapes des programmes vont être corrigés comme ceux des opérations (voir [https://github.com/sigrennesmetropole/geor_tabou2_front/issues/130](url)

**Comment by Gaetanbrl** [comment]
Du coup pas de modification à faire de mon côté si les libellés changent ? 
Etant donné qu'actuellement, j'applique systématiquement un "dinstinct" sur le champ utilisé pour l'affichage (libelle ici).

Je peux rendre paramétrable ce comportement de "dinstinct" et éviter de l'utiliser pour ce cas.

**Comment by dcottenc** [comment]
> Du coup pas de modification à faire de mon côté si les libellés changent ?
> Etant donné qu'actuellement, j'applique systématiquement un "dinstinct" sur le champ utilisé pour l'affichage (libelle ici).
> Je peux rendre paramétrable ce comportement de "dinstinct" et éviter de l'utiliser pour ce cas.

Dans cette anomalie, c'est la liste qui n'est pas correcte.

**Comment by Gaetanbrl** [comment]
> Dans cette anomalie, c'est la liste qui n'est pas correcte.

oui c'est corrigé (à déployer) mais tu évoques deux sujets et je dois distinguer ce qui est à corriger de ce qui est "pour info". J'ai tout de même rajouté la possibilité de faire un distincte ou non (étant auparavant toujours appliqué suite aux problèmes de retours API en doublons).

**Comment by dcottenc** [comment]
Validé, à clore
