### ISSUE TITLE
VA Front - Onglet Ajout Opération - Gestion liste déroulante Etape

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#130]
**Description du bug**

Dans l'onglet Ajout, pour une opération, le contenu de la liste déroulante des étapes : 
- utilise la suppression des doublons. Ce cas ne devrait pas se produire mais il est préférable de les laisser s'afficher;
- est à trier avec l'Id (ordre du workflow des étapes).

**Reproduire le bug**

1. Ouvrir le plugin Tabou
2. Cliquer sur l'onglet "Ajouter une entité"
3. Sélectionner Opération
4. Ouvrir la liste déroulante des étapes =>
-  le contenu contient une seule fois le choix "En projet" alors qu'il existe deux occurences
-  les étapes sont triées par ordre alphabétique

**Comportement attendu**

La liste devrait contenir le contenu proposé par le résultat de l'appel https://portail-test.sig.rennesmetropole.fr/tabou2/operations/etapes?orderBy=id&asc=true

```
{
  "elements": [
    {
      "id": 1,
      "libelle": "En projet",
      "code": "EN_PROJET_OFF"
    },
    {
      "id": 2,
      "libelle": "En étude (off)",
      "code": "EN_ETUDE_OFF"
    },
    {
      "id": 3,
      "libelle": "Annulé",
      "code": "ANNULE_OFF"
    },
    {
      "id": 4,
      "libelle": "En projet",
      "code": "EN_PROJET_PUBLIC"
    },
    {
      "id": 5,
      "libelle": "En étude",
      "code": "EN_ETUDE_PUBLIC"
    },
    {
      "id": 6,
      "libelle": "Opérationnel",
      "code": "OPERATIONNEL_PUBLIC"
    },
    {
      "id": 7,
      "libelle": "Clôturé",
      "code": "CLOTURE_PUBLIC"
    },
    {
      "id": 8,
      "libelle": "Annulé",
      "code": "ANNULE_PUBLIC"
    }
  ],
  "totalElements": 8
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/76009802/124449072-603d0c80-dd83-11eb-839f-8e9aa04ff785.png)

**Environnement**

Environnement : RM Portail Test
Version Front v1.0
API : v1.1.4

**Comment by Gaetanbrl** [comment]
> Ce cas ne devrait pas se produire mais il est préférable de les laisser s'afficher
 
 Je ne comprend pas dans quel cas il est possible que ca se produise ?
 
 Sinon, comment l'utilisateur peut faire la différence entre ces deux libellés identique ?

**Comment by dcottenc** [comment]
> Je ne comprend pas dans quel cas il est possible que ca se produise ?
> Sinon, comment l'utilisateur peut faire la différence entre ces deux libellés identique ?

Je confirme que cela ne devrait pas se produire.
Dans ce cas précis, j'ai failli ouvrir une anomalie car je ne voyais pas les étapes (off) et j'ai testé après correction des libellés (off) qui étaient en doublon et ils sont apparus. Il n'est donc pas souhaitable de supprimer les doublons dans cette liste.

**Comment by dcottenc** [comment]
> Du coup pas de modification à faire de mon côté si les libellés changent ?
> Etant donné qu'actuellement, j'applique systématiquement un "dinstinct" sur le champ utilisé pour l'affichage (libelle ici).
> Je peux rendre paramétrable ce comportement de "dinstinct" et éviter de l'utiliser pour ce cas.

Je pensais que le distinct était une propriété paramétrée pour chaque liste utilisée.
Si c'est un comportement global, je pense que nous pouvons avoir des soucis lié à son utilisation. 
Pour l'instant, je propose de le supprimer car nous n'avons plus de soucis de doublon sur les retours des API.

**Comment by Gaetanbrl** [comment]
> je propose de le supprimer car nous n'avons plus de soucis de doublon

ok je désactive pas défaut et je laisse la possibilité de l'ajouter

**Comment by Gaetanbrl** [comment]
- [ ] les étapes sont triées par ordre alphabétique

**Comment by dcottenc** [comment]
> les étapes sont triées par ordre alphabétique

La demande est de les trier par ID (ordre du workflow) comme indiqué dans la requete https://portail-test.sig.rennesmetropole.fr/tabou2/operations/etapes?orderBy=id&asc=true

**Comment by dcottenc** [comment]
> La demande est de les trier par ID 

Demande déjà traitée. Désolé

**Comment by Gaetanbrl** [comment]
> Demande déjà traitée. Désolé

A fermer ?

**Comment by dcottenc** [comment]
Oui, à clore. Merci
