### ISSUE TITLE
VA Front - Consultation secteur -Undefined dans l'appel de l'API operations/programme

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#132]
**Description du bug**

Lors de la consultation d'un secteur, l'application MapStore plante.
Après recherche, un appel de l'API qui permet de récupérer les programmes du secteur est effectué sans indiquer l'id du secteur ("undefined" à la place).
Pour rappel, cet API retourne systématiquement un http 500 actuellement mais si on effectue la même action avec une opération, l'erreur est correctement gérée et l'opération s'affiche.

**Reproduire le bug**

1. Ouvrir le plugin Tabou
2. Cliquer sur un secteur suivi (avec id_tabou) => MapStore plante

**Comportement attendu**

Le comportement doit être identique pour l'affichage d'une opération et d'un secteur (API utilisées identiques).
Cet appel incorrect bloque l'utilisation de MapStore (plantage)

**Screenshots**

Console > Réseau
![image](https://user-images.githubusercontent.com/76009802/124882392-9de2a500-dfd0-11eb-9145-091ad45f3e6f.png)

Capture d'écran de l'appel précédent l'erreur : on a bien 153 (ID du secteur) renseigné dans l'appel de l'API
![image](https://user-images.githubusercontent.com/76009802/124882530-c5397200-dfd0-11eb-8378-3ef409d17e9e.png)

Capture d'écran de l'appel en erreur : on a "undefined" à la place de l'ID du secteur
![image](https://user-images.githubusercontent.com/76009802/124882703-f2862000-dfd0-11eb-83a3-8aaec35d0296.png)

**Environnement**

Environnement : RM Portail Test
Version Front v1.0
API : v1.1.4

**Informations complémentaires**

Les données utilisées sont maintenant celles issues de la reprise de données

**Comment by Gaetanbrl** [comment]
Depuis l'issue #131 ca devrait être corrigé ==> cette issue est en doublon @dcottenc ?

La correction de l'issue 131 ne fait pas les appels si les services GET /operation ou GET /programme ne retourne rien (comme c'est le cas avec les PA et SA actuellement. (erreur 500). La fiche s'affiche donc vide.

Donc ce cas ne devrait plus exister.

Je n'ai pas re déployé car tous mes tests ne sont pas terminé (erreurs API / travaux sur reprise en cours). Je préfère déployer un plugin un minimum stable...

![tabou_131](https://user-images.githubusercontent.com/16317988/124885803-ee0f3680-dfd3-11eb-8001-ec1ab879ff97.gif)

**Comment by dcottenc** [comment]
> Depuis l'issue #131 ca devrait être corrigé ==> cette issue est en doublon @dcottenc ?

Oui excuse moi. Je n'ai pas vu l'issue 131. Si tu peux déployer rapidement, merci.

**Comment by Gaetanbrl** [comment]
@dcottenc c'est déployé.

**Comment by dcottenc** [comment]
> c'est déployé.

Validé cela fonctionne, à clore merci
