### ISSUE TITLE
VA > VSR - Erreur filtre de la TOC si une couche n'est pas assez filtrée

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#133]
**Description du bug / Describe the bug**

Lorsqu'un utilisateur réalise une recherche et qu'il y a trop de résultat, une erreur apparaît sur la couche concernée.

La requête GET que MapStore2 réalise à l'application d'un filtre à un nombre de caractère >  2000.
La requête GET est donc trop longue en nombre de caractère et provoque une erreur.

En restreignant le nombre de caractère (moins d'ID dans le CQL par exemple), alors les entités s'affichent, il n'y a plus d'erreur.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Ouvrir le plugin Tabou2
2. Ouvrir le volet "Chercher une entité"
3. Appliquer un filtre sur le critère "SAM" avec la valeur "Faisceau ferroviaire"
4. Lorsque possible, cliquer sur "Appliquer"
5. Voir que la couche "Programmes" ne s'affiche pas et voir qu'elle est en erreur
6. Ouvrir pour la couche "Programmes" le menu des filtres et voir que le filtre est cependant bien appliqué

**Comportement attendu / Exptected behavior**

Les entités de toutes les couches qui correspondent aux critères définis s'affichent.

**Screenshots**

![issue_133](https://user-images.githubusercontent.com/16317988/125301538-5e4aee80-e32b-11eb-8121-e76f300eeb2a.gif)

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - Plugin : v1.0

**Comment by Gaetanbrl** [comment]
La limite semble être de 183 entités.
Par mesure de précaution, je propose de limiter à 150 entités et d'afficher un message pour inviter l'utilisateur à restreindre la recherche en ajoutant un nouveau filtre (ex: commune).

**Comment by Gaetanbrl** [comment]
Le nouveau paramètre permettant de limiter les entités a été ajouté dans la documentation et est disponible dans le localConfig.json de ce projet.

https://github.com/sigrennesmetropole/geor_tabou2_front/blob/cee73f50431ba9167e01247bf5d1cea1b5c5f68f/localConfig.json#L375-L376

**Comment by Gaetanbrl** [comment]
A tester par @dcottenc

**Comment by dcottenc** [comment]
Les retours des tests de la MOA montrent que la limite est très souvent atteinte pour des filtres usuels. 
On a potentiellement un risque que la limite liée à la méthode de filtrage ne soit pas satisfaisante pour l'utilisation des filtres.

**Comment by Gaetanbrl** [comment]
le problème est que la limite de 150 est née suite à des tests qui sont bornés par des standards du web et par le coeur MapStore.
Il faudrait alors modifier la requête WMS et créer des requêtes POST et non GET si c'est possible.

**Comment by dcottenc** [comment]
> Il faudrait alors voir pour modifier directement MapStore2 et les requêtes WMS, pour créer des requêtes POST et non GET si c'est possible
Le blocage des requetes POST est au niveau de MapStore (Geosolutions) ou GeOrchestra ?

**Comment by Gaetanbrl** [comment]
> Le blocage des requetes POST est au niveau de MapStore (Geosolutions) ou GeOrchestra ?

Je ne suis pas certain de comprendre la question.
Il n'y a pas de blocage sur le POST. Actuellement les WMS sont interrogés en GET, ce qui limite le nombre d'id que l'on peut passer dans la requêtes générée par le filtre MapStore2.

Donc si on a un soucis sur la limite, c'est dans la mécanique MapStore2.

**Comment by Gaetanbrl** [comment]
Erreur avec "En diffus" et "Rennes".
2 unités à afficher alors que le message s'affiche.

A revoir.

![image](https://user-images.githubusercontent.com/16317988/128487033-df408c21-ce44-4459-9694-fb016291f9c2.png)

**Comment by dcottenc** [comment]
> Il n'y a pas de blocage sur le POST. Actuellement les WMS sont interrogés en GET, ce qui limite le nombre d'id que l'on peut passer dans la requêtes générée par le filtre MapStore2.
Donc si on a un soucis sur la limite, c'est dans la mécanique MapStore2.

Pour préciser la réserve qui est faite sur cette anomalie (ne pas hésiter à me corriger) :

- le fonctionnement actuel du filtre interroge les couches GeoServer en envoyant la liste des ID des entités à afficher : ce fonctionnement trouve ses limites dans le nombre de caractère accepté par la requête GET => Solution, modifier MapStore pour accepter les requetes POST
- si la solution ci-dessus n'est pas possible, nous avons besoin de trouver un autre fonctionnement. Par exemple (attention c'est une supposition fonctionnelle dénuée de base technique) : faire une requête GET avec un filtre spatial contenant la listes des geometries des filtres ?

**Comment by dcottenc** [comment]
> Car c'est bien du GET qui est utilisé pour le croisement géométrique :

Tu veux dire que si j'utilise le filtre spatial MapStore avec une couche et des géométries complexes nous aurions le même soucis ?

**Comment by Gaetanbrl** [comment]
> Tu veux dire que si j'utilise le filtre spatial MapStore avec une couche et des géométries complexes nous aurions le même soucis ?

A vérifier avec les polygones mais je pense que oui.

**Comment by Gaetanbrl** [comment]
Testé => Reproduis avec un polygone complexe.

**Comment by Gaetanbrl** [comment]
Aide demandée sur :
* mailing list mapstore2 le 11/08/21 

Pas de réponse à ce jour :
https://groups.google.com/g/mapstore-developers/c/YgyMn68Gcvk

* comme issue mapstore2-georchestra

Pas de réponse à ce jour @catmorales 
https://github.com/georchestra/mapstore2-georchestra/issues/412

**Comment by Gaetanbrl** [comment]
Passage en VSR

**Comment by dcottenc** [comment]
Demande faite à Catherine pour relancer le ticket 412 GeoSolutions

Hier lors d'une démo, je n'ai jamais réussi à appliquer un filtre. Le message (limite max) apparaissait dans tous les cas.

**Comment by Gaetanbrl** [comment]
En attente d'une revue de GeoSolution - PR 7475 en attente dans le coeur MapStore2.

**Comment by Gaetanbrl** [comment]
En attente de MAJ mapstore2-georchestra et GO RM (après update mapstore2-georchestra de RM) pour test / validation.

**Comment by Gaetanbrl** [comment]
Suite au dernier update de MapStore2-georchestra avec la dernière branche stable MS2, la config peut être appliquée dans le localConfig.json pour test.

Pour l'exemple à suivre, rechercher le paramètre miscSettings dans la doc dev de l'appli MS2 :

https://mapstore.readthedocs.io/en/latest/developer-guide/local-config/

**Comment by dcottenc** [comment]
> Modifier ensuite la valeur du paramètre maxURLLength (ex: 10000).

Peux-tu nous indiquer quelle est la valeur que tu préconises ?
Pour me faire une idée, as-tu une idée de la valeur fixe qu'il y avait avant et qui entrainait notre blocage ?

**Comment by Gaetanbrl** [comment]
> Pour me faire une idée, as-tu une idée de la valeur fixe qu'il y avait avant et qui entrainait notre blocage ?

Aucune valeur n'était utilisée.

> Peux-tu nous indiquer quelle est la valeur que tu préconises ?

Difficile d'évaluer une valeur quand je ne sais pas quels sont les recherches réalisées en générale (selon une utilisation courante).
Il faudra probablement procéder par ajustement.
Commençons par 5000. Sinon vous pouvez analyser les requêtes et observer le nombre de caractères quand l'erreur est retournée.

Je pense qu'il faut toutefois conserver une limite pour ne pas avoir des filtres inutiles de trop grande échelle.

**Comment by Gaetanbrl** [comment]
@dcottenc il faut par contre s'assurer que la bonne version est bien installée chez RM (image docker à jour sur les serveurs RM)

**Comment by dcottenc** [comment]
Nous venons de déployer une nouvelle version de MapStore (21.2) en test.
Le paramètre MapStore  maxURLLength a été renseigné avec la valeur 4000.
Le paramètre nombre max d'entités dans Tabou a été modifié à 1000 (contre 150 auparavant).

Apres plusieurs tests, l'erreur n'est pas apparu. La correction semble donc correcte.
Cependant, les résultats des filtres ne sont pas bons (Ok en prod). Exemple avec le filtre Rennes, on a des opérations hors Rennes qui restent visibles. L'erreur existait avant la modification et elle apparu depuis quelques jours (depuis la mise à jour du contexte effectuée lors du déploiement du plugin ?). 

@Gaetanbrl : Je te remercie de vérifier le fonctionnement des filtres dans portail-test ainsi que que la configuration contexte.

**Comment by Gaetanbrl** [comment]
> @Gaetanbrl : Je te remercie de vérifier le fonctionnement des filtres dans portail-test ainsi que que la configuration contexte.

Une issue + un exemple serait le bienvenu si possible...

**Comment by dcottenc** [comment]
Je te fais l'issue. C'était au cas où tu aurais eu la réponse sans avoir à chercher

**Comment by Gaetanbrl** [comment]
Dans https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/Tabou-lot2

j'ai toujours une erreur en sélectionnant seulement "Rennes" comme commune et aucun autre filtre

**Comment by Gaetanbrl** [comment]
Testé ce jour suite à MAJ de l'image docker.
@dcottenc je te laisse tester + fermer.

**Comment by dcottenc** [comment]
Validée et testée dans portail Test RM. Merci pour la PR
