### ISSUE TITLE
VA - Afficher l'unité de l'espace totale et modifier le comportement du champ

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#134]
**Description du bug / Describe the bug**

* L'unité du champ n'est pas précisée
* Il faut supprimer les chiffres inférieurs à 0 (en attente de retour utilisateur pour + d'infos)

**Reproduire le bug / To Reproduce**

1. ouvrir le plugin
2. Clique sur une opération
3. Ouvrir le volet "Descriptif"
4. Voir la valeur dans le champ "Espace total"
5. Modifier la valeur

**Comportement attendu / Exptected behavior**

1. permettre la saisie d'une surface inférieure à 1
2. Permettre la saisie d'une valeur avec des dixièmes (ex: 1.25)
3. Supprimer les chiffres inférieur à 0

**Comment by Gaetanbrl** [comment]
- [ ] permettre la saisie d'une surface inférieure à 1
- [ ] Permettre la saisie d'une valeur avec des dixièmes (ex: 1.25)
- [ ] Supprimer les chiffres inférieur à 0
- [ ] Afficher l'unité

**Comment by Gaetanbrl** [comment]
@dcottenc quelle est l'unité à afficher ? C'est bien le m² ?

**Comment by dcottenc** [comment]
> quelle est l'unité à afficher ? C'est bien le m² ?

@Gaetanbrl, non, de ce que j'ai lu, l'unité est ha

**Comment by Gaetanbrl** [comment]
@dcottenc modification visible sur les deux contexte : 

![image](https://user-images.githubusercontent.com/16317988/128052780-0e2b91bb-2b30-48ac-9b01-4addd345d58c.png)

**Comment by Gaetanbrl** [comment]
@dcottenc à fermer si ca convient donc.

**Comment by dcottenc** [comment]
@Gaetanbrl La saisie n'est apparemment pas limitée aux chiffres (tests effectués sous Mozilla 78.11)

![image](https://user-images.githubusercontent.com/76009802/128136609-62dc68da-e5e7-4c20-94cc-281f7791fe04.png)

**Comment by Gaetanbrl** [comment]
> La saisie n'est apparemment pas limitée aux chiffres (tests effectués sous Mozilla 78.11)

Le comportement de ce champ semble en effet différent sur ff et chrome.
https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/number

**Comment by Gaetanbrl** [comment]
Sur Firefox, la saisie de caractère alphabétiques est autorisée par défaut mais n'est pas considérée comme une saisie valide.
Lorsque l'utilisateur saisie "abc" et non "123" sur FF, cette saisie n'a pas d'effet.

Dans notre cas, la valeur "surface" restera vide lors de la validation même avec une saisie du type "abc".

Sur FF uniquement, ce comportement natif oblige la validation pour indiquer à l'utilisateur que la saisie doit être de type numérique uniquement.

**Comment by dcottenc** [comment]
> Le comportement de ce champ semble en effet différent sur ff et chrome.

Le bug semble connu. Reste à vérifier le comportement de la validation lors de l'enregistrement d'une OA.
Pour cela, une nouvelle version de l'API est nécessaire (déploiement le 05/08)

**Comment by Gaetanbrl** [comment]
> Reste à vérifier le comportement de la validation lors de l'enregistrement d'une OA.

Je suis en train de tester les événements qui se déclenchent à la saisie (keydown ou keypress) afin de modifier le contenu du champ si c'est du caractère et ne rien afficher.

je ferai un retour.

**Comment by Gaetanbrl** [comment]
Avec un contrôle à l'appuie des touches du clavier, on peut bloquer la saisie des lettres.
Ca semble fonctionner sur FF et Chrome.

Je déploie le plugin sur le contexte RM pour test.

**Comment by dcottenc** [comment]
>Avec un contrôle à l'appuie des touches du clavier, on peut bloquer la saisie des lettres.

C'est ok mais la saisie de la virgule (point du pavé numérique) n'est plus possible également

**Comment by Gaetanbrl** [comment]
> C'est ok mais la saisie de la virgule (point du pavé numérique) n'est plus possible également

Il faut saisir la touche , et non . car je bloque le point. Le point n'étant pas accepté dans ce champ avec FF. Seul Chrome fait considère le point comme une virgule.

Est-ce bloquant d'utiliser la touche virgule pour faire une virgule et non aussi la touche point pour faire une virgule ?

**Comment by Gaetanbrl** [comment]
> C'est ok mais la saisie de la virgule (point du pavé numérique) n'est plus possible également

Modification faite, on peut saisir des virgule et des points. La valeur renvoyées sera dans les deux cas (2,5 et 2.5)  sur FF et Chrome : 2.5

**Comment by dcottenc** [comment]
Correction testée et vallidée
