### ISSUE TITLE
VA>VSR DATA - noms des emprises vides après reprise des données

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#135]
**Description du bug**

Les noms des emprises sont en majorités vides pour les OA / SA / PA.

Cela provoque les problèmes suivants : 
* soucis dans le comportement de l'application (les noms sont repris de l'éléments cliqué sur la carte et permet de savoir si on a choisi ou non une emprise). Ce point peut être corrigé par modification du code.

* Pour l'utilisateur lorsqu'il doit ajouter une entité, il doit sélectionner une emprise. Hors, il ne voit pas les noms et ne sait pas quelle est la bonne emprise : 

![image](https://user-images.githubusercontent.com/16317988/127986360-b20a3cd2-98a3-4aab-8f38-76027b121c3f.png)

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Ouvrir Tabou
2. Cliquer sur l'onglet "Ajouter"
3. Choisir "Opération"
4. Choisir la nature ZA
5. Ouvrir la liste
6. Voir que les valeurs sont vides

**Comportement attendu / Exptected behavior**

L'utilisateur doit pouvoir voir ce qu'il choisit.
L'API renvoi actuellement cet objet :

```
    {
      "id": 664,
      "nom": null
    }
```

Le nom doit être renseigné pour être visible dans la liste.

**Comment by dcottenc** [comment]
Il est nécessaire de s'assurer qu'un nom vide pour une emprise ne provoque pas une erreur. Pour le reste des problèmes liés à ces noms vides (liste déroulante avec des blancs, difficultés de sélection etc…), c'est à RM de gérer.
Concrètement la MOA dispose de ces données depuis plusieurs mois mais les corrections ne sont pas faites… S'ils veulent pouvoir gérer des noms vides, à eux de nous préciser ce que l'on doit faire dans ce cas.
Ma proposition de mettre un nom par défaut (et lequel…) dans les couches est possibles mais il faudra alors sans doute aussi faire évoluer les API.

**Comment by dcottenc** [comment]
Action dcottenc : tests en cours (contenu liste des entités proposées)

**Comment by dcottenc** [comment]
Vérification correction en attente
Le contenu actuel de la liste n'est pas filtrable (indisponibilité critères API (Nom et OA parent))

**Comment by Gaetanbrl** [comment]
à fermer et filtrage à traiter dans #124 ? @dcottenc

**Comment by dcottenc** [comment]
> à fermer et filtrage à traiter dans #124 ?
Je préfère conserver ce ticket en Pending et l'utiliser pour les tests spécifiques pour les noms à Null
