### ISSUE TITLE
VA front - Affichage fiche opération/secteur/programme

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#136]
**Niveau : Mineur**

**Description du bug / Describe the bug**

La fiche Identifier s'ouvre avec tous les blocs fermés. L'utilisateur est obligé d'ouvrir le bloc identification pour voir de quelle entité il s'agit.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Se connecter au contexte Tabou
2. Ouvrir le plugin Tabou
3. Cliquer sur une entité (OA/SA/PA) qui est suivi dans Tabou (id_tabou non null)
4. Cliquer sur l'onglet de consultation de la fiche de cette entité
=> On ne voit pas les infos de l'entité sélectionnée

**Comportement attendu / Exptected behavior**

Le bloc Identification est à ouvrir par défaut. Les autres restent fermés

**Screenshots**

Actuel
![image](https://user-images.githubusercontent.com/76009802/128143796-f2381437-5419-46a9-8250-7ffd179ce395.png)

Attendu
![image](https://user-images.githubusercontent.com/76009802/128143889-636a5d81-c185-4a87-ae94-21b49a63882a.png)

**Environnement / Desktop**

 - Environnement : RM Portail Test 
 - Version Front v1.0

**Informations complémentaires / Additional context**

**Comment by Gaetanbrl** [comment]
Ce comportement (non précisé ultérieurement) vient d'être appliqué et sera disponible lors du prochain déploiement du plugin.

**Comment by dcottenc** [comment]
@Gaetanbrl  Testé et validé. Merci
