### ISSUE TITLE
VA front - Fiche OA/PA - Formatage champs Habitat

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#137]
**Niveau : Mineur**

**Description du bug / Describe the bug**

Des informations de formatage ont été précisées par la MOA. Elles sont liées à la nature des champs.
Fiche OA ou PA / Onglet Habitat :

- Année attribution foncière : année sur 4 chiffres uniquement
- Tous les champs nombres logements : uniquement >= 0

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Se connecter au contexte Tabou
2. Ouvrir le plugin Tabou
3. Cliquer sur une entité (OA/SA/PA) qui est suivie dans Tabou (id_tabou non null)
4. Cliquer sur l'onglet de consultation de la fiche de cette entité
=> Champs du bloc Habitat

**Comportement attendu / Exptected behavior**

Contrôles sur la saisie des champs (cf. Description du bug)

**Environnement / Desktop**

 - Environnement : RM Portail Test 
 - Version Front v1.0

**Comment by Gaetanbrl** [comment]
Il est possible de définir le pas lors du clic sur les flèches haut et bas, la valeur min et max. Mais seule la validation pourra vérifier le champ "Année".

**Comment by Gaetanbrl** [comment]
Je propose ce type d'affichage pour les années incorrectes : 

![issueYearValid](https://user-images.githubusercontent.com/16317988/128166286-533cc4e9-17e4-4917-b309-8cef1314421d.gif)

**Comment by dcottenc** [comment]
Pour le pas, je pense que l'on peut rester sur 1

**Comment by Gaetanbrl** [comment]
> Pour le pas, je pense que l'on peut rester sur 1

Merci, j'ai fait le changement, à déployer.

**Comment by dcottenc** [comment]
En attente validation MOA

**Comment by Gaetanbrl** [comment]
Validé par MOA ce jour en cotech.
