### ISSUE TITLE
VA front - Fiche OA - Bloc Programmes liés

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#138]
**Niveau : Mineur**

**Description du bug**

L'intitulé du bloc n'est pas correct, à corriger par "Liste des programmes" (la liste ne contient que des programmes)
Le label "Liste des programmes" au dessus du tableau est à supprimer.
L'utilisation d'un tableau dynamique n'est pas satisfaisant. La liste des programmes peut être très longue. Un tableau fixe d'une dizaine de ligne avec un ascenseur serait plus adapté.

**Reproduire l'anomalie**

1. Se connecter au contexte Tabou
2. Ouvrir le plugin Tabou
3. Cliquer sur une OA qui est suivie dans Tabou (id_tabou non null)
4. Cliquer sur l'onglet de consultation de la fiche de cette entité
=> Champs du bloc Secteurs et programmes liés

**Comportement attendu**

(cf. Description du bug)

**Environnement**

 - Environnement : RM Portail Test 
 - Version Front v1.0

**Comment by Gaetanbrl** [comment]
Modifications réalisées, en cours de déploiement sur le contexte RM.

**Comment by dcottenc** [comment]
Le scroll ne peut-il pas être à l'intérieur du tableau ? Sans cela, on perd la visibilité sur les entêtes des colonnes

**Comment by Gaetanbrl** [comment]
> Le scroll ne peut-il pas être à l'intérieur du tableau ?

Je peux regarder mais ce n'est pas un classeur Excel.

**Comment by Gaetanbrl** [comment]
Visiblement, MapStore2 utilise une librairie https://adazzle.github.io/react-data-grid pour afficher les attributs d'une couche.
On peut réutiliser ses composants pour nos tableaux.

**Comment by Gaetanbrl** [comment]
@dcottenc c'est de toute façon une évolution qui demande de refaire tout le tableau.

**Comment by dcottenc** [comment]
Correction testée et validée
