### ISSUE TITLE
V2 - Fiche OA - Bloc Programmes liés

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#139]
## Description

L'affichage des programmes liés s'effectue à l'aide d'un tableau simple, l'objectif est de le rendre plus dynamique.

**En tant qu'utilisateur**
**Je souhaite disposer de fonctionnalités dynamiques dans le tableau**
**Afin de trier et sélectionner les programmes**

## (Si) Règles spécifiques - Règles métiers
- [ ] Il est souhaitable de conserver l'affichage des en-tête et ne pas les masquer au scroll
- [ ] Tri par défaut : la liste des programmes est trié par défaut sur le Nom par ordre alphabétique
- [ ] Tri des colonnes : l'utilisateur doit pouvoir effectuer un tri asc/desc sur chaque colonne
- [ ] Sélection : l'utilisateur doit pouvoir cliquer sur une ligne pour sélectionner un programme. Ce clic entraine le centrage de la fenêtre Carto sur le programme sélectionné (reprendre comportement natif effectué dans le plugin table attributaire ?) SUPPRIME et finalement REPRIS " et l'affichage des informations de ce programme dans le plugin Tabou." (cf. COTECH et CR du 18/08 - à traiter dans #152 )

## (Si) Tests d'acceptabilité

Tri par défaut, tri pour chaque colonne et sélection d'un programme (tests à détailler)

**Comment by Gaetanbrl** [comment]
Pour cette évolution, il sera nécessaire de modifier tous le tableau et d'utiliser ce composant : 

https://adazzle.github.io/react-data-grid

C'est ce composant qui est utilisé pour afficher les attributs d'une couche, donc il est déjà disponible dans mapstore2.

**Comment by dcottenc** [comment]
@Gaetanbrl Description mise à jour

**Comment by Gaetanbrl** [comment]
# Note

MS2 utilise une version Azzadle ancienne : `"react-data-grid": "5.0.4"`

La documentation actuelle sur la page https://adazzle.github.io/react-data-grid/#/common-features n'est plus applicable.

# Limites
Le composant est limité (ex: traduction, affichage par défaut des filtres, etc.) et ne seront pas implémentés dans cette version.

# Solutions
1 Voir les issues passées
https://github.com/adazzle/react-data-grid/issues/

2 Voir le code source directement du tag `v5.0.4` 
https://github.com/adazzle/react-data-grid/tree/v5.0.4

3 Surcharger / étendre les composants existants via une classe reactjs :

`class TabouDataGrid extends ReactDataGrid {`

**Comment by dcottenc** [comment]
Fonctionnalité non incluse dans ce marché
