### ISSUE TITLE
VA front - Onglet Identifier - Actualisation liste types entités

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#140]
**Niveau : Mineur**

**Description du bug**

L'onglet Identifier contient une liste des types des entités lié à la visibilité des couches correspondantes dans la TOC.
L'actualisation de la liste lors de la modification de la visibilité des couches n'est pas satisfaisante.
Le tri alphanumérique est à remplacer par celui fixe des types (Opération puis Secteur puis Programme)

**Reproduire l'anomalie**

1. Se connecter au contexte Tabou
2. Ouvrir le plugin Tabou
3. Cliquer sur une OA qui est suivie dans Tabou (id_tabou non null)
4. Ouvrir la TOC est rendre visible les couches secteurs et programmes
5. Cliquer sur une entité qui est suivie dans Tabou (id_tabou non null)
=> La liste ne contient pas les trois types d'entités attendus, il manque systématiquement celui qui correspond à la deuxième couche rendue visible

**Comportement attendu**

La liste des types d'entité doit toujours correspondre à la liste des couches aménagements visibles dans la TOC.

**Screenshots**

![image](https://user-images.githubusercontent.com/76009802/128335567-076e585e-bdde-4ff4-a0d2-504fda674dd0.png)

**Environnement**

 - Environnement : RM Portail Test 
 - Version Front v1.0

**Comment by Gaetanbrl** [comment]
@dcottenc peux-tu me donner précisément ton cas de test avec l'entité exactement cliquée ?

Pour rappel la liste n'affiche que les layers qui ont une entité retournée par le clic.
Ton exemple ici me laisse penser qu'il n'y a tout simplement pas d'entité de la couche secteur à afficher.

**Comment by dcottenc** [comment]
> Ton exemple ici me laisse penser qu'il n'y a tout simplement pas d'entité de la couche secteur à afficher.
Non je confirme qu'il y avait un secteur au niveau du clic.
Tu peux essayer sur n'importe quel programme ou secteur de Baud Chardonnet

**Comment by Gaetanbrl** [comment]
> Tu peux essayer sur n'importe quel programme ou secteur de Baud Chardonnet

Ok vu.

**Comment by Gaetanbrl** [comment]
A tester.
Je créer une issue pour l'affichage par ordre alpha, étant une évolution...

**Comment by dcottenc** [comment]
Validé

A confirmer, le fonctionnement est-il bien lié aux noms des couches dans la TOC ?
Si oui : 
- il manque un s au nom de la couche opération(s), peux-tu modifier ton traitement ?
- c'est une contrainte a bien prendre en compte coté RM.

**Comment by Gaetanbrl** [comment]
> A confirmer, le fonctionnement est-il bien lié aux noms des couches dans la TOC ?

Oui, le nom de la couche n'ayant pas de "s"... 

Voir issue #141

**Comment by Gaetanbrl** [comment]
> il manque un s au nom de la couche opération(s), peux-tu modifier ton traitement ?

C'est à modifier dans la TOC surtout aussi.

**Comment by Gaetanbrl** [comment]
Je clos.
