### ISSUE TITLE
VA - Identifier - Affichage des noms de couches par ordre alpha

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#141]
**Description du bug / Describe the bug**

Le tri alphanumérique est à remplacer par celui fixe des types (Opération puis Secteur puis Programme)

Voir issue #140 pour plus de précisions.

![image](https://user-images.githubusercontent.com/16317988/128368701-8fe32465-1bae-4a33-b74c-73e4cb606e6d.png)

Tâches : 

- [ ] Documentation config
- [ ] Passer en configuration la possibilité de définir un ordre selon le nom de la couche (titre visible en TOC)

**Comment by Gaetanbrl** [comment]
Travaux en cours. Les opérations sont pour le moment interrogeable suite à un test sur l'environnement RM dû à la modification apportée pour cette issue.

Actuellement les modifications fonctionnent en local mais pas sur le portail RM qui provoque un bug... je ne sais pas pourquoi, je suis en cours d'analyse.

**Comment by Gaetanbrl** [comment]
Le problème provient du nom de la couche "Opération" alors qu'elle était nommée "Operations" auparavant.

**Comment by Gaetanbrl** [comment]
![image](https://user-images.githubusercontent.com/16317988/128390600-e2219041-9b28-4714-8b50-e47694f16f00.png)

**Comment by dcottenc** [comment]
La couche Opérations doit bien être au pluriel comme les autres.  
Je ne vois pas d'où vient ce changement. Puis-je renommer la couche sans altérer le fonctionnement du plugin ?

**Comment by Gaetanbrl** [comment]
>  Puis-je renommer la couche sans altérer le fonctionnement du plugin ?

Non.

Par défaut c'est l'ordre des couches dans la TOC qui était affiché (Programme, secteur, opération) pour le dernier cas de test avant cette issue.

Pour pouvoir appliquer un ordre différent il faut obliger la liste à se baser sur une liste strictement définie et donc différente de l'ordre des couches dans la TOC : 
* Opération
* Secteurs
* Programmes

Pour appliquer cet ordre, on ne peut se baser sur le nom de la couche, son index ou son son nom GeoServer puisque ces trois éléments peuvent changer à tout moment et modifier l'ordre prédéfini.

Les seuls moyens sont : 

* Ajouter une configuration pour imposer un ordre à partir des noms des couches - C'est une source d'oublie !
* Ajouter la liste en constante dans le code à partir des noms - Ce n'est pas gérable par un administrateur car il faut modifier le code, le rebuilder, re déployer le plugin à chaque modification

**Comment by dcottenc** [comment]
> je préconise toutefois la saisie dans la configuration car il y a déjà des éléments propres au nom GeoServer des couches.

Je pense que l'on ne peux pas faire l'économie d'une configuration qui permettrait au plugin d'avoir une correspondance définie entre la couche OA et chaque type d'entité (opération**S**, secteurs, programmes)
L'adhérence au éléments de GeoServer n'est pas satisfaisante car ces éléments sont modifiables par d'autres acteurs.

**Comment by Gaetanbrl** [comment]
> Je pense que l'on ne peux pas faire l'économie d'une configuration

C'est noté, je rajoute cet élément en configuration. Je mettrai la doc à jour également.

**Comment by Gaetanbrl** [comment]
Effectif sur l'environnement de test.
A tester et clore @dcottenc

**Comment by dcottenc** [comment]
Correction testée et validée.
Configuration validée
