### ISSUE TITLE
V2 - Plugin - Affichage onglet Création lié aux droits

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#142]
## Description

L'affichage de l'onglet Création d'entité doit être effectif uniquement si l'utilisateur à les droits requis.

**En tant qu'utilisateur avec les droits "Référents"**
**Je souhaite disposer de l'onglet Ajouter**
**Afin de pouvoir créer des suivi d'entité**

## (Si) Règles spécifiques - Règles métiers
L'onglet "Ajouter" n'est visible que pour les utilisateurs avec les droits "Référents"

## (Si) Tests d'acceptabilité

Tests avec un utilisateur sans les droits "référent" :

1. Ouvrir le plugin Tabou 
L'onglet création n'est pas visible (seuls Recherche et Identifier le sont)

Tests avec un utilisateur avec les droits "référent" :

1. Ouvrir le plugin Tabou 
L'onglet création est visible

## Complément (modifié le 11/08)

Les utilisateurs ne doivent disposer d'aucun moyen d'accéder au contenu / à l'onglet "Ajouter".

**Comment by dcottenc** [comment]
@Gaetanbrl le ticket est indiqué comme Test, j'ai donc testé mais l'onglet Ajout est toujours visible quel que soit le rôle (sous Firefox). Est-ce bien déployé ?

**Comment by Gaetanbrl** [comment]
Je viens de tester avec les users suivants :

* tconsult => Ne voit pas l'onglet "Ajouter" ==> OK
* tcontrib=> Ne voit pas l'onglet "Ajouter" ==> OK
* treferent => Voit pas l'onglet "Ajouter" ==> OK

**Comment by dcottenc** [comment]
> quels sont les rôles que tu as testés ?
Je pense que le soucis concerne l'actualisation de mon profil. J'ai oublié de me déconnecté/connecté...

**Comment by Gaetanbrl** [comment]
Testé avec FF, idem :

tconsult => Ne voit pas l'onglet "Ajouter" ==> OK
tcontrib=> Ne voit pas l'onglet "Ajouter" ==> OK
treferent => Voit l'onglet "Ajouter" ==> OK

**Comment by dcottenc** [comment]
L'onglet Ajouter est toujours accessible pour les utilisateurs qui n'ont pas les droits.

1. Se connecter avec un utilisateur hors référent
2. Ouvrir le plugin Tabou
3. Cliquer sur un programme "non suivi"
4. Le message indiquant que l'entité est non suivi apparait
5. Cliquer sur le bouton Ajouter => Affichage de l'onglet Ajout PA 

Plusieurs solutions possibles. @Gaetanbrl  A voir ensemble pour trouver la plus simple pour toi ?

**Comment by Gaetanbrl** [comment]
Il faut masqué le contenu du volet "identifier" donc.

**Comment by dcottenc** [comment]
Nous souhaiterions, si possible, que lors du clic sur un entité non suivie, le message affiché soit différent quand on a pas les droits.
Exemple (non contractuel) : "Cette entité ne fait pas l'objet d'un suivi dans Tabou. Pour activer le suivi contacter le service SPEU/UCUF mail".

Sinon, plus simple bouton inactivé avec popup "Vous n"avez pas les droits requis"

**Comment by dcottenc** [comment]
Je propose à Myriam pour validation et afin qu'elle nous fournisse le contact. Merci

**Comment by Gaetanbrl** [comment]
Le contact n'est pas à mettre dans le volet "aide" qui est prévu en évolution ? On pourra mettre un bouton d'ouverture de cette fenêtre à ce moment.

**Comment by dcottenc** [comment]
>Le contact n'est pas à mettre dans le volet "aide (ou "contact") qui est prévu en évolution ? On pourra mettre un bouton d'ouverture de cette fenêtre à ce moment.

@Gaetanbrl question posée à la MOA

**Comment by Gaetanbrl** [comment]
> la demande suivante : remplacer la fin du message par un lien hypertexte "mailto..." avec un email paramétré dans le fichier de config du plugins

L'affichage d'un mail est en plus de l'affichage de l'onglet création selon les droits.

Pour toute nouvelle demande sur un ticket qui a déjà été traité ==> **_Nouveau ticket_**

**Comment by dcottenc** [comment]
@Gaetanbrl Je veux bien mais là tu nous fais une proposition à laquelle je réponds en t'apportant des précisions. Cela ne me dérange pas de faire un autre ticket mais c'est toujours pénible de suivre un ticket et de devoir en changer pour voir la fin. 
Une demande n'est pas traitée quand on est au stade des propositions.

**Comment by Gaetanbrl** [comment]
> Une demande n'est pas traitée quand on est au stade des propositions.

Je vais créer un ticket pour ma proposition :)  

Sinon je ne m'en sors pas, les tickets grossissent et le risque c'est que à la fin on a traité plusieurs sujets en un seul, et qu'on ne retrouve plus où on a traité quel sujet... en plus ca me permet de lier les commits (bout de code) à des issues afin de savoir pourquoi on a coder cette fonctionnalité.

**Comment by dcottenc** [comment]
> Je vais créer un ticket pour ma proposition :)

Pas de soucis, je comprends.

**Comment by Gaetanbrl** [comment]
Evolution sur le message + email => #160

**Comment by Gaetanbrl** [comment]
Ticket à fermer ?

**Comment by dcottenc** [comment]
Testée et validée
