### ISSUE TITLE
V2 - Identifier PA - Affichage sources données (interfaces externes)

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#143]
## Description

L'affichage de la source des données externes est à renforcer

**En tant qu'utilisateur**
**Je souhaite distinguer et identifier facilement les données externes**
**Afin de ne pas les confondre avec les autres données saisies par les utilisateurs**

## (Si) Règles spécifiques - Règles métiers
Actuellement, les données externes sont présentes dans la fiche Identifier d'un PA, et sont constituées des tableaux données DDC et Agapéo. Ces deux noms font références à des outils informatiques qui ne sont pas forcement connus des utilisateurs.

- [ ] Un bouton ou lien info à proximité du titre des Tableaux pourraient permettre d'afficher un texte.
Par exemple :

- Données issues du logiciel Agapéo du Service Habitat
- Données issues du logiciel Droits de Cités du Service Droits des Sols

- [ ] Un affichage distinctif des titres ou de la présentation des Tableaux est à  effectuer
- [ ] Modifier Tableau DDC
- numAds (N° ADS)
- depotDossier (Date dépôt)
- adsDate  (Date décision)
- docDate (Date DOC)
- datDate (Date DAACT)

## (Si) Tests d'acceptabilité

(tests à détailler)

## Complément (graphique, capture, schéma, etc.)

**Comment by Gaetanbrl** [comment]
@dcottenc pour cette issue je propose d'ajouter une phrase  en italique sous le tableau pour afficher que les données proviennent de droit de cité ou Agapéo. On ajoutera à côté un liens vers une page de l'aide en ligne qui explique les données et les différentes sources.

Je ne suis pas certain de comprendre la phrase suivante : 

> Un affichage distinctif des titres ou de la présentation des Tableaux est à effectuer

**Comment by dcottenc** [comment]
> Un affichage distinctif des titres ou de la présentation des Tableaux est à effectuer

L'objet de ce ticket est que l'utilisateur distingue bien que les données des tableaux sont issues de sources externes.
Nous avions donc pensé à : 

- Modifier le titre pour qui précise bien la source de données (Agapéo ou DDC) ;
- si le lien ne peut pas être mis dans le titre alors oui un lien en dessous du tableau peut convenir

Je te remercie également de modifier les colonnes affichées pour le  tableau DDC : 

- numAds (N° ADS)
- depotDossier (Date dépôt)
- adsDate  (Date décision)
- docDate (Date DOC)
- datDate (Date DAACT)
- 

-

**Comment by Gaetanbrl** [comment]
> Modifier le titre pour qui précise bien la source de données (Agapéo ou DDC) ;

D'après ce que je vois, on a déjà le nom DDC et AGAPEO de visible au dessus des tableaux. On pourra donc rajouter le lien sans problème dans ce titre. Il faudra passer par de la configuration dans le help de la config de l'aide en ligne :

```
	"help": {
	  "urlDdc":  "",
	  "urlAgapeo":  "",
	  "url": "https://public.sig.rennesmetropole.fr/ressources/app/georchestra/Portail%20web%20guide%20rapide%20de%20prise%20en%20main.pdf",
	  "contact": "d.cottencin@rennesmetropole.fr"
	},
```

> Je te remercie également de modifier les colonnes affichées pour le tableau DDC :

Actuellement nous avons les champs suivants :

- numAds
- adsDate

Les champs suivants seront rajoutés donc : 

- Champ docDate avec le libbellé Date DOC

**Comment by dcottenc** [comment]
> D'après ce que je vois, on a déjà le nom DDC et AGAPEO de visible au dessus des tableaux.

Alors pour les utilisateurs attentifs cela fonctionne. Mais dans la réalité, ces deux titres ne ressortent pas vraiment.
Le lien à coté permettra déjà de pouvoir lié un document explicatif.
On pourrait être plus explicite en remplaçant "Données Agapeo" par "Données du service Habitat (Agapéo)" et le mettre un peu plus en évidence.

**Comment by dcottenc** [comment]
pour DDC, "Données du service Droit des Sols (DDC)"

**Comment by dcottenc** [comment]
Agapéo et DDC pouvant être le texte lié au lien hyertexte

**Comment by Gaetanbrl** [comment]
J'ai modifié les libellé pour les titres des tableaux.
Je vais faire ressortir les titre d'une manière ou d'une autre et rajouter une icône d'aide cliquable à côté (avec une tooltip).

Je reste sur ma position de la V1 qu'une formation (+ aide en ligne ;) ) sera plus qu'utile pour les utilisateurs que des aides dans à tous les libellés...

**Comment by dcottenc** [comment]
> Je reste sur ma position de la V1 qu'une formation (+ aide en ligne ;) ) sera plus qu'utile pour les utilisateurs que des aides dans à tous les libellés...

Je partage ta position, il n'y aura un lien que pour ces deux tableaux

**Comment by dcottenc** [comment]
> Je reste sur ma position de la V1 qu'une formation (+ aide en ligne ;) ) sera plus qu'utile pour les utilisateurs que des aides dans à tous les libellés...

Je partage ta position, il n'y aura un lien que pour ces deux tableaux

**Comment by Gaetanbrl** [comment]
Voici une proposition pour la MOA @dcottenc si cela te convient : 

![143_1](https://user-images.githubusercontent.com/16317988/143612465-8e57d874-3936-49c3-8cb3-b0de74510fa5.gif)


Les paramètres seront les suivants dans la config de tabou : 

```
                "help": {
                    "url": "https://public.sig.rennesmetropole.fr/ressources/app/georchestra/Portail%20web%20guide%20rapide%20de%20prise%20en%20main.pdf",
                    "contact": "d.cottencin@rennesmetropole.fr",
                    ddc: "https://...main.pdf#page=5",
                    ads: "https://...main.pdf#page=26"
                },
```

Dans cette configuration, Je ne permet pas de seulement saisir une page pour les paramètre `ddc` et `ads` car on peut avoir une URL différente.
Si c'est la même documentation, il faudra mettre le même lien avec la page à la fin sous la forme `#page=6` coimme dans l'exemple ci-dessus pour ouvrir le document sur une page spécifique de la doc.

Je vais déployer cette proposition sur le contexte VSR.

**Comment by Gaetanbrl** [comment]
# Blocage


Déploiement de la config impossible avec une URL d'aide contenant un caractère # sur le portail-test en raison d'un blocage du F5 Rennes Métropole. Ce caractère est utilisé pour renseigner la page à ouvrir lors de l'ouverture d'un PDF avec la liseuse chrome au sein d'une URL pointant vers un PDF.

Ex : 
`ads: "https://...main.pdf#page=26#" `

Voici un extrait de la config (voir paramètre ADS pour l'exemple) :

```
                "help": {
                    "url": "https://public.sig.rennesmetropole.fr/ressources/app/georchestra/Portail%20web%20guide%20rapide%20de%20prise%20en%20main.pdf",
                    "contact": "d.cottencin@rennesmetropole.fr",
                    ddc: "https://...main.pdf#page=5",
                    ads: "https://...main.pdf#page=26#" 
                },
```

Problème remonté à @catmorales le 26/11/2021.

------

Informations sur la requêtes.

## Retour

The requested URL was rejected. Please consult with your administrator.

Your support ID is: **6549129882866924533**


## Requête

**General**
```
URL de requête: https://portail-test.sig.rennesmetropole.fr/mapstore/rest/geostore/data/4942
Mode de requête: PUT
Code d'état: 200 OK
Adresse distante: 185.150.252.41:443
Règlement sur les URL de provenance: strict-origin-when-cross-origin
```
**Headers**
```
access-control-allow-headers: Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
access-control-allow-methods: GET, HEAD, OPTIONS
access-control-allow-origin: https://portail-test.sig.rennesmetropole.fr
cache-control: no-cache
content-encoding: gzip
content-type: text/html;charset=utf-8
pragma: no-cache
strict-transport-security: max-age=31536000; includeSubDomains; preload;
transfer-encoding: chunked
vary: Accept-Encoding
x-content-type-options: nosniff
x-xss-protection: 1; mode=block

```

**Comment by dcottenc** [comment]
>Voici une proposition pour la MOA @dcottenc si cela te convient (visible dans contexte VSR).

Nos remarques :  

- nous souhaiterions avoir une ligne d'espace entre les attributs et le titre des tableaux
- le nom des paramètres "ddc" et "ads" dans la config sont à remplacer par "Agapeo" pour le bloc Habitat et "ddc" pour le bloc Droit de Cités

**Comment by Gaetanbrl** [comment]
> dans la config

Dans la config du plugin tabou ?

**Comment by Gaetanbrl** [comment]
> nous souhaiterions avoir une ligne d'espace entre les attributs et le titre des tableaux

Est-ce que cet affichage convient @dcottenc ?

![image](https://user-images.githubusercontent.com/16317988/145054016-4b2fdd1c-051e-44bc-9a73-adcb2c2855ef.png)

**Comment by dcottenc** [comment]
> Est-ce que cet affichage convient @dcottenc ?

Je te remercie de supprimer la ligne entre le titre et le tableau (cf. ci-dessous)

![image](https://user-images.githubusercontent.com/76009802/145056173-33c5ca45-5a2e-46dd-ba37-5c23e5207213.png)

**Comment by dcottenc** [comment]
> Dans la config du plugin tabou ?

Oui les paramètres de la config ci-dessous


                "help": {
                    "url": "https://public.sig.rennesmetropole.fr/ressources/app/georchestra/Portail%20web%20guide%20rapide%20de%20prise%20en%20main.pdf",
                    "contact": "d.cottencin@rennesmetropole.fr",
                    ddc: "https://...main.pdf#page=5",
                    ads: "https://...main.pdf#page=26#" 
                },

**Comment by dcottenc** [comment]
> Donc seul ads est à renommer en agapeo tel que :

Oui, en vérifiant que le paramètre "ddc" correspond bien au titre du tableau ddc et pour "agapeo" au tableau Agaepo

**Comment by Gaetanbrl** [comment]
Fait et visible sur Tabou-VSR @dcottenc .

**Comment by dcottenc** [comment]
Validée par la MOA
