### ISSUE TITLE
V2 - FIches OA et PA - Ajout boutons Tiers dans Gouvernance

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#144]
## Description

Plusieurs utilisateurs ont été déroutés par l'affichage des tiers du bloc Gouvernance en lecture seule. Le bouton Tiers n'étant plus visible, ils n'ont pas eu le reflexe de remonter en haut de la fiche.

**En tant qu'utilisateur**
**Je souhaite disposer des boutons tiers pour les champs Tiers**
**Afin d'accéder directement à la fenêtre de modification de ce type de tiers**

## (Si) Règles spécifiques - Règles métiers
La demande porte sur l'ajout d'un bouton tiers à la suite de chaque champ qui contient un ou des tiers. A l'ouverture de la fenêtre Tiers, le filtre est automatiquement placé sur le type du champ concerné (non modifiable ?). A l'enregistrement, le contenu du champ est actualisé.

Fiche OA :

- [ ] Gouvernance / Aménageur : Bouton Tiers (filtre MOA)
- [ ] Gouvernance / Maîtrise d'œuvre : Bouton Tiers (filtre MOE)

Fiche PA :

- [ ] Gouvernance / Promoteur : Bouton Tiers (filtre MOA)
- [ ] Gouvernance / Maîtrise d'œuvre : Bouton Tiers (filtre MOE)

## (Si) Tests d'acceptabilité

(tests à détailler)

## Complément (graphique, capture, schéma, etc.)

**Comment by Gaetanbrl** [comment]
@dcottenc depuis portail-test, peux-tu me partager des entités  OA ou SA ou PA avec des tiers (au moins un) pour que je puisse tester mes développements ? 

Puis-je sinon en créer 2 pour : 

OA - Baud Chardonnet
SA - id_tabou 407
PA - id_tabou 152

Vide de tiers, je souhaiterai donc en associer / en créer (label spécial test-PA-x ou test-SA-x ou test-OA-x dedans).

**Comment by Gaetanbrl** [comment]
Erratum, sans base de test je ne vais pas créer de tiers si besoin (conformément à ce qui a été dis pendant nos échanges précédents).

Cette issue restera bloquée si je ne vois pas d'association de tiers avec des entités OA / PA.

**Comment by Gaetanbrl** [comment]
@dcottenc, nous proposons cet affichage : 

![image](https://user-images.githubusercontent.com/16317988/143859652-aa2b2291-b75d-41e6-9cba-948d16254ab3.png)


Est-ce que cela convient ?

**Comment by dcottenc** [comment]
> Est-ce que cela convient ?

Oui c'est bien à cela que je pensais avec le premier qui ouvre la fenêtre des tiers filtrée sur le type tier MOA et le second sur MOE (filtres présélectionnés)

**Comment by Gaetanbrl** [comment]
> Oui c'est bien à cela que je pensais avec le premier qui ouvre la fenêtre des tiers filtrée sur le type tier MOA et le second sur MOE (filtres présélectionnés)

Oui normalement bien  le comportement prévu... si je peux tester je confirmerai :)

**Comment by Gaetanbrl** [comment]
@dcottenc Visible sur le contexte Tabou-VSR :

![image](https://user-images.githubusercontent.com/16317988/145018961-06ff6a02-990a-4a7c-9ab4-541f99a70be0.png)

**Comment by dcottenc** [comment]
Présence boutons et ouverture modale Tiers testées et validées
