### ISSUE TITLE
VA > VSR front - Ajout Programme - Pas de rafraichissement de la carte

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#145]
**Niveau : Mineur**

**Description du bug**

Lors de la création du suivi d'un programme, la plupart des actions se passent bien :

- enregistrement des données
- bascule sur fiche identifier du programme créé
Mais il manque le rafraichissement de la carto. La couleur du polygone ne se met à jour que si l'on change le zoom et reste inchangée dans le niveau de zoom utilisé lors de la création.

**Reproduire l'anomalie**

1. Se connecter au contexte Tabou
2. Ouvrir le plugin Tabou
3. Cliquer sur un PA non suivi (id_tabou null)
4. Cliquer sur ajouter et remplir les champs nécessaires à l'ajout
5. Enregistrer => l'emprise du programme reste avec la symbologie "Non suivi"
6. Modifier le niveau de zoom de la carte => l'emprise est mise à jour

**Comportement attendu**

Lors de l'enregistrement d'un PA, l'actualisation de l'affichage de la couche programme est à réaliser. L'utilisateur peut ainsi identifier que cette entité est suivi.

**Environnement**

 - Environnement : RM Portail Test 
 - Version Front v1.0

**Comment by Gaetanbrl** [comment]
Analyse en cours. 
Les images affichées à l'écran doivent être rechargées selon deux façons : 
* Manuellement pas un zoom, un drag ou un refresh manuel de la couche pour forcer les tuiles à se recharger (recalcul des images)
* Automatiquement via une méthode OpenLayers type [`refresh`](https://openlayers.org/en/latest/apidoc/module-ol_source_TileWMS-TileWMS.html#refresh)

**Comment by Gaetanbrl** [comment]
**Suite de l'analyse :** 

MapStore2 dispose d'une action pour rafraîchir une couche (REFRESH_LAYERS). Cette action permet donc une mise à jour des informations de la couche mais pas de déclencher le rechargement des tuiles du WMS (ou du render de la map).

**Comment by Gaetanbrl** [comment]
Question posée sur le google group dev de Mapstore2 le 11/08/2021, sans réponse aujourd'hui

https://groups.google.com/g/mapstore-developers/c/7QcrqM43JzE

**Comment by Gaetanbrl** [comment]
Passage en VSR.

**Comment by Gaetanbrl** [comment]
@dcottenc le correctif est visible sur le contexte Tabou-VSR

**Comment by dcottenc** [comment]
Testée et validée pour les PA merci pour ta persévérance @Gaetanbrl .
