### ISSUE TITLE
V2 - Plugin - Ajout Aide en ligne

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#146]
## Description

Ajout Aide en ligne. Modalités à préciser (réunion sur ce sujet le 12/08)

**En tant qu'utilisateur**
**Je souhaite pourvoir accéder à l'aide en ligne à partir du plugin Tabou**
**Afin de pouvoir consulter la documentation du plugin**

## (Si) Règles spécifiques - Règles métiers

Ajout Aide en ligne. Modalités à préciser (réunion sur ce sujet le 12/08)

**Comment by Gaetanbrl** [comment]
Exemple : 
https://public.sig.rennesmetropole.fr/ressources/app/georchestra/Portail%20web%20guide%20rapide%20de%20prise%20en%20main.pdf

**Comment by dcottenc** [comment]
@Gaetanbrl Modification de l'US ce jour

**Comment by Gaetanbrl** [comment]
@dcottenc je viens de voir avec @Agath21 pour le bouton et notre proposition est disponible sur le contexte de VSR.

![146](https://user-images.githubusercontent.com/16317988/143424023-2b8f51a1-f665-4525-b81f-3efe89fa9386.gif)

Une configuration simple permet maintenant d'ajouter l'URL du document (si absent, alors le lien d'aide ne s'affiche pas dans l'UI Tabou) et l'URL de contact dans l'onglet Identifier (si les droits ne sont pas suffisants pour rappel).

Cette proposition vous convient ?

**Comment by dcottenc** [comment]
>@dcottenc je viens de voir avec @Agath21 pour le bouton et notre proposition est disponible sur le contexte de VSR.

Le fonctionnement est OK. Le positionnement m'interpelle car on perd une ligne d'affichage juste pour ce bouton.
Je vais solliciter la MOA pour validation.

**Comment by Gaetanbrl** [comment]
Selon les écrans, d'une manière ou d'une autre on perdra une ligne. Vu qu'il faut que ce soit accessible pour tous et en dehors des onglets, on a peu d'options je pense.

**Comment by Gaetanbrl** [comment]
Je complète : de base on a pas toutes les lignes @dcottenc

**Comment by dcottenc** [comment]
> on a peu d'options je pense.

Oui, je n'ai pas mieux à proposer.

**Comment by dcottenc** [comment]
Validé par la MOA
