### ISSUE TITLE
VSR front - Fiche OA / PA - Mauvais fonctionnement des champs dates

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#147]
**Niveau : Majeur**

**Description du bug**

Le fonctionnement est correct uniquement à la première saisie d'une date avec un champ initialement vide.
Ensuite, lors de la sélection d'une date, la valeur sélectionnée s'affiche finalement à J-1 mais les valeurs enregistrées en base sont bien à J. Lors des consultations suivantes, les champs date affichées sont J-1 des valeurs en base.

De plus : 

- si on supprime la valeur d'un champ : la valeur 01/01/1970 est mise par défaut
- les saisies directement dans le champ ne fonctionnent pas

**Reproduire l'anomalie**

1. Se connecter au contexte Tabou
2. Ouvrir le plugin Tabou
3. Cliquer sur une OA / PA qui est suivie dans Tabou (id_tabou non null)
4. Sélectionner une date à l'aide du calendrier pour une date dont la valeur est vide
6. La date affichée correspond à celle sélectionnée
7. Enregistrer la fiche
8. Les dates affichées et enregistrées sont conformes
9. Modifier cette date à l'aide du calendrier
10. **/!\ La date affichée est J-1**
11. Enregistrer la fiche
12. **/!\ La date Affichée est toujours à J-1** mais la date est enregistrée en base avec la bonne valeur J
13. Supprimer la valeur de la date
14. **/!\ La date affichée prend la valeur 01/01/1970**
15. Saisir directement la date au format 17/08/2021
16. **/!\ La date affichée est supprimée**

**Comportement attendu**

- [x] Lors de la sélection d'une valeur dans la calendrier, celle-ci doit être correctement affichée ;
- [x] La suppression de la valeur d'un champ date doit être possible (Enregistrement avec valeur Null)
- [x] La saisie manuelle de la date doit être possible directement dans le champ avec un message si la valeur n'a pas le bon format ou n'est pas conforme (Evolution).

**Environnement**

 - Environnement : RM Portail Test 
 - Version Front v1.0

**Comment by Gaetanbrl** [comment]
Corrections en cours.

- [ ]  Lors de la sélection d'une valeur dans la calendrier, celle-ci doit être correctement affichée ;
- [ ]  La suppression de la valeur d'un champ date doit être possible (Enregistrement avec valeur Null)

**Comment by Gaetanbrl** [comment]
> Lors de la sélection d'une valeur dans la calendrier, celle-ci doit être correctement affichée ;

Que se passe-t-il ?

La première fois qu'on récupère la valeur, la valeur de date ISO envoyée par le serveur est bien lue par les components ou librairies JS  et s'affiche bien dans le champ type Date de la fiche.

Ensuite, lors du clic on sauvegarde une valeur standardisée (ISO) qui est attendue par l'API.

* Clic sur le 12/08/2021
* Le component mapStore2 UTCDateTimePicker retourne `Thu Aug 12 2021 00:00:00 GMT+0200 (heure d’été d’Europe centrale)`
* On transforme au format ISO  pour avoir une valeur `2021-08-11T22:00:00.000Z`

La valeur ISO est calculée -1 jour par les librairie JS `moment` et native `Date`.

Le component `UTCDateTimePicker` semble modifier les dates en appliquant un décalage horaire. On va se passer de se composant car pour nos besoins nous n'avons qu'un fuseau horaire => l'heure Rennes Métropole.

**Comment by Gaetanbrl** [comment]
Après correction / tests nous avons  pour l'Ui suivantes :

![image](https://user-images.githubusercontent.com/16317988/129697097-d600ce05-42d3-4781-b4ca-0d6e1c6783f8.png)


Ces valeurs envoyées à l'API : 

```
clotureDate: "2021-08-19T09:01:44.943+0000"
livraisonDate: "2021-08-18T00:00:00.000+0000"
```

**Comment by Gaetanbrl** [comment]
> La saisie manuelle de la date doit être possible directement dans le champ avec un message si la valeur n'a pas le bon format ou n'est pas conforme (Evolution).

Non traité. Nouvelle issue si évolution.

**Comment by Gaetanbrl** [comment]
@dcottenc corrections testables sur le contexte de VA, en attente d'un retour.

**Comment by dcottenc** [comment]
>>La saisie manuelle de la date doit être possible directement dans le champ avec un message si la valeur n'a pas le bon format ou n'est pas conforme (Evolution).

>Non traité. Nouvelle issue si évolution souhaitée.

La saisie manuelle n'est pas une évolution. La demande d'afficher un message oui.

**Comment by dcottenc** [comment]
> [x] Lors de la sélection d'une valeur dans la calendrier, celle-ci doit être correctement affichée ;
> [x] La suppression de la valeur d'un champ date doit être possible (Enregistrement avec valeur Null)

Correction testée et validée. Merci.

Reste la saisie manuelle

**Comment by Gaetanbrl** [comment]
> La saisie manuelle n'est pas une évolution. La demande d'afficher un message oui.

ok ce n'était pas clair...

**Comment by Gaetanbrl** [comment]
Saisie libre dans un champ date  d'une fiche sur la branche develop. Testable sera déployé bientôt sur contexte de VA

**Comment by Gaetanbrl** [comment]
Saisie libre dans un champ date d'une fiche sur la branche develop. Testables ur contexte de VA @dcottenc

**Comment by dcottenc** [comment]
> Saisie libre dans un champ date d'une fiche sur la branche develop. Testables ur contexte de VA

Non corrigé (sous Firefox). La valeur disparait ou reprend la valeur avant saisie

**Comment by Gaetanbrl** [comment]
> Non corrigé (sous Firefox). La valeur disparait ou reprend la valeur avant saisie

Je ne vois plus le commentaire, c'est encore le cas ?

**Comment by dcottenc** [comment]
> Je ne vois plus le commentaire, c'est encore le cas ? (après vidage de cache)

Oui c'est Ok Merci
