### ISSUE TITLE
VSR - Fiche PA - Libelle infobulle impression fiche de suivi

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#149]
**Description du bug / Describe the bug**

Le libellé de l'infobulle sur le bouton qui permet de télécharger la fiche de suivi doit maintenant afficher : 
"Éditer la fiche de suivi"

**Comment by Gaetanbrl** [comment]
Traité, à déployer pour validation.

**Comment by dcottenc** [comment]
Testé et validé
