### ISSUE TITLE
[MAP] - Couches OA & SA - Accéder à la Fiche OA & SA

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#15]
## Description

**En tant que** DAUH,
**Je souhaite** Cliquer sur la carte
**Afin de** Visualiser les information sur une entité de la couche OA ou SA

## Règles

Des tests sont à prévoir dans le plugin `identifier` pour pouvoir faire un Hook et afficher le contenu comme prévu.

## (Si) Tests d'acceptance

1. Je clic sur la carte sur des entités OA ou SA
2. Je sélectionne la couche OA ou SA
3. Je peux voir la fiche OA et les informations qu'elle contient

**Comment by Gaetanbrl** [comment]
En accord avec le CCTP page 34 : 

`Des données attributaires supplémentaires pourront être ajoutées dans le cadre de la partie variable du marché. La solution doit anticiper ces évolutions (par exemple par l'ajout d'onglet).`

Nous souhaitons voir un ou plusieurs (si possibles) bloc d'attributs :

[Exemple en ligne](http://plnkr.co/edit/OxbVII?p=preview&preview).

**Comment by Gaetanbrl** [comment]
@dcottenc rendu actuellement en cours de réalisation  : 

![image](https://user-images.githubusercontent.com/16317988/105470624-127f8c80-5c9a-11eb-9829-94861771e4bc.png)

**Comment by dcottenc** [comment]
Comme nous l'avions évoquer cela répond à nos besoins.
L'intégration avec le respect de l'ergonomie MapStore est très réussi
