### ISSUE TITLE
VSR - Fiche de suivi - appliqué un nom standard

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#151]
**Description **

Le nom de la fiche de suivi téléchargée doit correspondre à ce format : 

`
FicheSuivi_IDTabou_codexxx_NomOperation.pdf
`

**Comment by Gaetanbrl** [comment]
Visible dans le contexte VA.

**Comment by dcottenc** [comment]
FicheSuivi-452_2021-6028_BaudChardonnet.pdf

Il reste encore le premier tiret à remplacer par un "_"

**Comment by Gaetanbrl** [comment]
corrigé et Testé ce jour @dcottenc je ferme le ticket.

Voici le nom de fichier retourné :

[FicheSuivi_560_2021-60392_BaudChardonnet.pdf](https://github.com/sigrennesmetropole/geor_tabou2_front/files/7014868/FicheSuivi_560_2021-60392_BaudChardonnet.pdf)
