### ISSUE TITLE
Evo - Voir sur la carte les programmes d'une OA / SA

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#152]
## Description

**En tant que** MOA
**Je souhaite** pouvoir cliquer sur un programme listé dans la fiche d'une OA ou SA
**Afin de** mieux localiser un programme et le différencier des autres entités visibles sur la carte

## (Si) Tests d'acceptabilité

1. Ouvrir le plugin Tabou2
2. Cliquer sur une entité OA ou SA
3. Dans la fiche de l'entité, ouvrir le volet "Liste des programmes"
4. Cliquer sur un programme
5. La carte doit se positionner sur l'étendue du programme cliqué
6. L'utilisateur doit également pouvoir retourner sur l'étendue du OA ou SA de la fiche

## Compléments / screenshot
![image](https://user-images.githubusercontent.com/16317988/129896324-7c166608-d35c-47ef-bbab-a9711f3c6831.png)

**Comment by dcottenc** [comment]
@Gaetanbrl  Doublon avec 139 finalement ?

**Comment by Gaetanbrl** [comment]
En effet, mais la 139 est trop gosse, en affinant on se perd moins.

**Comment by dcottenc** [comment]
Elle n'est pas grosse !! Seulement un peu enveloppée !
(Désolé, petit moment de craquage avec mes référence littéraires très basiques ;) )

**Comment by dcottenc** [comment]
Fonctionnalité non incluse dans ce marché
