### ISSUE TITLE
Evo - mettre en évidence l'entité cliquée sur la carte

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#153]
## Description

**En tant que** chargé d'opération
**Je souhaite** pouvoir cliquer sur un bouton de la fiche info d'une OA, PA ou SA
**Afin de** mettre en évidence l'entité géographique qui correspond à la fiche en consultation

## (Si) Tests d'acceptabilité

1. Ouvrir Tabou2
2. Cliquer sur une PA ou une SA ou une OA
3. L'entité Tabou est visible sur la carte également par une symbologie spécifique (en plus du marqueur initial MapStore2)
4. Si une seconde entité est capturée par le clic, changer d'entité via la liste disponible

![image](https://user-images.githubusercontent.com/16317988/129885220-885b6497-b051-410a-8020-f342fbd90c87.png)

5. L'entité sélectionnée devient l'entité mise en évidence sur la carte
6. Quitter la fiche info et voir qu'il n'y a plus d'entité mise en évidence sur la carte
7. Quitter le plugin et voir qu'il n'y a plus d'entité mise en évidence sur la carte

## Complément (graphique, capture, schéma, etc.)

La fonctionnalité décrite ici est reprise du fonctionnement de la mise en évidence du volet d'interrogation au clic.

![image](https://user-images.githubusercontent.com/16317988/129885403-55cc3a45-0af3-4955-bb16-12ad0473ee9c.png)

**Comment by dcottenc** [comment]
@Gaetanbrl Pour reprendre un peu la description de ce sujet.

Lorsque l'onglet Identifier est ouvert (avec au moins une entité), alors on affiche les données d'une entité et celle ci doit être mise en surbrillance. Si l'utilisateur sélectionne une autre entité ou un autre type alors l'entité en surbrillance change aussi (comme les données). 
C'est également le cas lorsque l'entité sélectionnée n'a pas d'id_tabou (affichage du message Ajout). La surbrillance est conservée même quand on bascule dans l'onglet Ajout (emprise sélectionnée)

Dans les autres cas, onglet Recherche, onglet Ajout (sans emprise sélectionnée) et onglet Identifier (sans entité au niveau du clic utilisateur), il n'y a pas d'entité en surbrillance.

**Comment by dcottenc** [comment]
Ok pour lancer les devs sur ce ticket

**Comment by Gaetanbrl** [comment]
Suite aux débuts des développements, voici un aperçu du fonctionnement non finalisé  @dcottenc : 

![153_v1](https://user-images.githubusercontent.com/16317988/146176357-43c36e57-6bb3-4601-abc9-cdd5000ee9b9.gif)


Ces développements incluent une refont des éléments suivants à partir du modèle Cadastrapp : 

* Création d'un système Tabou de click + appel WMS (retour GeoJSON)
* Système de lecture d'une réponse JSON depuis le geoserver
* Chargement des informations depuis le click ou l'appel Tabou
* Création de couches additionnelles pour afficher une géométrie (depuis n'importe quelle source)
* Utilisation des couches additionnelles pour zoomer sur une emprise
* Gestion du GetFeatureInfo natif (ne pas l'utiliser si Tabou est ouvert / l'utiliser quand Tabou est fermé) comme Cadastrapp

**Comment by Gaetanbrl** [comment]
@dcottenc voici le rendu final plus fluide que la v1 lors du clic (on ne voit plus le volet de recherche natif).

![153_end](https://user-images.githubusercontent.com/16317988/147946374-4226e789-640f-452c-9450-439f1192c6c7.gif)


Voici la config liée aux styles des features et pour afficher ou non l'icône du click : 

```
          "styles": {
            "showClick": true,
            "selection": {
              "fillColor": "red",
              "fillOpacity": 0.5,
              "opacity": 1,
              "color": "yellow",
              "weight": 2
            },
            "default": {
              "fillColor": "#6f718e",
              "fillOpacity": 0,
              "opacity": 0.8,
              "color": "yellow",
              "weight": 2,
              "dashArray": [5, 5]
            }
          }
```

**Comment by Gaetanbrl** [comment]
En attente de déploiement (contexte de test) + test

**Comment by Gaetanbrl** [comment]
Feature Déployée  - en attente de validation

**Comment by dcottenc** [comment]
Testée et validée techniquement. Très beau travail. Merci

En attente, validation métier

**Comment by dcottenc** [comment]
Validée par la MOA
