### ISSUE TITLE
VSR - Fiche OA/PA / Journal de bord - Gestion enregistrement

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#154]
**Niveau : Majeur**

**Description du bug**

L'ergonomie de l'enregistrement d'un événement présente une anomalie et il ne s'exécute pas.

**Reproduire le bug**

1. Ouvrir le plugin Tabou
2. Cliquer sur une OA ou PA suivie dans Tabou (id_tabou non null)
3. L'onglet "Identifier" s'ouvre et affiche les informations de l'entité
4. Cliquer sur le bouton Journal de bord
5. Cliquer sur le bouton Ajouter
6. Saisir un type et un libellé de l'événement
=> lorsqu'on place le curseur au dessus du bouton Valider, un sens interdit est présent (non bloquant). Pour le faire disparaitre il faut cliquer sur type
8. Cliquer sur le bouton enregistrer
=> la ligne en cours disparait et n'est pas ajoutée en base

**Comportement attendu**

A partir de l'étape 6, 
7. Cliquer sur le bouton Enregistrer
=> l'événement est enregistré en base et passe en mode consultation dans la liste 

**Informations complémentaires**
L'API fonctionne correctement. Par contre, le JSON associé me semble incorrect.
Via la console, on obtient : 
La requête appelée `https://portail-test.sig.rennesmetropole.fr/tabou2/programmes/552/evenements`
Le JSON associé : 
```
{
  "description":"eee",
  "eventDate":"2021-04-21T14:39:54.176Z",
  "id":0,
  "idType":3,
  "new":true,
  "typeEvenement":
     {
        "id":1,
        "libelle":"Reunion",
        "dateInactif":null,
        "code":"REUNION",
        "systeme":false
     }
}
```

**Environnement**

Environnement : RM Portail Test
Version Front v1.0
API : v1.1.5

**Comment by Gaetanbrl** [comment]
> L'API fonctionne correctement. Par contre, le JSON associé me semble incorrect.

Peux-tu préciser ce qui te semble incorrect @dcottenc dans le JSON stp ?

**Comment by Gaetanbrl** [comment]
> Saisir un type et un libellé de l'événement
>=> lorsqu'on place le curseur au dessus du bouton Valider, un sens interdit est présent (non bloquant). 
> Pour le faire disparaitre il faut cliquer sur type

En effet, la validation s'exécute quand le champ "Note" n'est plus "focus", donc désélectionne.

> Cliquer sur le bouton enregistrer
> => la ligne en cours disparait et n'est pas ajoutée en base

Lorsqu'on reclique sur l'entité OA (PA ou SA), et qu'on revient dans les événements on retrouve bien l'événement rajouté.

Je pense qu'il y a un soucis au refresh de la liste...

**Comment by dcottenc** [comment]
> Peux-tu préciser ce qui te semble incorrect @dcottenc dans le JSON stp ?

L'API accepte le JSon tel quel mais ;
- "id":0 : n'est pas utile (ID non connu)
- "idType":3, et "new":true, ne font pas partis des arguments de l'API
- il manque l'argument Est Système (mais mis à défaut par False)

**Comment by Gaetanbrl** [comment]
> il manque l'argument Est Système (mais mis à défaut par False)

Ce n'est pas la propriété "système" dans le JSON ?

**Comment by dcottenc** [comment]
> Je pense qu'il y a un soucis au refresh de la liste...

Je confirme. J'avais bien testé en fermant la modale mais pas en rechargeant la fiche

**Comment by dcottenc** [comment]
> Ce n'est pas la propriété "systeme" dans le JSON ?

Oui désolé, c'est bien systeme

**Comment by Gaetanbrl** [comment]
> "id":0 : n'est pas utile (ID non connu)
> "idType":3, et "new":true, ne font pas partis des arguments de l'API

Ce sont des infos que j'utilise, je peux les enlever à l'envoi.

**Comment by dcottenc** [comment]
> Ce sont des infos que j'utilise, je peux les enlever à l'envoi.

Cela ne semble pas gêner l'API mais on ne sait jamais

**Comment by Gaetanbrl** [comment]
- [ ] Saisir un type et un libellé de l'événement et pouvoir valider sans cliquer en dehors de la comobox
- [ ] Cliquer sur "Enregistrer" => la ligne en cours disparaît et revient avec la récupération des données de l'API (refresh)

Plugin en cours de déploiement  et visible à terme.

**Comment by Gaetanbrl** [comment]
A valider @dcottenc merci

**Comment by dcottenc** [comment]
Corrections testées et validées; Merci
