### ISSUE TITLE
VSR - Fiche OA/PA / Journal de bord - Modification Note

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#155]
**Niveau : Mineur**

**Description du bug**

Lors de la modification d'une note dans le journal de bord, la valeur actuelle apparait en grisé mais n'est pas modifiable par l'utilisateur

**Reproduire le bug**

1. Ouvrir le plugin Tabou
2. Cliquer sur une OA ou PA suivie dans Tabou (id_tabou non null)
3. L'onglet "Identifier" s'ouvre et affiche les informations de l'entité
4. Cliquer sur le bouton Journal de bord
5. Cliquer sur le bouton Modifier pour une Note (non système)
=> impossible de modifier le libellé de la note, le contenu disparait lors du clic

**Comportement attendu**

A partir de l'étape 5, 
6. Modifier le libellé de la note
=> l'événement est enregistré en base et passe en mode consultation dans la liste 

**Environnement**

Environnement : RM Portail Test
Version Front v1.1
API : v1.1.5

**Comment by Gaetanbrl** [comment]
A valider @dcottenc merci

**Comment by Gaetanbrl** [comment]
A valider @dcottenc merci

**Comment by dcottenc** [comment]
Correction testée et validée. Merci
