### ISSUE TITLE
VSR - Evolution - Fiche OA/PA / Journal de bord - Affichage liste des événements

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#156]
## Description

**En tant que** chargé d'opération
**Je souhaite** consulter la liste des événements triée par date événement croissant
**Afin de** visualiser toutes les informations de chaque événement

## (Si) Tests d'acceptabilité

1. Ouvrir Tabou2
2. Cliquer sur une PA ou une SA ou une OA
3. Cliquer sur le bouton Journal de bord
4. La liste des événements doit comporter pour chaque ligne :
- Est système ou pas
- Date de l'évènement;
- Type événement
- Description "Note" /!\ Actuellement ce champ s'étend horizontalement selon son contenu => un champ assez grand avec un ascenseur vertical est demandé si besoin
- Date et User Modif ex : "m.basle 18/08/2021 16:16"

## Complément (graphique, capture, schéma, etc.)

Illustration extension champ Note

![image](https://user-images.githubusercontent.com/76009802/129914125-65ed3a9e-1ddf-4448-b4b8-c5e40fd430c9.png)

**Comment by Gaetanbrl** [comment]
Ajouter une checkbox non modifiable pour les éléments `Est système`.

**Comment by Gaetanbrl** [comment]
Est-ce bien le rendu souhaité @dcottenc ?

![image](https://user-images.githubusercontent.com/16317988/130468170-f92031d3-afc6-4500-939b-8932c624a966.png)

**Comment by dcottenc** [comment]
> Est-ce bien le rendu souhaité @dcottenc ?

La colonne Auteur est à supprimer car en doublon avec celle de dernière modification (à mettre à la fin). Merci

**Comment by Gaetanbrl** [comment]
> La colonne Auteur est à supprimer car en doublon

Si l'auteur n'est pas le dernier à avoir modifié ? On affiche pas l'auteur ?
(on avait déjà vu ce point ensemble il me semble)

**Comment by Gaetanbrl** [comment]
@dcottenc visible en l'état sur le contexte de VA. En attente d'une validation + clôture si valide.

**Comment by dcottenc** [comment]
Juste une remarque ; pour moi le oui/non à coté de la case à cocher ne se justifie pas car il fait doublon avec la case. Si ce n'est pas une correction très simple, on peut valider sans.

**Comment by Gaetanbrl** [comment]
> la case à cocher ne se justifie pas car il fait doublon avec la case

C'était pour être certain que les utilisateurs comprennent, étant donné qu'ils sont souvent en questionnement sur les interfaces... Je vais enlever le oui / non.

**Comment by dcottenc** [comment]
> C'était pour être certain que les utilisateurs comprennent,

Tu as raison mais comme tu l'as déjà indiqué, et je partage ton avis, il va falloir les former plutôt que de surcharger inutilement les IHM

**Comment by Gaetanbrl** [comment]
Correctif dispo sur le contexte VA.

**Comment by dcottenc** [comment]
Correction testée et validée
