### ISSUE TITLE
VSR - Evolution - Fiche OA/PA / Journal de bord - Modification des événements

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#157]
## Description

**En tant que** chargé d'opération
**Je souhaite** pouvoir éditer les événements non système
**Afin de** modifier les champs autorisés 

## (Rg) Règles de Gestion

Seuls les événements "non système" (systeme =false) sont modifiables. Les événements "système" sont en lecture seule.

## (Si) Tests d'acceptabilité

1. Ouvrir Tabou2
2. Cliquer sur une PA ou une SA ou une OA
3. Cliquer sur le bouton Journal de bord
4. Cliquer le bouton d'ajout ou modification d'un événement
5. Les champs suivants (et uniquement ceux là) deviennent modifiables :
- Date de l'évènement (calendar ?) ;
- Type événement (listé déroulante) ;
- Description "Note".
6. Cliquer sur Enregistrer
=> l'événement ajouté ou modifié est enregistré en base et l'affichage de la liste est actualisée

**Comment by Gaetanbrl** [comment]
VSR ou évolution ? @Gaetanbrl Idem #156

**Comment by dcottenc** [comment]
L'écran Evènement n'était pas finalisé pour la v1. En tout cas, il ne répond pas complétement au besoin.
L'absence de la date événement aurait du être signalée bien plus tôt d'où "Evolution". Et VSR car identifié en VSR. Peu importe pour moi.

**Comment by dcottenc** [comment]
Testé mais des anomalies
- lorsqu'on clique sur modifier le type disparait :
Avant clic sur Modifier
![image](https://user-images.githubusercontent.com/76009802/174028902-c2fd3e24-59a5-4c29-b8bb-9edaf069d0ab.png)
Après clic sur Modifier
![image](https://user-images.githubusercontent.com/76009802/174029107-38cb224f-e8b1-4d65-984b-c7be49361720.png)

- lorsqu'on enregistre les modifications, l'affichage ne s'actualise pas et reste en saisie

@Gaetanbrl preferes-tu que j'ajoute des tickets pour les anos ?

**Comment by Gaetanbrl** [comment]
> preferes-tu que j'ajoute des tickets pour les anos ?

oui on distingue les specs des anomalies si possible.

**Comment by Gaetanbrl** [comment]
le but étant de fermer les milestones précédents aussi @dcottenc

**Comment by dcottenc** [comment]
Ok, je traite par Milestone et je créé des ano dans la VA. Merci

**Comment by dcottenc** [comment]
Testé, deux anos identifiées en VA.

US close
