### ISSUE TITLE
API - Modifier un événement - PUT Request

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#158]
# Description du bug

L'API pour modifier un événement ne semble pas reconnaître l'ID type.

**Voici le JSON à utiliser dans l'API :** 

ID Operation 105

https://portail-test.sig.rennesmetropole.fr/tabou2/operations/105/evenements

```
{
    "eventDate": "2021-08-19T09:05:00.246+0000",
    "description": "Reprise test GB2",
    "systeme": false,
    "createUser": "gbruel",
    "createDate": "2021-08-19T09:05:08.028+0000",
    "modifUser": "gbruel",
    "modifDate": "2021-08-19T09:05:08.028+0000",
    "typeEvenement": {
        "id": 6,
        "libelle": "Reprise données",
        "dateInactif": null,
        "code": "REPRISE",
        "systeme": false
    }
}
```

**Est-ce que le corps est bon ?**

J'ai comparé avec le corps mis en exemple dans le Swagger, on a le même. J'ai l'impression que l'ID Type envoyé n'est pas reconnu.

# Reproduction

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur le Swagger de l'API
2. Ouvrir l'API operation/{operationId}/evenements
3. Renseignez le JSON fourni au dessus
4. Saisir l'ID Tabou Opération 105

**Comportement attendu / Exptected behavior**

La modification est acceptée.

# Erreur API

```
Erreur 422
can't parse JSON.  Raw result:
updateEvenementByOperationId.arg1.id: L'identifiant de l'évenement est invalide
```

Côté Navigateur : 

```
Request URL: http://localhost:8081/tabou2/operations/105/evenements
Request Method: PUT
Status Code: 422 Unprocessable Entity
```

# Informations complémentaires

l'ID type événement est valide : 

https://portail-test.sig.rennesmetropole.fr/tabou2/types-evenements?asc=true

```
    {
      "id": 6,
      "libelle": "Reprise données",
      "dateInactif": null,
      "code": "REPRISE",
      "systeme": false
    }
```

**Comment by dcottenc** [comment]
Il manque l'ID de l'événement à modifier dans le JSON proposé.
Le JSON corrigé ci-dessous a fonctionné
```
{    
    "id":355,
    "eventDate": "2021-08-19T09:05:00.246+0000",
    "description": "Reprise test GB2",
    "systeme": false,
    "createUser": "gbruel",
    "createDate": "2021-08-19T09:05:08.028+0000",
    "modifUser": "gbruel",
    "modifDate": "2021-08-19T09:05:08.028+0000",
    "typeEvenement": {
        "id": 6,
        "libelle": "Reprise données",
        "dateInactif": null,
        "code": "REPRISE",
        "systeme": false
    }
}
```

**Comment by Gaetanbrl** [comment]
Validé, merci @dcottenc
