### ISSUE TITLE
VSR - Fiche OA/PA / Journal de bord - Modification Note systeme

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#159]
**Niveau : Mineur**

**Description du bug**

Les événements système ne sont pas modifiables. Le bouton supprimer est bien absent pour ce type de ligne mais le bouton Modifier est présent.

**Reproduire le bug**

1. Ouvrir le plugin Tabou
2. Cliquer sur une OA ou PA suivie dans Tabou (id_tabou non null)
3. L'onglet "Identifier" s'ouvre et affiche les informations de l'entité
4. Cliquer sur le bouton Journal de bord
=> bouton Modifier présent pour une Note système

**Comportement attendu**

A partir de l'étape 4, 
=> les boutons Supprimer et Modifier ne sont pas présents sur la ligne

**Environnement**

Environnement : RM Portail Test
Version Front v1.1
API : v1.1.5

**Comment by Gaetanbrl** [comment]
@dcottenc à valider sur contexte VA.

**Comment by dcottenc** [comment]
Correction testée et validée
