### ISSUE TITLE
Mail de contact - utilisateur consultation uniquement

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#160]
## Description

**En tant que** utilisateur,
**Je souhaite** pouvoir voir un contact quand je ne peux pas accéder à l'ajout d'une entité,
**Afin de** pouvoir demander les droits ou faire une demande de modification.

## (Si) Règles spécifiques - Règles métiers

L'objectif est de pouvoir cliquer sur un mail type mailto.
L'email renseigner doit pouvoir être configurable dans le plugin.

## (Si) Tests d'acceptabilité

1. Se logger en tant qu'utilisateur non réferent et non contributeur
2. Cliquer sur une entité Tabou non suivie => Rechercher "lentille" par exemple

![image](https://user-images.githubusercontent.com/16317988/130213155-a22bff2e-f1f0-4fb8-a69d-ef40d71954e5.png)

3. Voir le message et le bouton d'envoi de mail

![image](https://user-images.githubusercontent.com/16317988/130213295-9b7cc801-1300-4e4f-8c58-14f7c22b9dd5.png)

4. Cliquer sur le bouton d'envoi du mail pour ouvrir le dialogue d'envoi d'un email

**Comment by Gaetanbrl** [comment]
@dcottenc testable sur context VA.

J'ai également rajouté un lien pour copier l'adresse mail, dans le cas où on ne souhaite pas utiliser la boîte mail de l'ordinateur mais une boîte dans un navigateur.

Ca convient ?

![image](https://user-images.githubusercontent.com/16317988/130215428-21af9d51-ddcc-4d4a-b835-bed8c1766c21.png)

**Comment by dcottenc** [comment]
@Gaetanbrl Le bouton répond à la demande 
Par contre, le lien pour copier l'email ne doit pas correspondre à ce que tu avais prévu avec Firefox

**Comment by Gaetanbrl** [comment]
Quel est le comportement que tu as ?

Je viens de tester sur Chrome et FF, sur les deux ca correspond à mon cas d'usage :

* Cliquer sur le lien
* L'adresse mail est alors en copie dans le presse papier
* Coller directement dans la zone de texte voulu (ex: dans une page web comme Outlook version web)

![copymail](https://user-images.githubusercontent.com/16317988/130228516-6a577eb7-983f-4b9c-b8dc-9355da3fddf2.gif)


Dans mon cas, le mailto ouvre le logiciel de gestion des mails de mon système, qui n'est pas Outlook par défaut.
Si je copie le mail ca me permet de le coller directement en tant que destinataire dans mon Outlook.

Je trouve ca plutôt pratique.

**Comment by dcottenc** [comment]
A mon avis cela va dérouter les utilisateurs et ils ne vont pas réussir à s'en servir. Après, je cautionne l'intérêt de cette fonctionnalité.
"Copier l'email" apparait comme un lien hypertexte avec un curseur de saisie que l'on se trouve dessus. Au clic, rien ne se passe mais effectivement le mail est copié.

**Comment by Gaetanbrl** [comment]
> A mon avis cela va dérouter les utilisateurs

Bien vu ! 

Du coup j'ai apporté ces modifications (visibles sur contexte VA) :
* Au survol : affichage du pointeur avec la main + affichage d'une tooltip
* Au clic : affichage d'une notification en haut à droite

Si ca ne convient toujours pas je désactiverai cette fonctionnalité.

![copymail](https://user-images.githubusercontent.com/16317988/130243487-dab966f9-8e72-421d-9095-0f786e00bbb7.gif)

**Comment by dcottenc** [comment]
A mon avis, la prochaine étape c'est que tu fasses un clic automatique à la place de l'utilisateur quand il pense à vouloir copier l'email ! :p 

C'est parfait. Je valide
