### ISSUE TITLE
Evo - Filtrer par famille de zone PLUI

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#162]
## Description

**En tant que** utilisateur,
**Je souhaite** pouvoir filtrer les couches OA, PA, SA par famille de zone PLUI (par type)
**Afin de** pouvoir voir toutes les entités selon le type filtré.

## (Si) Règles spécifiques - Règles métiers

La couche PLUI contient deux champ : libellé et type_zone.
C'est le champ "type_zone" qui est à utiliser et qui devra être exposé par l'API.
L'API devra également permettre une autocomplétions si le nombre de famille est trop grand.

Si l'autocomplétions est utilisée, elle devra démarrer à partir de 1 caractère saisi.

Voici le tableau détaillé des zones et secteurs : 

![image](https://user-images.githubusercontent.com/16317988/130455896-c7416994-deda-42ab-bb4d-d5c788c354d3.png)

## (Si) Tests d'acceptabilité

1. Se rendre sur le contexte Tabou2
2. Ouvrir le plugin
3. Choisir l'onglet "filtrer"
4. Dans le filtre "Type PLUI", choisir "UA1"
5. Attendre la fin du chargement
6. Valider la recherche
7. Voir que la carte ne contient que les entité OA / PA / SA qui intersectent une zone PLUI du type "UA1"

**Comment by Gaetanbrl** [comment]
liée à #115 (idem ?)

**Comment by dcottenc** [comment]
Le filtre est opérationnel (il a suffit de changer les paramètres de celui-ci).

Testé et validé en PF de test et en prod
