### ISSUE TITLE
Evo - Afficher la fiche d'un programme depuis la liste des programmes

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#163]
## Description

**En tant que** utilisateur,
**Je souhaite** voir un bouton pour chaque programme de la liste des programmes d'une OA, SA
**Afin de** pouvoir accéder directement à la fiche d'un programme sans cliquer sur le programme.

## Règles spécifiques

- Lors du chargement forcé d'une fiche, aucune autre fiche ne pourra être visible. Seul la fiche du programme cliqué sera visible. Dans la liste des couche de la fiche, seul `Programme` sera inséré.
- Pour revenir à la sélection précédente avant le clic, il faudra re cliquer sur la carte pour reproduire la sélection.

## (Si) Tests d'acceptabilité

1. Ouvrir le plugin Tabou2
2. Cliquer sur une OA
3. Ouvrir le bloc "Liste des programmes"
4. identifier un programme dans la liste
5. Cliquer sur le programme
6. Voir que la carte se positionne sur l'emprise du programme
7. Au dessus de la liste, cliquer sur un bouton avec une tooltip affichant `Voir la fiche du programme`
8. Voir que la fiche information a chargé les informations du programme

**Comment by Gaetanbrl** [comment]
Cette issue est à valider par @dcottenc

**Comment by dcottenc** [comment]
> Cette issue est à valider par @dcottenc

A mon sens, il est souhaitable de reprendre l'ergonomie de la table des attributs avec la fonctionnalité identique (symbole du bouton, placement en début de ligne...). Es-tu d'accord ?

![image](https://user-images.githubusercontent.com/76009802/130638033-8fc91952-92ea-491e-89ed-5d0be9697801.png)

**Comment by Gaetanbrl** [comment]
Je propose de reprendre ce bouton pour le zoom sur l'emprise.
Il faut voir combien de boutons on peut mettre pour avoir un bouton "ouvrir la fiche".

**Comment by dcottenc** [comment]
>Il faut voir combien de boutons on peut mettre pour avoir un bouton "ouvrir la fiche"

Je n'ai pas compris ce dernier point.

**Comment by Gaetanbrl** [comment]
Sur ta capture il n' a qu'un seul bouton à gauche. ce serait bien d'avoir un bouton "Zoom sur l'emprise" et un autre "Ouvrir la fiche".

Mais il faut voir combien de bouton on peut rajouter si ce n'est pas juste une colonne.

**Comment by dcottenc** [comment]
>  ce serait bien d'avoir un bouton "Zoom sur l'emprise" et un autre "Ouvrir la fiche".

Je n'avais pas compris ton US comme ca. La solution d'avoir deux boutons est souple pour l'utilisateur mais peut également devenir pénible.
Lors de nos discussions, nous pensions à un clic sur le programme qui permet de centre la carte sur celui-ci et d'afficher sa fiche de données attributaires. Un seul clic pour deux actions. Le débat était sur la pertinence de la 2eme.

**Comment by Gaetanbrl** [comment]
> Un seul clic pour deux actions. Le débat était sur la pertinence de la 2eme.

J'avais également mis en garde que l'utilisateur pouvait se tromper sur l'emprise PA. Par exemple il souhaite une emprise X et clique sur le nom d'une emprise Y, si la fiche s'ouvre, il doit recliquer sur l'emprise X sur la carte. Ce qui ne rend pas optimal le workflow à mon sens et rajoute des clics.

 Si on ne fait que le zoom, il clique sur la PA dans la liste, on zoom dessus et si c'est celle qu'il souhaite alors on ouvre la fiche.
Avoir deux interaction permet de directement ouvrir la fiche ou de simplement faire un zoom dessus.

Dans le cas de deux clics, je me pose la question de l'intérêt du zoom sur une emprise PA. Car en ouvrant une fiche on a prévu de mettre en évidence l'emprise cliquée...

**Comment by dcottenc** [comment]
Ce sujet a été évoqué avec la MOA ce matin, mais elle n'est pas dans la capacité de statuer cette semaine.
Une consultation est mise en place pour obtenir une validation du besoin en milieu de semaine prochaine.

**Comment by dcottenc** [comment]
Fonctionnalité non incluse dans ce marché
