### ISSUE TITLE
VSR front - Fiche PA - Modification mapping champs DDC

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#165]
**Niveau : Mineur**

**Description du bug**

Les champs Date du bloc DDC de la fiche PA ne sont pas mappés sur les bons champs. La description du mapping dans le ticket #69 est fausse.

**Comportement attendu**

Dans le bloc DDC le mapping des champs Date est corrigé (en gras).
La correction du mapping est à corriger pour l'affichage et la modification de ces champs.

**Bloc Instruction Droit des Sols**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Date ADS | Date | Calendar |  |  | /programmes/{programmeId} | **adsDatePrevu** |
| Date DOC | Date | Calendar |  |  | /programmes/{programmeId} | **docDatePrevu** |
| Date DAACT | Date | Calendar |  |  | /programmes/{programmeId} | **datDatePrevu** |
| Détail ADS | Liste | Tableau | X |  | /programmes/{programmeId}/permis | (cf. WS) |

**Environnement**

Environnement : RM Portail Test
Version Front VSR

**Comment by Gaetanbrl** [comment]
@dcottenc est-ce que je peux avoir un exemple pour les tests où ces valeurs sont non nulles ?

**Comment by dcottenc** [comment]
@Gaetanbrl regarde les programmes E1 ou D1 de Baud Chardonnet, l'un des deux présente des dates renseignées

**Comment by Gaetanbrl** [comment]
Ni l'un ni l'autre n'ont ces 3 champs de saisis.

* D1
https://portail-test.sig.rennesmetropole.fr/tabou2/programmes/541

* E1
https://portail-test.sig.rennesmetropole.fr/tabou2/programmes/529

J'ai mis à jour le plugin, je te laisse revenir vers moi si tu constates une erreur.

**Comment by dcottenc** [comment]
@Gaetanbrl La correction est testée et validée 
Le programme id 529 n'affiche plus les valeurs des dates de DDC mais celle prévu (à Null) dans l'exemple.
Ce n'est pas normal que l'API DDC ne retourne rien, un ticket est ouvert pour cela
`{
  "id": 529,
  "etape": {
    "id": 6,
    "libelle": "En chantier",
    "code": "EN_CHANTIER_PUBLIC",
    "type": "NORMAL",
    "mode": "PUBLIC"
  },
  "operationId": 105,
  "diffusionRestreinte": false,
  "code": "2021-6031",
  "nom": "E1",
  "programme": "1",
  "description": "Programme sur socle de parking commun, composé de quatre bâtiments de formes urbaines variées (Maisons de ville et collectifs) R+2 à R+10",
  "idEmprise": null,
  "attributionFonciereAnnee": 2019,
  "attributionDate": "2019-03-25T09:37:58.818+0000",
  "commercialisationDate": null,
  "adsDate": "2020-09-15T22:00:00.000+0000",
  "livraisonDate": "2023-05-31T22:00:00.000+0000",
  "docDate": "2021-06-13T22:00:00.000+0000",
  "datDate": null,
  "adsDatePrevu": null,
  "docDatePrevu": null,
  "datDatePrevu": null,`
