### ISSUE TITLE
VSR front - Ajout / Modification OA/SA - Pas de rafraichissement de la carte

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#166]
**Niveau : Mineur**

**Description du bug**

De la même manière que les PA;  il manque le rafraichissement de la carto pour les OA et SA. La couleur du polygone ne se met à jour que si l'on change le zoom et reste inchangée dans le niveau de zoom utilisé lors de la création ou de la modification 
Voir ticket #145 

**Reproduire l'anomalie**

Cas ajout :
1. Se connecter au contexte Tabou
2. Ouvrir le plugin Tabou
3. Cliquer sur une OA non suivie (id_tabou null)
4. Cliquer sur ajouter et remplir les champs nécessaires à l'ajout
5. Enregistrer => l'emprise de l'opération reste avec la symbologie "Non suivi"
6. Modifier le niveau de zoom de la carte => l'emprise est mise à jour

Cas Modification : 
1. Se connecter au contexte Tabou
2. Ouvrir le plugin Tabou
3. Cliquer sur une OA suivie (id_tabou non null)
4. Modifier l'étape de l'opération
5. Enregistrer => l'emprise de l'opération reste avec la symbologie de l'étape précédente
6. Modifier le niveau de zoom de la carte => l'emprise est mise à jour

**Comportement attendu**

Lors de l'enregistrement d'une OA, l'actualisation de l'affichage de la couche opération est à réaliser. L'utilisateur peut ainsi identifier que cette entité est suivi.
A noter que dans ce cas la couche secteur doit également être actualisée même si pour l'instant la symbologie n'est pas liée à un attribut du secteur mais cela va changer prochainement.

**Environnement**

 - Environnement : RM Portail Test 
 - Version Front VSR
 - API v1.1.5

**Comment by Gaetanbrl** [comment]
Vu avec Denis. A clôturer, fonctionne comme prévu.
