### ISSUE TITLE
VSR front - Liste des tiers - Lignes de la liste non renseignées

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#167]
**Niveau : Majeur**

**Description du bug**

Les champs de la liste des tiers d'une OA ou d'un PA sont vides.
On n'est contraint de cliquer au hasard sur toutes les lignes pour trouver le tiers que l'on souhaite modifier ou supprimer

**Reproduire l'anomalie**

1. Se connecter au contexte Tabou
2. Ouvrir le plugin Tabou
3. Cliquer sur une OA (ex : id 105) ou un PA (ex : id 529)
4. Vérifier qu'il existe des tiers pour l'entité sélectionnée (oui dans les exemples données ci-dessus)
5. Ouvrir la fenêtre de gestion des tiers
6. La liste apparait avec le bon nombre de lignes mais qui ne sont pas renseignées

Le comportement est similaire si on associe un tiers à l'entité

**Capture d'écran**
![image](https://user-images.githubusercontent.com/76009802/135037875-e83bb2a5-4da2-4e1a-ae8a-62573cd683a7.png)

**Comportement attendu**

La liste des tiers permet d'afficher les attributs des tiers associés à l'entité.

**Environnement**

 - Environnement : RM Portail Test 
 - Version Front VSR
 - API v1.1.5

**Comment by Gaetanbrl** [comment]
Les tiers et affichages ne sont-ils pas englobés dans les évolutions à venir ?
Il me semblait que l'appel des infos de tiers n'était pas "fonctionnel" en raison de certaines infos manquantes (pour liv. v1).

Je peux toujours regarder cela dit.

**Comment by dcottenc** [comment]
Oui il est bien prévu de faire évoluer la gestion des tiers. Je ne pense pas que l'API consultation était indisponible  (je ne me rappelle plus). 
Cette ano est à traiter dans la VSR uniquement si cela concerne un soucis simple (mapping de champs par exemple) et non l'implémentation d'une API qui n'était pas dispo.

**Comment by Gaetanbrl** [comment]
Suite aux modifications portées dans l'API sur le schema des tiers retournés (propriétés `tiers.tiers` et` tiers.typeTiers`), l'ensemble des informations doivent être reprises pour un affichage correspondant.

![image](https://user-images.githubusercontent.com/16317988/136796967-cf08f06e-5aa8-46a9-89ad-1877576d868c.png)

**Comment by dcottenc** [comment]
Les dernières corrections des API tiers ont été livrées juste avant la fin de la v1. C'est pour cela qu'elles ne sont pas prises en compte.

Correction testée et validée, merci.

**Comment by Gaetanbrl** [comment]
> Les dernières corrections des API tiers ont été livrées juste avant la fin de la v1. C'est pour cela qu'elles ne sont pas prises en compte.

Ce correctif permet donc d'utiliser les actions et d'afficher les tiers selon la dernière version de l'API. A tester si tout cela correspond bien aux attentes.
