### ISSUE TITLE
[Consultation] - Fiche OA - Consulter suivi OA par vocation

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#171]
## Description

En tant que utilisateur 
Je souhaite consulter la fiche OA correspondante à sa vocation
Afin de visualiser les champs communs aux OA et propre à sa vocation

## (Si) Règles spécifiques - Règles métiers

Pour toutes les OA, il existe des attributs communs qui sont toujours affichés.
Les différentes vocations sont :

- Mixte : (affichage de certains attributs des différentes vocations);
- Habitat ;
- Activités ;
- Mobilités (hors périmètre de la commande)
- Equipements (hors périmètre de la commande)
- Espaces naturels (hors périmètre de la commande)

## Informations complémentaires

- Vocation MIXTE

**1 Composition / programmation**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| operation | Texte | Champ |  |  | /v2/operations | operation | 

**1.1 Programmation de logements**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Nombre logements | Entier | Champ numerique |  |  | /v2/operations | nbLogementsPrevu | 
| Programmation habitat | Texte | Champ |  |  | /v2/operations | informationsProgrammation.description (avec informationsProgrammation.Type.code = Habitat | 
| Programmation actvites | Texte | Champ |  |  | /v2/operations | informationsProgrammation.description (avec informationsProgrammation.Type.code = Activites | 
| Vocation ZA | Texte | Liste déroulante /!\ | --- | --- | /v2/operations | vocationZa.libelle | 
| Convention PLH Date | Date | champ date | --- | --- | /v2/operations | plh.date | 
| Convention PLH | Texte | Champ | --- | --- | /v2/operations | plh.description | 
| PLH nbre logts prévus | Entier | Champ numerique | --- | --- | /v2/operations | plh.logementsPrevus | 
| PLH nbre logts livrés | Entier | Champ numerique | --- | --- | /v2/operations | plh.logementsLivres | 
| Scot | Booleen | Checkbox | --- | --- | /v2/operations | scot | 
| Densité mini SCoT | Entier | Champ numerique | --- | --- | /v2/operations | densiteScot | 
| Densité mini OAPQ | Entier | Champ numerique | --- | --- | /v2/operations | plui.densiteOap /!\ | 

**1.2 Autre programmation**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Programmation équipement | Texte | Champ |  |  | /v2/operations | informationsProgrammation.description (avec informationsProgrammation.Type.code = Equipement | 
| Programmation autre | Texte | Champ |  |  | /v2/operations | informationsProgrammation.description (avec informationsProgrammation.Type.code = Autres | 

**2 Contribution à la mise en œuvre du PADD et des OAP métropolitaines**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Principaux enjeux généraux | Texte | Champ |  |  | /v2/operations | contributions.description (avec contributions.Type.code = Enjeux | 
| Principales prises en compte | Texte | Champ |  |  | /v2/operations | contributions.description (avec contributions.Type.code = Traitee | 
| Comment aller plus loin? | Texte | Champ |  |  | /v2/operations | contributions.description (avec contributions.Type.code = Avenir | 

- Vocation HABITAT

**1 Composition / programmation**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| operation | Texte | Champ |  |  | /v2/operations | operation | 

**1.1 Programmation de logements**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Nombre logements | Entier | Champ numerique |  |  | /v2/operations | nbLogementsPrevu | 
| Programmation habitat | Texte | Champ |  |  | /v2/operations | informationsProgrammation.description (avec informationsProgrammation.Type.code = Habitat | 
| Convention PLH Date | Date | champ date | --- | --- | /v2/operations | plh.date | 
| Convention PLH | Texte | Champ | --- | --- | /v2/operations | plh.description | 
| PLH nbre logts prévus | Entier | Champ numerique | --- | --- | /v2/operations | plh.logementsPrevus | 
| PLH nbre logts livrés | Entier | Champ numerique | --- | --- | /v2/operations | plh.logementsLivres | 
| Scot | Booleen | Checkbox | --- | --- | /v2/operations | scot | 
| Densité mini SCoT | Entier | Champ numerique | --- | --- | /v2/operations | densiteScot | 
| Densité mini OAPQ | Entier | Champ numerique | --- | --- | /v2/operations | plui.densiteOap /!\ | 

**1.2 Autre programmation**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Programmation équipement | Texte | Champ |  |  | /v2/operations | informationsProgrammation.description (avec informationsProgrammation.Type.code = Equipement | 
| Programmation autre | Texte | Champ |  |  | /v2/operations | informationsProgrammation.description (avec informationsProgrammation.Type.code = Autres | 

**2 Contribution à la mise en œuvre du PADD et des OAP métropolitaines**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Principaux enjeux généraux | Texte | Champ |  |  | /v2/operations | contributions.description (avec contributions.Type.code = Enjeux | 
| Principales prises en compte | Texte | Champ |  |  | /v2/operations | contributions.description (avec contributions.Type.code = Traitee | 
| Comment aller plus loin? | Texte | Champ |  |  | /v2/operations | contributions.description (avec contributions.Type.code = Avenir | 

- Vocation ACTIVITES

**1 Composition / programmation**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| operation | Texte | Champ |  |  | /v2/operations | operation | 

**1.1 Programmation de logements**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Programmation actvites | Texte | Champ |  |  | /v2/operations | informationsProgrammation.description (avec informationsProgrammation.Type.code = Activites | 
| Vocation ZA | Texte | Liste déroulante /!\ | --- | --- | /v2/operations | vocationZa.libelle | 
| Scot | Booleen | Checkbox | --- | --- | /v2/operations | scot | 
| Densité mini SCoT | Entier | Champ numerique | --- | --- | /v2/operations | densiteScot | 
| Densité mini OAPQ | Entier | Champ numerique | --- | --- | /v2/operations | plui.densiteOap /!\ | 

**1.2 Autre programmation**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Programmation équipement | Texte | Champ |  |  | /v2/operations | informationsProgrammation.description (avec informationsProgrammation.Type.code = Equipement | 
| Programmation autre | Texte | Champ |  |  | /v2/operations | informationsProgrammation.description (avec informationsProgrammation.Type.code = Autres | 

**2 Contribution à la mise en œuvre du PADD et des OAP métropolitaines**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Principaux enjeux généraux | Texte | Champ |  |  | /v2/operations | contributions.description (avec contributions.Type.code = Enjeux | 
| Principales prises en compte | Texte | Champ |  |  | /v2/operations | contributions.description (avec contributions.Type.code = Traitee | 
| Comment aller plus loin? | Texte | Champ |  |  | /v2/operations | contributions.description (avec contributions.Type.code = Avenir | 

## Complément (échange du 19/11/2021)

Il se peut que plusieurs vocations existent au sein d'une OA (ex: une OA de type Mixte peut avoir un immeuble et une bouche de métro. On aura donc deux vocations "Habitat" pour l'immeuble et "Equipements" publics pour le métro réparties dans deux secteur distincts).

Donc dans ce type de cas, nous pourrons considérer qu'un secteur au sein d'une OA correspond à une vocation.
Pour observer en détail les information d'une vocation au sein d'une OA, l'utilisateur devra cliquer sur la carte sur un secteur au sein de l'OA  pour accéder à ses informations.

##  Tests d'acceptabilité

Tests d'acceptabilité

1. Ouvrir le plugin Tabou2
2. Cliquer sur une OA de chaque type de vocation
3. Voir que la fiche OA correspond à sa vocation et qu'elle affiche les attributs correspondants

**Comment by Gaetanbrl** [comment]
En attente des specs pour avoir les attributs par vocation.

**Comment by dcottenc** [comment]
@Gaetanbrl Mise à jour de la description du ticket

**Comment by Gaetanbrl** [comment]
@dcottenc est-ce qu'il est possible d'avoir un nom court pour les catégories ?
En effet, je propose d'utiliser des onglets pour les catégories d'attributs au sein d'une vocation afin de ne pas scroller jusqu'à très bas dans la fenêtre.

Voici un aperçu avec les noms en l'état actuel (à améliorer c'est pour le concept) :

![image](https://user-images.githubusercontent.com/16317988/164417286-c4171829-3859-4acc-946f-ae9b5e3ee5df.png)

**Comment by Gaetanbrl** [comment]
> Pour toutes les OA, il existe des attributs communs qui sont toujours affichés.

A préciser par MOA

**Comment by Gaetanbrl** [comment]
@dcottenc @ThomasBruleOpen les codes me semblent étranges pour `informationsProgrammation`.

Actuellement on a qu'une seule valeur de type : 
https://portail-test.sig.rennesmetropole.fr/tabou2/types-programmations?asc=true

```
code: "CODE_TYPE_PROG_1_TBR"
libelle: "Type de programmation de test TBR"
```

Quand seront intégrés les vrais types comme attendus par les specs de cette issue ?

**Comment by ThomasBruleOpen** [comment]
@Gaetanbrl : les types de programmation viennent d'être intégré : 
`{"elements":[{"id":1,"code":"Habitat","libelle":"Type de programmation Habitat","dateInactif":null,"createUser":"t.brule","createDate":"2022-04-22T14:24:01.000+00:00"},{"id":2,"code":"Activites","libelle":"Type de programmation Activités","dateInactif":null,"createUser":"t.brule","createDate":"2022-04-22T14:24:01.000+00:00"},{"id":3,"code":"Equipement","libelle":"Type de programmation Equipement","dateInactif":null,"createUser":"t.brule","createDate":"2022-04-22T14:24:01.000+00:00"},{"id":4,"code":"Autres","libelle":"Type de programmation Autres","dateInactif":null,"createUser":"t.brule","createDate":"2022-04-22T14:24:01.000+00:00"}],"totalElements":4}`

**Comment by Gaetanbrl** [comment]
il manque les types Enjeux, Traitee, Avenir par contre ?

**Comment by Gaetanbrl** [comment]
Autant pour moi... j'ai louché sur les contributions

**Comment by Gaetanbrl** [comment]
pour contributions, les codes des specs sont différents de ceux fournis par l'API.

Code specs ==> Enjeux
Code API ==> CONTRIBUTION_ENJEUX

**Comment by Gaetanbrl** [comment]
@dcottenc dans le système actuel, il n'est pas prévu / possible de supprimer un type programmation ou une contribution.
Vu que aucun champ n'est obligatoire on a les questions suivantes : 

1. Au départ, on a aucun type contribution et aucun type programmation
2. On saisi une description => On ajoute le type correspondant

**Question :** 

Si On supprime le texte de la description ? 
On fait quoi ? On considère qu'on supprime le type ? Mais si on veut garder le type sans description ?

**Comment by Gaetanbrl** [comment]
Livré ce jour. A tester.

**Comment by dcottenc** [comment]
Teste et validé (Portail test RM)

*Attention, le ticket #218 précise des modifications identifiées en VA*
