### ISSUE TITLE
[Impression] - Fiche OA - Impression fiche suivi OA

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#172]
## Description

**En tant que** utilisateur,
**Je souhaite** imprimer la fiche de suivi d'une OA à partir de la fiche de consultation d'une OA
**Afin** de consulter ou télécharger un PDF contenant les informations de l'entité en cours.

## Tests d'acceptance

1. Se connecter
2. Cliquer sur la couche OA
2. Cliquer sur une entité de la couche OA sur la carte
4. Voir la Fiche OA contenant les informations sur l'entité sélectionnées
5. Voir en haut de la fiche un bouton "Imprimer"
6. Cliquer sur le bouton "Imprimer" pour consulter ou exécuter le téléchargement de la fiche pour l'entité sélectionnée
7. Valider que le document consulté ou téléchargé contient les informations de la fiche en cours

## Précisions techniques

L'utilisateur cliquera sur un bouton "imprimer" qui devra être visible dans la fiche information d'une OA suivie. Au clic, un appel à l'API via un web service permettra de récupérer un document PDF.

La fonctionnalité est identique à l'impression de la fiche PA. Seul le nom du Web Service change.

**Comment by Gaetanbrl** [comment]
Testé ce jour => OK
En attente de retour @dcottenc pour clore l'issue.
