### ISSUE TITLE
[Consultation] - Fiche OA - Consulter informations PLUI

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#173]
## Description

En tant que utilisateur 
Je souhaite consulter les informations relatives au PLUI sur la fiche d'une OA
Afin de visualiser les différentes règles du PLUi qui s'applique à l'OA

## (Si) Règles spécifiques - Règles métiers

L'affichage des informations relatives au PLUI comporte plusieurs champs textes en lecture seule (10-20).
Il est possible de les présenter sous forme d'une fiche spécifique accessible via un bouton ou directement sous forme d'un bloc dans la fiche OA. Un travail sur l'ergonomie de la fiche OA est à prévoir.

##  Tests d'acceptabilité

Tests d'acceptabilité

1. Ouvrir le plugin Tabou2
2. Cliquer sur une OA 
3. Voir qu'à partir de la fiche OA , il est possible de consulter les données du PLUi relatives à celle-ci

**Comment by Gaetanbrl** [comment]
API non réalisée => Informations non fournies par MOA pour.

**Comment by dcottenc** [comment]
Fonctionnalité non incluse dans ce marché
