### ISSUE TITLE
[Consultation] Fiche OA - Filtrer SA et PA

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#175]
## Description

En tant que utilisateur 
Je souhaite pouvoir faire un filtre à partir de l'onglet consultation d'une OA
Afin de n'afficher que les SA et les PA de celle-ci

## Règles spécifiques - Règles métiers

L'utilisateur a besoin de filtrer les entités SA et PA d'une OA pour notamment afficher les statistiques uniquement sur celles-ci.
La solution souhaitée serait de pouvoir effectuer l'action à partir d'un bouton poussoir sur la fiche de l'OA. L'annulation du filtre pourrait se faire sur la fiche mais également dans l'onglet filtre si besoin.
Une alternative serait de proposer un champ de recherche de l'OA à partir de l'onglet Filtre.

Lors de ce filtre :

- la couche OA ne contient plus qu'une OA (celle en cours)
- les entités de la couche SA sont filtrées spatialement par l'emprise de l'OA en cours
- les entités de la couche PA sont filtrées attributairement sur l'ID de l'OA en cours (API /operations/{id]/programme)

##  Tests d'acceptabilité

Tests d'acceptabilité

1. Ouvrir le plugin Tabou2
2. Cliquer sur une OA 
3. Cliquer sur l'onglet consultation de la fiche de l'OA
4. Cliquer sur le bouton "Filtrer les entités sur cette  opération"
5. Les couches OA / SA / PA sont filtrées sur l'OA en cours.

**Comment by Gaetanbrl** [comment]
Ce bouton serait donc un raccourci à l'application d'un filtre spatial sur les couches SA et PA (fonctionnalité native MapStore) si je comprends bien.

Avez-vous échangé avec la MOA afin d'utiliser les filtres spatiaux sur ces deux couches  (croissement spatial + usage d'un filtres) ?

**Comment by Gaetanbrl** [comment]
Quel serait le cas d'usage avec un filtre déjà actif ?

**Comment by dcottenc** [comment]
> Ce bouton serait donc un raccourci à l'application d'un filtre spatial sur les couches SA et PA (fonctionnalité native MapStore) si je comprends bien.

Oui, ce bouton permet d'appliquer des filtres standards simultanément sur les trois couches.

**Comment by dcottenc** [comment]
> Avez-vous échangé avec la MOA afin d'utiliser les filtres spatiaux sur ces deux couches (croissement spatial + usage d'un filtres) ?

Je ne sais pas  si j'ai bien compris la question mais ce bouton remplace trois manips (pas si simple) sur trois couches pour les utilisateurs non experts

**Comment by dcottenc** [comment]
>Quel serait le cas d'usage avec un filtre déjà actif ?

L'annulation du filtre précèdent. Il est difficile de prévoir autre chose notamment si l'OA n'est pas dans le filtre encours

**Comment by Gaetanbrl** [comment]
> Je ne sais pas si j'ai bien compris la question mais ce bouton remplace trois manips (pas si simple) sur trois couches pour les utilisateurs non experts

C'est noté. Sans connaissance ou formation préalable sur MapStore ca peut en effet paraître complexe. 

Je reviens vers toi avec un complément au chiffrage.

**Comment by Gaetanbrl** [comment]
Voici les requêtes à jouer.

- Filtrer une SA par intersection avec une OA en lecture dans le volet `identifier`

On appliquera directement un filtre spatiale sur la couche SA.

> Exemple avec une intersection en OA Baud Chardonnet (id_tabou 15) et la couche SA :
> `CQL_FILTER=(INTERSECTS(shape,collectGeometries(queryCollection('app:tabou_v_oa_operation', 'shape','("id_tabou" = ''15'')'))))`

Les filtres déjà existants seront remplacés par ce filtre unique.

- Filtrer une PA selon une liste d'ID retournée par l'API

L'appel à l'API permettra en premier de récupérer les ID de PA à afficher.

> _Ex pour avoir les programmes de Baud Chardonnet_ : 
> https://portail-test.sig.rennesmetropole.fr/tabou2/operations/15/programmes?asc=true

On appliquera ensuite un filtre CQL sur la couche WMS PA avec les ID à afficher :

> `("id_tabou" = '429' OR "id_tabou" = '453')`

**Comment by dcottenc** [comment]
> Voici les requêtes à jouer.

Ok, ne pas oublier de filtrer la couche OA : filtre CQL avec id_tabou= Id de l'OA

**Comment by Gaetanbrl** [comment]
Développements visibles et testables sur le contexte de test urb@map.

![175_1](https://user-images.githubusercontent.com/16317988/144893967-f489e67b-19c5-4466-892e-7492e7320964.gif)

En attente de validation.

**Comment by dcottenc** [comment]
Testée et en cours de validation par la MOA

**Comment by dcottenc** [comment]
Validée par la MOA
