### ISSUE TITLE
API - Requête POST ne lisent pas toutes le corps de la requête   

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#180]
# Description

Auparavant, mes requêtes envoies les paramètre d'une requête POST dans la requête (body) et non dans l'URL.

Par exemple, pour associer un tiers :

> URL : http://localhost:8081/tabou2/programmes/143/tiers
> Paramètres : {tiersId: 115, typeTiersId: 3}

 
Aujourd'hui, j'ai une erreur car le corps de la réponse n'est plus pris en compte dans le backend.
Il est nécessaire de passer les paramètres dans l'URL comme une requête POST pour que la requête fonctionne : 

`
http://localhost:8081/tabou2/programmes/143/tiers?tiersId=115&typeTiersId=3
`

Un changement a du être apporté car mes requêtes sont toutes basées su l'envoi des paramètres dans le corps, ce qui été fonctionnel pour la release actuelle et qui ne fonctionne plus aujourd'hui avec l'API.

Requête POST concernées :

- /programmes/id/documents
- /operations/id/documents
- /programmes/id/tiers

# Reproduire

* Dans le Swagger, réaliser une association entre un tiers et un programme.
* Voir que la requête CURL insère tous les paramètres dans l'URL.

**Comment by Gaetanbrl** [comment]
@dcottenc avez-vous des avancées sur ce ticket ?

**Comment by dcottenc** [comment]
@Gaetanbrl je ne vois rien d'effectué coté OPEN. Est-ce que ce sujet est toujours d'actualité ?
Je suis d'accord avec ta remarque mais plutôt favorable pour laisser ca comme pour éviter des devs.

**Comment by dcottenc** [comment]
> je ne vois rien d'effectué coté OPEN. Est-ce que ce sujet est toujours d'actualité ?

Rectification : /programmes/{programmeId}/tiers par exemple prends bien un id et le reste des paramètres dans le body.
