### ISSUE TITLE
GED - Upload d'un Fichier existant déjà

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#186]
#Description

Lors de l'upload d'un fichier une seconde fois, on voit que l'API (ou Alfresco) ajoute "-x" derrière le nom (e.g testods1-1).

Est-possible d'envisager (dans le futur) un control + une alerte si le nom existe déjà ?

**Comment by dcottenc** [comment]
La règle de gestion qui s'applique est que pour tout document modifié, sa version est automatiquement incrémentée.
Ce choix a été pris selon nos REX pour que les utilisateurs n'aient pas à gérer le versionnement et donc justement ne pas avoir cette alerte (dans un premier temps)

Par contre, je suis surpris que tu puisses voir la version du doc dans le nom car je ne l'ai pas constaté dans Swagger et c'est pour cela que j'ai demandé à avoir des droits supplémentaires dans Alfresco (pour valider l'incrémentation des versions entre autre).

**Comment by Gaetanbrl** [comment]
> Par contre, je suis surpris que tu puisses voir la version du doc

Je ne sais pas si c'est normal mais en tout cas c'est dans le nom (ou libelle je ne sais plus)

**Comment by dcottenc** [comment]
Apres tests : 
- cette question concerne l'ajout d'un document avec le même nom qu'un document déjà dans la GED => Alfresco ajoute un -2 au nom (fonctionnement nominal de ma GED)
- par contre, si un document est modifié, c'est bien la version qui est incrémentée.

@Gaetanbrl Pour répondre à la question, la fonctionnalité permettant de savoir si un nom existe déjà est possible mais serait à développer dans notre API (est à inclure dans le WS comme contrôle lors de l'ajout d'un document).
