### ISSUE TITLE
Filtrer entités - Résultats non cohérents

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#187]
**Description du bug**
Dans l'environnement de test, la sélection d'un critère spatial ne retourne pas toutes les entités contenues dans l'emprise et retourne des entités hors de l'emprise.

**Reproduire le bug**
1. Se connecter au portail-test
2. Ouvrir Ubr@map
3. Créer le filtre sur la commune de Saint jacques
4. Appliquer le filtre
5. En test, le résultat incorrect ;
![image](https://user-images.githubusercontent.com/76009802/150145005-9660167d-3070-4f2e-9e12-a460ae8a4509.png)

**Comportement attendu**
En production le résultat est correct : 
![image](https://user-images.githubusercontent.com/76009802/150144271-5f87e261-9ea0-4e55-ad70-954ddf08f6fe.png)

**Environnement / Desktop**

Portail -test RM

**Comment by Gaetanbrl** [comment]
# Test sur Cesson-Sévigné 


### Requête couche OA : 
Requête `POST` vers `https://portail-test.sig.rennesmetropole.fr/geoserver/ows`

```
CQL_FILTER: (INTERSECTS(shape,collectGeometries(queryCollection('ladm_terri:commune_emprise', 'shape','("code_insee" = 35051)')))) AND id_tabou IS NOT NULL
SERVICE: WFS
REQUEST: GetFeature
TYPENAME: tabou_v_oa_operation
OUTPUTFORMAT: application/json
VERSION: 1.0.0
```

### Résultats

totalFeatures: 11 :

```
tabou_v_oa_operation.3
tabou_v_oa_operation.4
tabou_v_oa_operation.69
tabou_v_oa_operation.82
tabou_v_oa_operation.93
tabou_v_oa_operation.95
tabou_v_oa_operation.102
tabou_v_oa_operation.127
tabou_v_oa_operation.132
tabou_v_oa_operation.133
tabou_v_oa_operation.237
```

Soit les objectIds `3,4,69,82,93,95,102,127,132,133,237`.

### IDs appliqué dans le filtre OA 

![image](https://user-images.githubusercontent.com/16317988/150147691-a9c32ccd-13a9-4233-a002-61c10f678377.png)

### IDs envoyés dans la requête WMS

Requête `GET`

```
LAYERS: tabou_v_oa_operation
CQL_FILTER: ("objectid" = '3' OR "objectid" = '4' OR "objectid" = '69' OR "objectid" = '82' OR "objectid" = '93' OR "objectid" = '95' OR "objectid" = '102' OR "objectid" = '127' OR "objectid" = '132' OR "objectid" = '133' OR "objectid" = '237')
```

**Comment by dcottenc** [comment]
> Soit les objectIds 3,4,69,82,93,95,102,127,132,133,237.

C'est pour cela que j'évoquai le contrôle de la configuration du plugin. 
Le portail tests contient deux couches tabou_v_oa_operation :
- app:tabou_v_oa_operation pour les données de production (sans commentaire)
- test:tabou_v_oa_operation

Donc si le CQL filter ne s'applique pas sur la même couche, les résultats seront aberrant (objectid différent).
J'ai essaye de mettre le test:tabou_v_oa_operation au lieu de tabou_v_oa_operation mais cela ne fonctionnait plus du tout.

**Comment by Gaetanbrl** [comment]
> J'ai essaye de mettre le test:tabou_v_oa_operation au lieu de tabou_v_oa_operation mais cela ne fonctionnait plus du tout.

Il faut en effet une cohérence entre la couche de recherche et la couche à trouver. A la base nous devions utiliser la même couches en effet.

En local sur notre geoserver je n'ai pas de soucis, le filtre fonctionne bien.

Voici la configuration utilisée pour les limites de longueur de l'URL / max entité :

```
"limit": 100000,
"maxURLLength": 2000
```

**Comment by Gaetanbrl** [comment]
@dcottenc tests en cours sur un filtre à partir du champ "id_tabou" au lieu de "objectid"

**Comment by Gaetanbrl** [comment]
@dcottenc testé et déployé sur https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/Tabou-lot2

Je valide avec l'utilisation du champ id_tabou.
Autrement, la requête qui permet de filtrer toute la couche PA sur l'ensemble de Rennes est toujours émise en GET alors que ce devrait être du POST.

**Comment by dcottenc** [comment]
> Je valide avec l'utilisation du champ id_tabou.

C'est un contournement qui fonctionne peut-être uniquement car les Id_Tabou sont actuellement à 95% identiques entre les  bases de prod et de test.
Nous n'avons pas identifié le problème de fond qui doit tourner autour de l'utilisation du prefixe test devant le nom des couches. 

> Il doit y avoir un problème dans votre paramétrage
C'est gênant. Le paramétrage semble bon. La version 21.2 est-elle celle que vous utilisez ?

**Comment by Gaetanbrl** [comment]
> C'est gênant. Le paramétrage semble bon. La version 21.2 est-elle celle que vous utilisez ?

Non en effet. Je peux faire un test.

Le soucis c'est que le dépôt initial geor_tabou_front n'est pas un fork du dépôt des extensions comme déjà évoqué ultérieurement plusieurs fois. Je dois donc écraser les branches avec un upgrade des branches.

Pour rappel, c'est la version du submodule MS2 du dépôt mapstore-extension qui fait foi et non le submodule MapStore2 du dépôt mapstore2-georchestra. De plus, je ne sais pas si les version MS2 de ces deux dépôts sont actuellement ISO.

**Comment by dcottenc** [comment]
Gaëtan, mes limites de compréhension sont atteintes dans ton dernier message.
Concrètement faut-il que l'on discute avec Catherine ou est-elle deja au courant de cela ?

**Comment by Gaetanbrl** [comment]
> Concrètement faut-il que l'on discute avec Catherine ou est-elle deja au courant de cela ?

Vous savez déjà tout ce n'est pas utile. Je vais faire la mise à jour manuellement mais ca ne m'empêche pas de tester sur un environnement plus à jour. Bien que je ne pense pas que ce soit le problème...

**Comment by Gaetanbrl** [comment]
@dcottenc a fermer ?
