### ISSUE TITLE
API - GED - paramètre operationid non remplacé

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#189]
# Description

Via le Swagger, pour ajouter un document sur une opération (id 100) nous avons la requête suivante : 

`https://portail-test.sig.rennesmetropole.fr/tabou2/operations/%7BoperationId%7D/documents?operationId=100&nom=zjdev2test&libelle=zjdev2test`

Ce qui est étrange c'est l'URL /operationid avec des `{}` :

`curl -X POST "https://portail-test.sig.rennesmetropole.fr/tabou2/operations/{operationId}/documents?operationId=100&nom=zjdev2test&libelle=zjdev2test" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "fileToUpload=@index.json;type=application/json"`

Mais le document semble tout de même envoyé.

**Comment by dcottenc** [comment]
> Mais le document semble tout de même envoyé.

Je confirme. je n'avais pas vu. Il y a redondance entre les deux ID et visiblement celui entre {} n'est pas utilisé :s 
Je recommande de le renseigner qd même pour anticiper la correction que je vais demander.

**Comment by Gaetanbrl** [comment]
> Je recommande de le renseigner qd même pour anticiper la correction que je vais demander.

Je viens de le rajouter.

**Comment by dcottenc** [comment]
Ticket OPEN CDCRM-1023

**Comment by dcottenc** [comment]
Fermé car suivi dans JiRa Open
