### ISSUE TITLE
API GED - Pagination

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#190]
# Description

L'api contient les paramètres `start` et `resultsNumber` pour faire de la pagination (attendu pour afficher les documents).
Mais le fonctionnement est à décrire ou n'est pas fonctionnel.

# Test 

Avec l'opération Baud Chardonnet,  je souhaite diviser par 3 les documents (3 documents par page maximum).
D'après le Swagger je dois donc avoir 3 appels (car l'OA à 9 documents) : 

Documents 0,1,2 ==> `Retourne 3 résultat` ==> OK
https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/documents?start=0&resultsNumber=3&asc=true

Documents 1,2,3 ==> `Retourne aucun résultat` ==> KO
https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/documents?start=3&resultsNumber=3&asc=true

Documents 4,5,6 ==> `Retourne aucun résultat` ==> KO
https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/documents?start=6&resultsNumber=3&asc=true

@dcottenc comment dois-je utiliser la pagination avec l'API ?

**Comment by dcottenc** [comment]
> comment dois-je utiliser la pagination avec l'API ?

Son fonctionnement est identique pour toutes les API : 

- Start : défini la page à lire (commence à 0)
- resultsNumber : le nombre d'éléments par page

Je confirme que cela fonctionne correctement mais je vais demander à préciser le fonctionnement du start dans le swagger

**Comment by dcottenc** [comment]
Documents 1,2,3 (page 1 si 3 éléments) 
[https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/documents?start=0&resultsNumber=3&asc=true](https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/documents?start=0&resultsNumber=3&asc=true)

Documents 4,5,6  (page 2 si 3 éléments) 
[https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/documents?start=1&resultsNumber=3&asc=true](https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/documents?start=1&resultsNumber=3&asc=true)

Documents 7,8,9  (page 3 si 3 éléments) 
[https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/documents?start=2&resultsNumber=3&asc=true](https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/documents?start=2&resultsNumber=3&asc=true)

**Comment by Gaetanbrl** [comment]
C'est compris. Merci.

**Comment by Gaetanbrl** [comment]
@dcottenc suite à mon précédent commentaire, il est possible de modifier la définition ou le nom du paramètre start qui porte à confusion ? Le nom "page" me semble plus approprié. C'est mineur...
