### ISSUE TITLE
APi GED - Suppression d'un document

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#193]
# Description

J'utilise la valeur `totalElements` pour avoir le nombre de page à afficher. Si j'ai 6 documents (valeur `totalElements`) et que j'en affiche 5 par page, alors j'affiche 2 pages dans la barre de pagination.

Mais lorsqu'on supprime un document et que le code JS appel l'ensemble des documents directement après via le WS dédié, alors le retour de l'API affiche une valeur de la propriété `totalElements` qui n'est pas bon car il comprend toujours le document précédemment supprimé.

# Reproduire 

1. Ajouter 6 documents pour une opération (id OA 100)
2. Appeler le WS pour lister les 6 documents et les observer dans le plugin Tabou

https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/documents?asc=true

```
{
  "elements": [
    {
      "id": "a37e5d7c-9b9b-4ff9-a44d-ad8853324d81",
      "nom": "test1297-2",
      "libelle": "test1297",
      "typeMime": "text/plain",
      "modifUser": "TABOU",
      "modifDate": "24/01/2022 11:04"
    },
    .........
  ],
  "totalElements": 6
}
```

3. Supprimer un document via le plugin Tabou et observer les requêtes API
4. Voir que la valeur totalElements est toujours à 6 selon le retour API (il devrait être à 5)
5. Voir que le plugin indique 2 pages (5 docs par pages) car l'API retourne 6 totalElements
6. Cliquer sur la page 2 et voir que rien ne s'affiche car il n'y a en réalité que 5 totalElements (nous venons de supprimer le 6è)
7. Fermer la modal
8. Cliquer sur le bouton "Documents"
9. Voir qu'il n'y a bien qu'une page d'affichée car un nouvel appel a été avec le nombre correct d'éléments

Il doit y avoir une latence entre la suppression et la possibilité d'avoir la bonne valeur.

![delete_doc](https://user-images.githubusercontent.com/16317988/150770201-a22663c7-ce58-4a7d-bc26-dcf638bb8ea2.gif)

# Comportement attendu

Lorsqu'on supprime un document, il est attendu que les appels du WS ci-dessous indiquent le nombre correct de la valeur totalElements et directement après la suppression d'un document.

https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/documents?asc=true

# Solution Front

Il est complexe d'apporter une solution côté front dans ce cas de figure.
Il pourrait toutefois être ajouté un control pour afficher un message si nous n'avons pas de documents pour la page 2.
Mais pour moi c'est une rustine qui ne corrige pas le problème.

**Comment by dcottenc** [comment]
Idem #194

**Comment by dcottenc** [comment]
Ce problème est bien lié à #194 
Mais c'est un cas qui peut être lié également à la mise à jour des documents par un autre utilisateur.
Il est donc bien nécessaire d'actualiser l'affichage de la liste (contenu et pagination) à chaque action sur son affichage (changement de page par exemple).
Dans le cas particulier d'une page vide (demande basée sur un totalElements mis à jour) alors son affichage ne me choque pas du moment que la page n'est pas en erreur et que l'on peut revenir sur la page précédente.

**Comment by Gaetanbrl** [comment]
>Il pourrait toutefois être ajouté un control pour afficher un message si nous n'avons pas de documents pour la page 2.

Modification apportée hier : 

_Si l'utilisateur clique sur la page 2 mais qu'en réalité nous n'avons qu'une page, alors il y a un appel au web service pour forcer le retour sur la page précédente._

**Comment by dcottenc** [comment]
La nouvelle version de la fenêtre document rend cette ano caduque
