### ISSUE TITLE
API GED - cohérence des infos à l'ajout et récupération des documents

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#194]
# Description

Via le Swagger, on peut ajouter un document et récupérer la liste des documents directement après.
Hors, il faut attendre quelques secondes pour avoir le retour correcte entre l'ajout et la récupération.

/!\ Teste réalisé avec un JSON !

# Reproduire

1. Ouvrir dans deux onglets le swagger avec un onglet sur l'affichage des documents et l'autre avec l'ajout d'un document (pour avoir + de rapidité dans le test)
2. Lister les documents de l'OA 100
3. Ajouter un document sur l'onglet (A) et attendre le retour CODE 200 via le swagger
4. Directement après sur l'onglet (B), lister les documents
5. Voir que le document ajouté n'est pas présent

# Conséquences
Cette latence va poser des problèmes comme pour la suppression (lié à #193) car on a besoin de la valeur totalElements pour paginer correctement les documents.

De plus, le front ne peut pas savoir quand le backend a terminé les process pour être rafraichi. Les appels sont donc directement fait en cascade et ce fonctionnement est validé pour les tiers comme pour le journal d'événements.

Je suppose que cette latence est liée au temps de réponse entre Alfresco + api Tabou. On demande à l'API Tabou de répondre alors que Alfresco n'est peut-être pas encore à jour.

# Solution

Une possibilité est d'afficher un bouton "Raffraîchir" pour donner la possibilité de faire un refresh manuel.

**Comment by dcottenc** [comment]
@Gaetanbrl je vais poser la question car si l'API retourne le code 200, c'est bien que l'API Alfresco a terminé son traitement.

**Comment by Gaetanbrl** [comment]
> je vais poser la question car si l'API retourne le code 200, c'est bien que l'API Alfresco a terminé son traitement.

Merci, je reproduis en tout cas à chaque test (en attendant bien le code 200 avant d'appeler la liste des documents après ajout).

**Comment by dcottenc** [comment]
> @Gaetanbrl je vais poser la question car si l'API retourne le code 200, c'est bien que l'API Alfresco a terminé son traitement.

Cette hypothèse ne se vérifie pas. Il y a effectivement plusieurs secondes après le http200 de l'ajout avant que la liste ne s'actualise.
Je vais soumettre le sujet à Florent.

**Comment by dcottenc** [comment]
L'analyse de ce sujet montre qu'Alfresco met plusieurs secondes après l'enregistrement du fichier pour le rendre disponible (délais, d'indexation, affectation des droits...).
Ce délai sera sans doute amplifié lorsque les documents seront  triés pour le plan de classement.
A ce stade, nous allons solliciter la DSI pour savoir si on peut améliorer ce délai dans Alfresco.

Ce dernier point étant peu probable, le plan B serait d'avoir un bouton "Rafraichir" pour la liste (relance de l'appel au WS de la liste des documents).

**Comment by dcottenc** [comment]
@Gaetanbrl Pour l'instant, le "Rafraichir" me semble effectivement notre seule option. Merci
Je n'ai pas constaté de problème similaire lors de l'utilisation du client Alfresco. Mais je ne sais pas comment c'est géré.

**Comment by dcottenc** [comment]
La solution proposée (bouton Rafraichir) est pertinente et me semble satisfaisante (A valider par la MOA).
Pour information, nous avons interrogé la DSI à ce sujet. Ils vont pouvoir améliorer sensiblement le délai de latence en supprimant l'indexation du contenu des fichiers (non utile dans notre cas).

Anomalie fermée car la solution Front répond au problème et les actions de correction en amont sont coté DSI RM
