### ISSUE TITLE
API GED - PUT document/content et changement de type

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#195]
# Description

Lorsqu'on créé un document de type text et qu'on modifie ensuite le contenu par une image, alors on ne peut pas télécharger le document correctement car l'image est toujours considérée comme du texte.

# Reproduire

1. Aller sur le swagger
2. Ajouter un document format .txt pour l'opération avec l'id 100
3. Modifier le contenu (requête PUT) et ajouter une image .png
4. Télécharger le document
5. Voir que ce sont les données de l'image qui sont téléchargées au format .txt
6. Appeler les métadonnées pour le document précédemment modifié
7. Voir que le `mimeType` est toujours en `text/plain`. Il devrait être en `image/png`
```
{
  "id": "ad947326-a347-48b9-a797-de06b9af9feb",
  "nom": "logo-rm",
  "libelle": "text",
  "typeMime": "text/plain",
  "modifUser": "TABOU",
  "modifDate": "25/01/2022 11:40"
}
```
![image](https://user-images.githubusercontent.com/16317988/150960477-f8d49361-ea19-4d70-bdea-f6371cc6270e.png)

**Comment by Gaetanbrl** [comment]
> il apparait assez cohérent de limiter le changement de format d'un document

J'imagine que les utilisateurs vont trouver cela contraignant s'ils se trompent. Ils devront alors tout refaire.

C'est une limite alfresco ?

**Comment by dcottenc** [comment]
> J'imagine que les utilisateurs vont trouver cela contraignant s'ils se trompent. Ils devront alors tout refaire.
Je n'ai pas encore la réponse sur le fait de pouvoir modifier le type Mime lors d'une modification. C'est effectivement souhaitable pour répondre à ton alerte
> C'est une limite alfresco ?
Je n'ai pas encore eu la réponse

**Comment by dcottenc** [comment]
> C'est une limite alfresco ?

Je viens de tester directement dans Alfresco : il n'y a pas de contrainte sur le changement de type de document lors d'une modification de son contenu. 

Cette anomalie va être traitée dans le back (ticket Open 960)

**Comment by dcottenc** [comment]
Selon les retours que j'ai eu, il est nécessaire de mettre à jour les métadonnées (et non uniquement le contenu) quand le type Mime change.
J'ai essayé de vérifier lors de l'utilisation du client Web Alfresco mais je ne vois pas les appels aux WS dans la console...

**Comment by Gaetanbrl** [comment]
> il est nécessaire de mettre à jour les métadonnées (et non uniquement le contenu) quand le type Mime change.

Est-ce que l'API prévoit ce cas de MAJ de la metadata ?

**Comment by dcottenc** [comment]
> Est-ce que l'API prévoit ce cas de MAJ de la metadata ?

Non, cela n'avait pas été prévu. On n'a pas de retour si cela doit être systématique. Nous aimerions bien avoir comment le client Web Alfresco gère cela.

**Comment by Gaetanbrl** [comment]
Je propose de passer ce point en évolution (ou bug mineur à traiter dans une version ultérieure)
