### ISSUE TITLE
API IRIS - Erreur 500

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#196]
# Description

La recherche IRIS par code insee retourne une erreur 500
https://portail-test.sig.rennesmetropole.fr/tabou2/iris?ccom=35238&asc=true

**Comment by dcottenc** [comment]
Corrigée et testée.
L'utilisateur app_tabou n'avait pas les droits sur le schéma démographie et la table iris.
