### ISSUE TITLE
Filtrer entités - affichage résultats couche vide

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#199]
**Description du bug**

Lors de l'utilisation des filtres, il est apparu que dans certains cas une ou des couches n'étaient pas conformes aux résultats attendus. Il semble que cela soit lié à la gestion des couches avec un résultat vide.

**Reproduire le bug**

1. Se connecter au portail-test
2. Ouvrir Urb@map
3. Dans le plugin, créer le filtre sur la commune de Rennes et Natures = "en diffus"
4. Vérifier que l'avertissement s'affiche 

![image](https://user-images.githubusercontent.com/76009802/156130192-67439230-6ed2-4e12-ad2a-2f9b3e771bd0.png)

5. Appliquer le filtre => les couches secteurs et programmes devraient être vides mais elles ne sont pas actualisées et présentent donc toujours les entités présentes auparavant.

**Comportement attendu**

Lors de l'affichage de l'alerte ci-dessus, les couches correspondantes doivent être filtrée et actualisée (quand elles sont vides).

**Environnement**

Portail-test et prod RM

**Informations complémentaires**
Pour reproduire le bug en production, il est nécessaire d'utiliser un autre cas de test (la production contient des entités en diffus).

**Comment by Gaetanbrl** [comment]
Ce fonctionnement avait été vu avec Cyril en cotech.

@dcottenc quand le résultat est vide, quel est le filtre à appliquer aux couches ? En l'état si on a pas de retour alors je ne vois aucun filtre à appliquer car on réalise : 
1. appel geoserver CQL
2. Lecture des Ids dans le résultat (ex: le contain retourne l'id 1)
3. On applique ce filtre, donc dans mapstore la couche a un filtre attributaire sur l'id 1

Si pas d'ids retourné, je vais devoir appliqué un filtre erroné (ex: id = -1) et provoquer une erreur (symbole /!\ dans la TOC), ce qui entrainera un masquage complet de la couche.

D'où l'alerte qu'une des couches ne peut être filtrée car on a aucun résultat.

**Comment by dcottenc** [comment]
@Gaetanbrl, les utilisateurs ne comprennent pas voir des entités qui ne correspondent pas aux filtres. Cela fausse les résultats, les impressions et les extractions.
L'erreur (symbole /!\ dans la TOC) consécutive au chargement d'une couche vide est justement expliquée par ton message d'alerte et cela donne l'information complémentaire de la ou des couche(s) concernée(s).

**Comment by Gaetanbrl** [comment]
Ok mais quel filtre aberrant (qui provoque une erreur) les utilisateurs souhaitent voir dans la couche @dcottenc ?

**Comment by dcottenc** [comment]
Le filtre n'est pas aberrant.
Si on prend l'exemple du diffus, on a 99% des OA qui n'ont pas de secteur (SA). Donc pratiquement tous les filtres avec du Diffus ne retourneront aucun secteur.

**Comment by Gaetanbrl** [comment]
Je reformule @dcottenc :
Quel filtre (qui doit provoque une alerte sur la couche dans la TOC) dois-je mettre dans le volet de filtre des couches concernées afin d'avoir un résultat nul et qui pourrait correspondre à une compréhension + export + capture + stats corrects ?

Est-ce que un critère `id_tabou = -1` serait bon ?

**Comment by dcottenc** [comment]
Ca y est j'ai compris. De mémoire tu fais un filtre avec la liste des id donc oui id_tabou = 0 ou -1 tu ne trouveras rien

**Comment by Gaetanbrl** [comment]
Ca marche ;)

**Comment by dcottenc** [comment]
Cette modification n'est pas livrée ?

**Comment by Gaetanbrl** [comment]
non.
Non prévu dans la réserve de VA il me semble

==> A traiter en garantie ?

**Comment by dcottenc** [comment]
> ==> A traiter en garantie ?

Nous sommes encore en VSR, je ne pense pas pouvoir valider la VSR avec des réserves. A voir, mais ce soucis perturbe fortement les utilisateurs.

**Comment by Gaetanbrl** [comment]
Donc il n'y a pas que les bloquantes à corriger pour validation de la VSR... Je regarde celle-ci

**Comment by Gaetanbrl** [comment]
Il me faudra un peu de temps pour la couvrir, je ne pourrai pas pouvoir la faire cette fin de semaine ni semaine prochaine @dcottenc.

**Comment by dcottenc** [comment]
Passage en majeure (mais non bloquante), suite aux retours des utilisateurs qui sont perdus lors qu'une des couches ne contient pas de valeurs après filtre mais reste affichée.

**Comment by dcottenc** [comment]
Testé et validé en test. Merci c'est top !
