### ISSUE TITLE
Imprimer une fiche Programme

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#2]
## Description

**En tant que** chargé d'opération,
**Je souhaite** imprimer les informations d'une entité de la couche PA à partir de la fiche PA
**Afin** de consulter ou télécharger un PDF contenant les informations de l'entité sélectionnée.

## Tests d'acceptance

1. Se connecter
2. Cliquer sur la couche PA
2. Cliquer sur une entité de la couche PA sur la carte directement selon la couche cliquée
4. Voir la Fiche PA contenant les informations sur l'entité sélectionnées
5. Voir en bas de la fiche un bouton "Imprimer"
6. Cliquer sur le bouton "Imprimer" pour consulter ou exécuter le téléchargement de la fiche pour l'entité sélectionnée
7. Valider que le document consulté ou téléchargé contient les informations de la fiche

**Comment by Gaetanbrl** [comment]
Développé sur Develop.
En attente d'un retour utilisateur pour le nom du fichier. 
En attendant, le nom est repris directement depuis le retour API (content-disposition header).

![tabou_2](https://user-images.githubusercontent.com/16317988/125269348-e370dc00-e308-11eb-90c1-5e5340227931.gif)

**Comment by dcottenc** [comment]
Fonctionnement testé et validé

@Gaetanbrl : es-tu toujours dans l'attente de la spécification sur le nom du fichier (par la MOA) ?

**Comment by Gaetanbrl** [comment]
@dcottenc la spécification est la suivante pour le nom du fichier  : 

`FicheSuivi_"IDTabou"_"codexxx"_"NomOperation".pdf`

**Comment by dcottenc** [comment]
Fonctionnalité testée et validée
