### ISSUE TITLE
API - Erreur 500 GET operation/etapes

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#200]
**Description du bug / Describe the bug**

Erreur 500 lors de l'appel des étapes : 
```
Error: Server Error
Response headers
 cache-control: no-cache, no-store, max-age=0, must-revalidate 
 connection: close 
 expires: 0 
 pragma: no-cache 
 strict-transport-security: max-age=31536000; includeSubDomains; preload; 
 vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers 
 x-content-type-options: nosniff, nosniff, nosniff 
 x-frame-options: DENY 
 x-xss-protection: 1; mode=block 
```

https://portail-test.sig.rennesmetropole.fr/tabou2/operations/etapes?asc=true

**Reproduire le bug / To Reproduce**

1. Aller sur le swagger
2. Tester GET [/operations/etapes](https://portail-test.sig.rennesmetropole.fr/tabou2/swagger-ui.html#/operations/operation-api-controller/searchOperationsEtapes)
Liste des étapes par opérations

**Comment by Gaetanbrl** [comment]
@dcottenc je ne sais pas si cette issue fait partie des problèmes remontés ce matin, mais l'API hors V1 et V2 semble en régression sur ce service (et d'autres ?)

**Comment by dcottenc** [comment]
@Gaetanbrl  cette anomalie est liée aux soucis précédents. Elle est corrigée et qualifiée mais non déployée à RM
