### ISSUE TITLE
API - GED Cohérence nom des champs

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#201]
## Description

Lorsqu'on appel la GED et qu'on réceptionne un document nous avons les champs suivants : 
https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/documents?asc=true

```
    {
      "id": "5a3d2963-f283-484b-96ac-72e9878092a8",
      "nom": "test-abc-jdev",
      "libelleTypeDocument": "image",
      "typeMime": "application/pdf",
      "modifUser": "TABOU",
      "modifDate": "25/01/2022 15:41"
   }
```
   
Mais quand on créé un document, le champ `libelleTypeDocument` doit s'appeler `libelle` :
https://portail-test.sig.rennesmetropole.fr/tabou2/swagger-ui.html#/operation-api-controller/addDocument

Alors que la description Swagger affiche un nom de champ différent du champ attendu en paramètre.

![image](https://user-images.githubusercontent.com/16317988/159895630-3d4ac680-a831-4e87-a108-51630aaa288a.png)

La modification PUT d'un document est cependant cohérente avec un nom de champ `libelleTypeDocument`.

**Les noms de champs devraient être cohérents pour éviter des sources d'erreur / bug**

**Comment by Gaetanbrl** [comment]
A noter que le champ POST programmes/document est correct : 
https://portail-test.sig.rennesmetropole.fr/tabou2/swagger-ui.html#/programme-api-controller/addDocument_1

**Comment by dcottenc** [comment]
Correction API testée et validée en Test
