### ISSUE TITLE
GET operation/id - Erreur 500 v2 v1

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#203]
###Description

Une erreur persiste au clic sur certains programmes au sein du plugin Urb@map.

il semblerai que ce soit lié à l'API du GET operation : 

https://portail-test.sig.rennesmetropole.fr/tabou2/v2/operations/280

On a ici deux cas qui provoquent cette erreur : 

1. Le plugin n'utilise pas encore les API avec un path /v2/operation/id et utilise un path simple  (sans vX) /operation/id qui n'existe plus (on attend la qualif pour faire les modifications dans le front - si des tests sont fait sur le plugin, tout ce qui dépend de ce service est logiquement KO)

2. L'API retourne de toute façon une erreur 500 lorsqu'on utilise n'importe quelle version v1 ou v2

### Reproduire

https://portail-test.sig.rennesmetropole.fr/tabou2/v2/operations/280
et
https://portail-test.sig.rennesmetropole.fr/tabou2/v1/operations/280

**Si un changement d'API doit être effectué côté plugin il faut que le service fonctionne et qu'ensuite on adapte le front dans le plugin urb@map.**

**Comment by ThomasBruleOpen** [comment]
Les appels de l'API sont désormais opérationnels. 

Problème de droits sur des tables externes à Tabou qui avaient sautés ...

A noter, au sujet des versionnements : 
- Tout ce qui est accessible via .../V1/... est accessible dans la mention de la version : 
https://portail-test.sig.rennesmetropole.fr/tabou2/v1/operations/280
https://portail-test.sig.rennesmetropole.fr/tabou2/operations/280
Ces deux appels sont identiques

- Tout ce qui est appelé en V2 doit comporter la mention V2

**Comment by Gaetanbrl** [comment]
> Les appels de l'API sont désormais opérationnels.

Testé et validé pour l'appel depuis le plugin.

> Tout ce qui est accessible via .../V1/... est accessible dans la mention de la version 

Ok, donc /v1/operation est égal à /operation, mais /operation et /v1/operation sont différents de /v2/operation.

Je clos.

**Comment by Gaetanbrl** [comment]
Suite à l'issue 209 cette phrase est invalidée : 

> Ces deux appels sont identiques
