### ISSUE TITLE
API - Doublon en base - Aucun contrôle sur les insertions

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#206]
## Description

Lorsqu'on modifie une operation avec l'API `PUT /v2/operations`,
on peut rajouter plusieurs informationsProgramme avec le même id de code (voir etapes en dessous pour + d'infos).

Le front doit contrôler ce type de saisie et bien sur ne jamais envoyer ce type de schéma, mais côté Backend, la sauvegarde en BDD ne devrait pas être possible selon une logique relationnelle.

Idem pour les contributions, ce type de sauvegarde ne devrait jamais être faisable front ET back avec 2x le même type : 

```
  "contributions": [
    {
      "id": 5,
      "typeContribution": {
        "id": 1,
        "code": "CONTRIBUTION_ENJEUX",
        "libelle": "Enjeux",
        "dateInactif": null,
        "createUser": null,
        "createDate": null
      },
      "description": "test KO"
    },
    {
      "id": 4,
      "typeContribution": {
        "id": 1,
        "code": "CONTRIBUTION_ENJEUX",
        "libelle": "Enjeux",
        "dateInactif": null,
        "createUser": null,
        "createDate": null
      },
      "description": "Première contributiond"
    }
  ],
```

> Voir la reproduction pour + d'infos.

## Etapes pour reproduire le bug

1. dans le Swagger, modifier `/v2/operations` sur l'id `517` et rajouter dans informationProgrammation 2x le même code type comme ceci :

```
    {
      "id": 18,
      "typeProgrammation": {
        "id": 2,
        "code": "Activites",
        "libelle": "Type de programmation Activités",
        "dateInactif": null,
        "createUser": "t.brule",
        "createDate": "2022-04-22T14:24:01.000+00:00"
      },
      "description": "test logement pr"
    },
    {
      "id": 27,
      "typeProgrammation": {
        "id": 2,
        "code": "Activites",
        "libelle": "Type de programmation Activités",
        "dateInactif": null,
        "createUser": "t.brule",
        "createDate": "2022-04-22T14:24:01.000+00:00"
      },
      "description": "test logement pro activite"
    },
    {
      "id": 14,
      "typeProgrammation": {
        "id": 2,
        "code": "Activites",
        "libelle": "Type de programmation Activités",
        "dateInactif": null,
        "createUser": "t.brule",
        "createDate": "2022-04-22T14:24:01.000+00:00"
      },
      "description": "test "
    }
```
2. Envoyer la requête PUT
3. Appeler en GET l'operation 517
4. Voir que la modification a bien été sauvegardée avec plusieurs fois le même code typeProgrammation
5. Faire de même pour contribution

## Comportement attendu

1. Ne jamais voir ce doublon.
2. Avoir une erreur lors de l'appel PUT

**Comment by dcottenc** [comment]
Il y a bien des contrôles lors de l'insertion mais effectivement le cas d'un doublon dans un même appel n'est pas effectué.

Ticket Open (CDCRM-1004) en cours pour la correction de cette anomalie

**Comment by dcottenc** [comment]
Fermé car suivi dans JiRa Open (en cours de recette mais à priori ok)
