### ISSUE TITLE
API - MAJ des infos user, date avec  PUT /v2/operation

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#207]
## Description

Lorsqu'une opération est modifiée avec le service `PUT /v2/operations` on voit que les champs type date et user pour les types contribution / programmation ne sont pas renseignés par le backend.

Jusque là ce n'est pas le front qui gère ces informations et la saisie d'un type contribution / type programmation se réalise à partir de cette base de schéma : 

```
informationProgrammation < array >: [{
    description < string >: "test",
    typeProgrammation < object >: {
        id < integer: 1
    }
}]
```

On obtient alors ensuite des nouveaux champs rajoutés par le service backend (avec un nouvel ID notamment): 

```
"informationsProgrammation": [{
    "id": 42,
    "typeProgrammation": {
        "id": 2,
        "code": "Activites",
        "libelle": "Type de programmation Activités",
        "dateInactif": null,
        "createUser": "t.brule",
        "createDate": "2022-04-22T14:24:01.000+00:00"
    },
    "description": ""
}]
```

### Problème

Les champs dateInactif, createUser, createDate ne sont cependant pas mis à jour par le backend.

**Comment by dcottenc** [comment]
Je pense qu'il y a une confusion. 
Les opérations ont un createUser, createDate, modifUser, modifDate .Ils sont mis à jour lors par PUT /v2/operations
Les types de programmation, contribution... ont également ces champs (maj manuel lors de l'ajout d'un type). 
Par contre, ces champs n'existent pas pour l'association operations/contribution par exemple.

C'est le cas dans l'exemple donné
```
"informationsProgrammation": [{
    "id": 42,
    "typeProgrammation": {
        "id": 2,
        "code": "Activites",
        "libelle": "Type de programmation Activités",
        "dateInactif": null,
        "createUser": "t.brule",
        "createDate": "2022-04-22T14:24:01.000+00:00"
    },
    "description": ""
}]
```

Si on avait ajouté ces champs on aurait (non demandé) : 
```
"informationsProgrammation": [{
    "id": 42,
    "typeProgrammation": {
        "id": 2,
        "code": "Activites",
        "libelle": "Type de programmation Activités",
        "dateInactif": null,
        "createUser": "t.brule",
        "createDate": "2022-04-22T14:24:01.000+00:00"
    },
    "description": "";
    "createUser": "d.cottencin",
     "createDate": "2022-06-17T14:24:01.000+00:00"
}]
```

**Comment by dcottenc** [comment]
C'est ok pour toi ? Peut-on clore ?

**Comment by Gaetanbrl** [comment]
si c'est ok pour toi alors oui

**Comment by dcottenc** [comment]
Ok pour moi
