### ISSUE TITLE
API - Vocation Habitat - champ nbLogementsPrevu non modifiable

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#208]
## Description

La modification du champ `nbLogementsPrevu` ne fonctionne pas.

## Etapes pour reproduire le bug

1. Aller sur le swagger sur le service `PUT /v2/operations`
2. Faire un appel `GET /v2/operations` sur l'opération id 517
3. Voir que la valeur du champ `nbLogementsPrevu`  est `null`
4. Pour l'opération id 517, modifier la valeur du champ `nbLogementsPrevu` par le nombre entier `25`
5. Voir que l'API retourne un code 200 et une valeur de nbLogementPrevu toujours null ==> **Test KO**

`"nbLogementsPrevu": null,`

6. Exécuter la requête
7. Faire un appel `GET /v2/operations` sur l'opération id 517
8. Voir que la valeur est toujours à `null` ==> **Test KO**

`"nbLogementsPrevu": null,`

## Comportement attendu

La modification de la valeur du champ doit être prise.

**Comment by dcottenc** [comment]
Ticket en cours de traitement (ref. : OPEN CDCRM-1018)

**Comment by dcottenc** [comment]
Je propose de clore ce ticket. Il est pris en compte coté OPEN et je viens de recevoir la correction.

**Comment by Gaetanbrl** [comment]
Si testé dans le plugin mapstore alors on peut clore oui.
