### ISSUE TITLE
Régression(s) - v1/operation et /operation diffèrent

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#209]
## Description

Dans le gros bazar imposé par le backend avec une gestion de version complexe et qui n'est pas utile pour urb@map, la recherche d'une operation par nom ne fonctionne qu'avec la /v1/operation.

L'ajout d'un programme ne fonctionne donc plus car on recherche une operation par le nom pour l'opération parente avec l'API /operation (et pas /v1/operation vu que ca ne devait pas avoir d'impact etc...) .

Il a pourtant été confirmé [ICI](https://github.com/sigrennesmetropole/geor_tabou2_front/issues/203#issuecomment-1095252769) les semaines passées : 

>A noter, au sujet des versionnements :

>Tout ce qui est accessible via .../V1/... est accessible dans la mention de la version :
>https://portail-test.sig.rennesmetropole.fr/tabou2/v1/operations/280
>https://portail-test.sig.rennesmetropole.fr/tabou2/operations/280
>Ces deux appels sont identiques

>Tout ce qui est appelé en V2 doit comporter la mention V2

Cette modification de version ne semble pas avoir pris en compte toutes les régressions possibles.

## Question

Est-ce possible de tout rajouter dans une seule et unique v2 et non pas  dans 3 apis ?

**Comment by ThomasBruleOpen** [comment]
Bonjour Gaetan, 

Je n'ai pas ton historique sur le projet, je n'ai donc sans doute pas assez d'éléments pour juger, néanmoins, il me paraitrait étonnant qu'une gestion de versions ait été mise en place si elle n'avait pas été nécessaire ...

Pour le reste, peux tu préciser ce qui ne fonctionne pas, exactement ?
J'ai fait ces deux tests : 
https://portail-test.sig.rennesmetropole.fr/tabou2/v1/operations?nom=H%C3%B4tel%20Dieu&asc=true
https://portail-test.sig.rennesmetropole.fr/tabou2/operations?nom=H%C3%B4tel%20Dieu&asc=true

Et les deux me renvoient strictement la même réponse.

**Comment by Gaetanbrl** [comment]
OK, je viens de comprendre.

On avait un code qui faisait une recherche de caractère sur `text*` alors qu'on recherche `*text*`.
Aussi, les services ont été virés du Swagger mais sont pourtant fonctionnels... ca porte à confusion car je me base sur ca pour savoir quelle version utiliser... 

Ce serait possible d'afficher tous les services disponibles pour chaque version @ThomasBruleOpen ?
