### ISSUE TITLE
GED - Instabilité interface GED via API

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#211]
## Description

Lorsqu'on utilise l'UI de la GED, on se rend compte de certaines latences qui sont, je pense, dû au temps de répons entre l'API Alfresco et l'API Tabou.

On a également des problèmes lors de l'ajout ou suppression d'un document, c'est notamment le cas lorsqu'on clique sur la page 2 mais qu'on a supprimé assez de documents pour n'avoir qu'une page. On perd alors tout le tableau qui ne s'affiche plus.

## Etapes pour reproduire le bug

Etapes à suivre pour reproduire votre problème du type : 

1.Ouvrir le plugin Tabou
2. CLiquer sur Baud Chardonet
3. Ouvrir les documents
4. Ajouter assez de documents pour en avoir sur 2 pages
5. Supprimer assez de documents ligne par ligne (avec l'îcone poubelle) pour n'avoir plus qu'une page
6. Voir que s'il ne reste qu'une page, le bouton "2" est toujours affiché
7. Voir que si on clique sur "2" le tableau ne s'affiche plus car il n'y a aucun document sur la page 2

## Comportement attendu

Avoir le bon nombre de page.

**Comment by Gaetanbrl** [comment]
Il y a deux retours que je ne comprends pas lors de la suppression d'un document dans un cas précis décris dans la section qui détaille les étapes en dessous.

Voici les deux retours : 

1. je réceptionne 4 documents pour la page 1 (start=0) alors qu'on compte 6 documents au total

tabou2/v2/operations/100/documents?start=0&resultsNumber=5&asc=true&nom=**

Retourne ...

![image](https://user-images.githubusercontent.com/16317988/166472626-6c3cd63e-1442-4e6a-9b67-1447c721866d.png)

2. Pour comparer, j'appel en cascade après l'appel précédent TOUS les documents de cette même opération mais sans la pagination.

![image](https://user-images.githubusercontent.com/16317988/166473235-17b231e5-5c78-454a-98e6-699d61a5b669.png)

Je pense que c'est lié à l'issue #193.

**Comment by dcottenc** [comment]
Analyse en cours : la DSI va désactiver l'indexation du contenu de documents pour réduire la latence

**Comment by dcottenc** [comment]
Cette anomalie ne concerne pas le front.
Elle est à traiter au niveau de la GED par la DSI RM.
