### ISSUE TITLE
API - Certaines recherches de document GED par nom ne retournent rien

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#212]
## Description

Le document `Rennes_Métropole.svg-1.png` n'est pas retrouvé par l'appel du service /v2/operation : 

https://portail-test.sig.rennesmetropole.fr/tabou2/v2/operations/100/documents?start=0&resultsNumber=5&asc=true&nom=*Rennes*

Le doucment `testjdev `est par contre bien retrouvé : 

https://portail-test.sig.rennesmetropole.fr/tabou2/v1/operations/100/documents?start=0&resultsNumber=5&asc=true&nom=*test*

## Etapes pour reproduire le bug

Etapes à suivre pour reproduire votre problème du type : 

1. Aller dans le swagger
2. Rechercher pour l'opération 100 le nom "Renne"
3. Voir qu'il n'y a aucun résultat
4. Appeler tous les documents pour cette opération et voir qu'il existe pourtant plusieurs documents qui commencent par `Rennes`

## Comportement attendu

Retrouver tous les documents recherchés.

**Comment by dcottenc** [comment]
Ticket Open (CDCRM-963) en cours pour la correction de cette anomalie

**Comment by dcottenc** [comment]
Ticket OPEN toujours en analyse coté OPEN (non reproduit en qualification, config Alfresco à voir)

**Comment by dcottenc** [comment]
Concerne le back ou l'API Alfresco. Corrigée
