### ISSUE TITLE
[Filtre] Zonage PLUi - Filtre non opérationnel

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#220]
## Description

Lors de l'utilisation du filtre avec le critère Zonage PLUi, le filtre retourne 0 entité trouvée.

## Etapes pour reproduire le bug

1. Ouvrir le plugin Urb@map sur l'onglet Filtrer
2. Sélectionner le critère "UB1h" dans la liste des zonages PLUi
=> Constater l'affichage d'un avertissement "aucun résultat"
3. Cliquer sur le bouton Appliquer
=> le bouton Appliquer ne permet pas de réaliser le filtre (rien ne se passe)

## Comportement attendu

Les trois couches OA, SA et PA doivent être filtrées avec la requête spatiale intersect sur les emprises des zonages PLUi avec l'étiquette "UB1h"

## Média / captures d'écran

![image](https://user-images.githubusercontent.com/76009802/173546877-31e28326-1266-49bf-bf79-ef0290eb6e33.png)

## Environnement

Portail Test et production RM

## Informations complémentaires

En regardant les requêtes transmises à Geoserver, les trois retournent un résultat à 0. Le CQL Filter est curieux car les valeurs criteres zonage apparaissent avec deux ' à suivre: 
`CQL_FILTER=(INTERSECTS(shape,collectGeometries(queryCollection('ladm_terri:commune_emprise', 'shape','("code_insee" = 35238)')))) AND (INTERSECTS(shape,collectGeometries(queryCollection('urba_docs_plui:plui_plan_zonage_simplifie', 'shape','("etiquette" = ''UB1h'')')`

**Comment by Gaetanbrl** [comment]
> Le CQL Filter est curieux car les valeurs criteres zonage apparaissent avec deux ' à suivre:

Il me semble que c'est une syntaxe courante pour intégrer des caractères de type String parfois mal interprétés dans un filtre CQL. A vérifier avec un type string (ce qui n'est pas le cas avec le code_insee qui est un Number).

**Comment by dcottenc** [comment]
Anomalie annulée => Demande pour futur MCO

Il s'avère que la source du zonage est différent pour l'API et le filtre. 
En l'état, on en peut pas savoir si cela n'a jamais marché ou si la couche a été modifiée

**Comment by Gaetanbrl** [comment]
> Il s'avère que la source du zonage est différent pour l'API et le filtre.

Donc pas forcément de synchronisation entre les données en base et celles dans la couche c'est ca ?
