### ISSUE TITLE
MCO Front - Modifier programme - Fonctionnement modifier/supprimer Date DAACT KO

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#221]
## Description

Le champs Date Daact de la fiche Programme est difficilement modifiable (sans utiliser le calendrier) et la suppression ne fonctionne pas.
Aussi, la date semble inférieure d'une journée par rapport à la date fournie par le WS.
Exemple ci-dessous dans `information complémentaires`.

## Etapes pour reproduire le bug

1. Ouvrir Urb@map
2. Ouvrir le plugin Urb@map
3. Cliquer sur un programme
4. Dans la fiche du programme/Instruction Droit des Sols, saisir une date dans le champ Date DAACT
5. Enregistrer => la date DAACT s'enregistre correctement
6. Modifier la date DAACT => la saisie manuelle d'une date ne fonctionne pas, le curseur se déplace à la fin pendant la saisie 
7. Supprimer la date DAACT
8. Enregistrer => la date DAACT est toujours présente

## Comportement attendu

Le champ DAACT doit pourvoir être modifié manuellement et surtout pouvoir être supprimé.

## Environnement

Portail Test RM

## Informations complémentaires

Lors de l'étape 8 ci-dessus dans le PUT le champ datDatePrevu devrait être à Null mais il contient l'ancienne valeur.
Autre remarque : pourquoi la valeur dans la requête est inferieure d'une journée ? La valeur affichée pour la date DAACT est le 01/06/2022 alors que l'appel contient le 31/05/2022 ?

`{"id":150,"etape":{"id":5,"libelle":"En étude","code":"EN_ETUDE_PUBLIC","type":"NORMAL","mode":"PUBLIC"},"operationId":100,"diffusionRestreinte":false,"code":"P-150","nom":"O1","programme":null,"description":null,"idEmprise":6026,"attributionFonciereAnnee":0,"attributionDate":null,"commercialisationDate":null,"adsDate":null,"livraisonDate":null,"docDate":null,"datDate":null,"adsDatePrevu":null,"docDatePrevu":null,"datDatePrevu":"2022-05-31T22:00:00.000+00:00","clotureDate":null,"logementsTotal":0,"logementsAccessMaitrise":null,"logementsLocatifRegulePrive":null,"logementsLocatifReguleHLM":null,"logementsAccessAide":null,"logementsLocatifAide":null,"logementsAccessAidePrevu":0,"logementsLocatifAidePrevu":0,"logementsLocatifRegulePrivePrevu":0,"logementsLocatifReguleHlmPrevu":0,"logementsAccessMaitrisePrevu":0,"logementsAccessLibrePrevu":0,"numAds":null,"createUser":"d.cottencin","createDate":"2021-11-12T09:01:11.551+00:00","modifUser":"d.cottencin","modifDate":"2022-06-16T07:26:07.940+00:00"}`

**Comment by Gaetanbrl** [comment]
C'est noté @dcottenc

**Comment by Gaetanbrl** [comment]
> Lors de l'étape 8 ci-dessus dans le PUT le champ datDatePrevu devrait être à Null mais il contient l'ancienne valeur.

On parle ici du champ DACCT ou datDatePrevu ?


> Autre remarque : pourquoi la valeur dans la requête est inferieure d'une journée ? La valeur affichée pour la date DAACT est le 01/06/2022 alors que l'appel contient le 31/05/2022 ?

Aucune idée. Je regarde.

**Comment by Gaetanbrl** [comment]
Ce bug n'est pas reproductible en local. 
Tout fonctionne bien dans mon environnement de développement, saisie + suppression + sauvegarde (étapes citées).

Le plugin est à jour sur la PF de test (déployé le 22/07/2022) Je regarde pourquoi une fois buildé on a pas le même comportement.

**Comment by dcottenc** [comment]
> On parle ici du champ DACCT ou datDatePrevu ?

Ce sont les mêmes : DAACT est le libellé du Front et datdateprevu l'attribut de l'API

> Ce bug n'est pas reproductible en local.

Les appels fournis dans la description ont été capturés à la sortie du plugin (dans la console Web)

**Comment by Gaetanbrl** [comment]
> Aucune idée. Je regarde, mais je pense que c'est une question de zone de temps (time zone) avec la librairie Js native Date().

Je confirme, cela provient de la librairie : 

`new Date("2022-05-31T22:00:00.000+00:00").toLocaleString()
`
... retourne : 

`'01/06/2022 00:00:00'`

**Comment by Gaetanbrl** [comment]
Correctif poussé et tests à réaliser : 

**Cas 1**
- [ ] Modifier la date via le calendrier
- [ ] Sauvegarder la date modifiée via le calendrier
- [ ] Voir la date dans le swagger

**Cas 2**
- [ ] Modifier la date manuellement
- [ ] Sauvegarder la date modifiée via le calendrier
- [ ] Voir la date dans le swagger

**Cas 3**
- [ ] Modifier la date manuellement
- [ ] Sauvegarder la date modifiée via le calendrier
- [ ] Voir la date dans le swagger
- [ ] Supprimer la date
- [ ] Sauvegarder
- [ ] Voir que la date est null

**Résultat :**

**Comment by dcottenc** [comment]
Testé en PF Test

Cas 1 => OK
Cas 2 => toujours des soucis pour saisir une date manuellement, le curseur va à la fin de la date lors de la saisie des premiers caractères (tests effectués avec Firefox)
Cas 3 => Ok

**Comment by Gaetanbrl** [comment]
> Cas 2 => toujours des soucis pour saisir une date manuellement, le curseur va à la fin de la date lors de la saisie des premiers caractères (tests effectués avec Firefox)

OK je regarde.

**Comment by dcottenc** [comment]
**Informations complémentaires**
A noter que si l'utilisateur commence à saisir manuellement une date celle-ci s'efface automatiquement au bout de quelques secondes (1 saisir un début de date ex : "20/", 2 attendre et constater que les caractères s'effacent automatiquement (sous Fiefox et Chrome)).

Est-il possible de sélectionner toute la date quand l'utilisateur clique dans la zone de saisie afin d'éviter à l'utilisateur de supprimer le contenu du champ avant de le modifier ?

**Comment by Gaetanbrl** [comment]
> Est-il possible de sélectionner toute la date quand l'utilisateur clique dans la zone de saisie afin d'éviter à l'utilisateur de supprimer le contenu du champ avant de le modifier ?

ca me semble être une rustine sur un soucis de gestion d'état ==> pour moi c'est à revoir

**Comment by dcottenc** [comment]
> ca me semble être une rustine sur un soucis de gestion d'état ==> pour moi c'est à revoir

Cela me semble être plutôt qqchose que l'on voit souvent dans les saisies Web de date. Mais oui peut être que la correction qui corrigera l'effacement auto suffira.

**Comment by Gaetanbrl** [comment]
@dcottenc Doublon #241 ==> A tester sur PF de test depuis dernier déploiement

**Comment by dcottenc** [comment]
> @dcottenc Doublon https://github.com/sigrennesmetropole/geor_tabou2_front/issues/241 ==> A tester sur PF de test depuis dernier déploiement

Les anos sont différentes.
Cette correction est testée et validée en PF de test (test avec saisie manuelle de valeurs ok ou ko=>null), la 241 non
