### ISSUE TITLE
VA - Anomalie - Fiche OA/PA / Journal de bord - Retour après enregistrement KO

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#223]
## Description

Dans la modale "Journal de bord", le type existant ne s'affiche plus en modification

## Etapes pour reproduire le bug

1. Ouvrir le plugin Tabou et sélectionner une OA ou un PA
2. Ouvrir le journal de bord
3. Cliquer sur Modifier un des documents => la ligne passe en mode saisie
4. cliquer sur Enregistrer => la ligne reste en mode saisie

## Comportement attendu

La ligne enregistrée doit repasser en lecture seule avec une actualisation des données selon les modifications effectuées

## Média / captures d'écran

Avant clic sur Enregistrer
![image](https://user-images.githubusercontent.com/76009802/174068157-742ae8ed-1a08-4f9a-abaf-67045d033bc7.png)

Apres clic
![image](https://user-images.githubusercontent.com/76009802/174068712-80d5bca4-8434-446a-a192-b6c926e1370d.png)

## Environnement

Portail test RM (VA)

**Comment by Gaetanbrl** [comment]
@dcottenc corrigé, déployé et à tester sur PF de test.

**Comment by dcottenc** [comment]
Testée et validée en PF de Test
