### ISSUE TITLE
VA - Anomalie - Edition - Associer un tiers - Gestion Désactiver KO

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#225]
## Description

Lorsque l'on clique sur désactiver, l'affichage n'est pas mis à jour (l'action est bien effectuée en bdd). Il faut recliquer sur l'entité puis rouvrir la fenêtre tiers pour voir le résultat.

## Etapes pour reproduire le bug

1. Ouvrir le plugin Urb@map
2. Cliquer sur une entité OA ou PA
3. Puis cliquer sur le bouton Tiers
4. Cliquer sur le bouton désactiver d'un tiers => Rien ne se passe 

## Comportement attendu

Le tiers desactivé doit avoir la colonne Actif avec une case à cocher vide dès que l'on clique sur le bouton desactivé

## Média / captures d'écran

Avant clic
![image](https://user-images.githubusercontent.com/76009802/174094083-9e0e1179-ba59-4b72-bf01-a32f206fa2b0.png)

Apres clic : aucun changement

## Environnement

Portail RM Test (VA)

**Comment by Gaetanbrl** [comment]
Livraison sur la PF test en cours.

**Comment by Gaetanbrl** [comment]
Livré sur PF de test et dispo en ligne @dcottenc

**Comment by dcottenc** [comment]
Testé et validé (Portail test VA). Merci
