### ISSUE TITLE
VA - Fiche OA & PA - Afficher les documents - Tri et filtre partiellement KO

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#226]
## Description

On constate les anomalies suivantes sur les tris et filtres :

- le filtre sur la date ne fonctionne pas
- si la liste est paginée alors les tri et filtres s'appliquent uniquement sur la page en cours plutôt que sur la totalité des documents.

## Etapes pour reproduire le bug

1. Ouvrir le plugin Tabou
2. Cliquer sur une entité OA ou PA (avec plus de 5 documents)
3. Cas 1 : Utiliser les filtres et les tris et voir qu'ils ne s'appliquent que sur les documents de la page en cours
4. Cas 2 : Saisir une date dans le filtre et voir qu'à partir du premier / il n'y a plus de résultat

## Média / captures d'écran

Cas 1 : 

avec la page 1 et 2 suivante
![image](https://user-images.githubusercontent.com/76009802/174097432-08a89a70-cc0e-44f5-b9db-4b04fd587d89.png)

![image](https://user-images.githubusercontent.com/76009802/174097262-39396731-52f2-498a-a354-b69a2ebc4e86.png)

Le filtre Plan de masse devrait retourner deux documents (ici un seul)
![image](https://user-images.githubusercontent.com/76009802/174097680-767f8104-bce3-44de-ae36-25e0a6aa84c7.png)

Pareil pour le tri (on a un seul plan de masse au lieu de 2)
![image](https://user-images.githubusercontent.com/76009802/174097947-f06d257d-7c9d-4a70-aa73-339fc7a93647.png)

Cas 2 : 
Le filtre '05/' ne retourne aucun resultat alors qu'il existe des documents à cette date
![image](https://user-images.githubusercontent.com/76009802/174098278-31d1fb8d-8bcc-430e-ba81-637a630e9771.png)

## Environnement

Portail Test RM (VA)

**Comment by Gaetanbrl** [comment]
> Le filtre '05/' ne retourne aucun resultat alors qu'il existe des documents à cette date

Je ne reproduis pas.
![filtre_226](https://user-images.githubusercontent.com/16317988/174762034-b7c446a1-f094-4fd9-a950-ce3af89f14e8.gif)

Voir la capture ci-dessous :

**Comment by Gaetanbrl** [comment]
Je voudrais faire un rappel sur ce composant et les différences avec le tableau d'attributs :

1. La source

On utilise l'API pour récupérer les documents. Le problème étant qu'on doit utiliser la pagination car l'API est limitée dans le nombre de réponses (voir les issues liées avec les filtres de recherche).
La différence avec MapStore2, c'est que la table des attributs MapStore2 utilise un flux WFS sans limite (le scroll charge les éléments supplémentaires). Donc une API sans contraites.

2. Le filtre

Du faite de l'API, on pagine, et donc le composant va rechercher dans tous les résultats chargés dans le tableau, donc uniquement ceux de la pagination.

3. Evolutions possibles

==> Solution A) 
Avoir une API qui fournis tous les résultats sans limite ==> @dcottenc ?

==> Solution B)
Avoir un filtre de recherche avancé (déjà proposé oralement) comme pour le champ NOM sous le tableau pour les autres champs.

**Comment by dcottenc** [comment]
@Gaetanbrl L'objectif est que les utilisateurs ne soient pas perdus et pour cela le fonctionnement des tableaux doit être homogène.
Encore une fois, je n'ai pas souvenir d'avoir évoqué un tri/filtre uniquement sur la page en cours et encore moins pour la case Rechercher Nom
Je te propose que j'évoque tes solutions demain avec la MOA et je te fais un retour.

**Comment by dcottenc** [comment]
@Gaetanbrl  Peux-tu m'indiquer si c'est le composant qui gère la pagination (il charge tous les résultats et gère les pages ) ou si c'est toi qui appelle l'API quand on clique sur une autre page (pour avoir les résultats pour une page) ?

**Comment by Gaetanbrl** [comment]
> Peux-tu m'indiquer si c'est le composant qui gère la pagination
Le composant React-data-grid est seulement un tableau qui prend des données et les affiche sans distinction (sauf spécificités).
https://adazzle.github.io/react-data-grid/#/common-features

La pagination est gérée par le front.
Le nombre de page est défini selon le nombre de résultats / le nombre  à afficher par page (ex: 5).
Par défaut, la page 1 s'affiche en utilisant les paramètres de pagination spécifié / prévus par l'API.
Au retour, on donne au composant (tableau) les données issues du retour du WS.

**Comment by Gaetanbrl** [comment]
@dcottenc **Remplacement en fin de réalisation pour avoir un composant similaire au tableau des attributs MS2 qui permet de charger :**
- plus d'éléments au scroll via le système de pagination (page suivante s'ajoute à la précédente avec le scroll)
- La recherche lors de la saisie d'un filtre utilise l'API et recharge l'ensemble du tableau ==> Ne peux fonctionner avec les dates car l'API ne permet pas la recherche par date

**RAF:**
- Afficher un message pendant le chargement
- Tests

**Comment by Gaetanbrl** [comment]
@dcottenc d'après les cas de test de cette issue :

Ouvrir le plugin Tabou
1. Cliquer sur une entité OA ou PA (avec plus de 5 documents)

Refresh des autres documents au scroll si le nombre d'éléments dans le tableau est inférieur au résultat total.
**Dans la configuration du plugin, il est conseillé d'avoir une une valeur < = à 10.**

2. Cas 1 : Utiliser les filtres et les tris et voir qu'ils ne s'appliquent que sur les documents de la page en cours

Ce n'est normalement plus le cas.

Testé avec ces étapes : 
```
 - Limiter le paramètre "documents" à 2
 - Charger le contexte Tabou
 - Afficher les documents de l'opération 100 Baud Chardonnet
 - Voir qu'il n'y a pas de documents avec le type "Schéma directeu"
 - Saisir dans le filtre du champ "Type" les caractère "Sche"
 - Voir qu'un document non présent dans le tableau s'affiche
```
**Résultat OK**
![image](https://user-images.githubusercontent.com/16317988/181203466-e20f08d4-e7ad-4d09-8cdb-8c90805d3421.png)

3. Cas 2 : Saisir une date dans le filtre et voir qu'à partir du premier / il n'y a plus de résultat

Nativement, le composant GRID ne semble pas accepter ce caractère.
Cependant, les filtres sur les champs Type, Nom et Type Mime  utilisent l'API pour recharger le tableau lors de la saisie d'un filtre.
Il conviendra d'utiliser ce même fonctionnement pour la recherche par Date, et donc d'avoir un web service disponible.

**En attendant, le filtre actuel fonctionne uniquement sur les données chargées dans le tableau et ne pourra fonctionner avec le caractère "/".**

**Comment by Gaetanbrl** [comment]
@dcottenc En attente de test et retour.

**Comment by dcottenc** [comment]
Testé et validé en PF de test
Remarque :  est-il possible d'avoir un ascenseur à droite qui permet d'identifier que la liste de documents  est plus longue que celle affichée ?

Le filtre Date pour l'API sera ajouté dans le cadre d'une évolution

**Comment by Gaetanbrl** [comment]
> est-il possible d'avoir un ascenseur à droite qui permet d'identifier que la liste de documents est plus longue que celle affichée ?

Probablement.

**Comment by dcottenc** [comment]
L'ascenseur (à privilégier) ou une pagination est à afficher car on ne peut pas voir tous les documents de la liste à partir d'un certain nombre

**Comment by Gaetanbrl** [comment]
> L'ascenseur (à privilégier) ou une pagination est à afficher car on ne peut pas voir tous les documents de la liste à partir d'un certain nombre

A placer dans une autre issue

**Comment by Gaetanbrl** [comment]
Je ferme, le scroll a été passé sur une autre issue.
