### ISSUE TITLE
API - PUT OA suppression champ entiteReferente impossible

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#228]
## Description

> Tests réalisés via appels API dans Tabou et aussi réalisés via le swagger

Les spécifications de l'issue {174 indique que le champ `entiteReferente` n'est pas obligatoire.

Lorsque je sauvegarder une OA avec une entité référente de cette structure dans l'opération pas de soucis, on garde la valeur en base  : 

`entiteReferente: {id: 1, code: "SAM", libelle: "SAm", dateInactif: null, createUser: "d.cottencin", createDate: null}`

Si on supprime la valeur du champ, la valeur vide ("") n'est pas acceptée par l'API et renvoi une erreur 500 : 

`entiteReferente: ""`

Si on met une valeur `null `(différente d'une chaine de caractères vide `""`),  alors on l'API ne semble pas sauvegarder la modification et on retrouve la valeur précédente si on appel l'opération une nouvelle fois via le web service.

## Etapes pour reproduire le bug

Etapes à suivre pour reproduire votre problème du type : 

1. Ouvrir le swagger
2. Appeler l'OA avec l'id 100
https://portail-test.sig.rennesmetropole.fr/tabou2/v2/operations/100

3. Remplacer la valeur du champ entiteReferente à `null` et sauvegarder
`entiteReferente: null`

4. Appeler à nouveau l'OA Baud Chardonnet et vérifier que la valeur est vide ==> KO

https://portail-test.sig.rennesmetropole.fr/tabou2/v2/operations/100

On retrouve la valeur précédente et non une valeur nulle : 

```
  "entiteReferente": {
    "id": 1,
    "code": "SAM",
    "libelle": "SAm",
    "dateInactif": null,
    "createUser": "d.cottencin",
    "createDate": null
  },
```

5. Remplacer la valeur du champ entiteReferente à `""` et sauvegarder
6. Voir une erreur 500 ==> KO

## Comportement attendu

Si `null `ou vide, on ne doit pas avoir d'erreur (dans un des cas au moins à spécifier) et la valeur pour le champ doit être vide.
On ne doit pas récupérer la valeur précédente.

**Comment by dcottenc** [comment]
Le périmètre de l'anomalie est plus vaste que l'attribut service Réfèrent, elle concerne tous les attributs dont l'enregistrement s'effectue avec un id. 

La correction de l'ano Open n'est pas validée. A clore car le suivi s'effectue dans le Jira Open
