### ISSUE TITLE
API - PUT operation - decimal surfaceTotale modifiée

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#229]
## Description

L'envoi de valeurs avec des décimales ne semble pas acceptée par l'API avec le champ surfaceTotale.
La valeur avec une décimale est arrondie à la valeur supérieure : 

```
0.5 -> 1
1.7 -> 2
```

## Etapes pour reproduire le bug

Etapes à suivre pour reproduire votre problème du type : 

1. Aller Swagger 

2. Ouvrir` GET operation/id` pour récupérer le JSON de l'entité SA avec id 404 à modifier
https://portail-test.sig.rennesmetropole.fr/tabou2/v2/operations/404

3. Voir que le champ surfaceRealisee a bien une valeur 0.5
==> On voit que le champ "surfaceRealisee": 0.5

4. Ouvrir le service PUT operation

5. Coller le JSON de l'entité SA `id 404`

6. Saisir la valeur `0.5` pour le champ `surfaceTotale`

` "surfaceTotale": 0.5`

7. Envoyer la requête

8. Appeler l'entité via le WS GET et voir que la valeur est à `1` et non `0.5`
https://portail-test.sig.rennesmetropole.fr/tabou2/v2/operations/404

` "surfaceTotale": 1,`

## Comportement attendu

La valeur saisie doit rester identique et ne doit pas être modifiée.

Les specs de l'issue #70 précisent que cette valeur est de type Real : 

<html>
<body>

Surface totale | Real | Champ |   |   | /operations/{operationId} | surfaceTotale
-- | -- | -- | -- | -- | -- | --

</body>
</html>

**Comment by dcottenc** [comment]
Anomalie suivie dans le JiRa Open (1034)
