### ISSUE TITLE
API BUG - PUT operation v2 avec amenageur

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#230]
Ref. #174 

@dcottenc lorsque j'envoi les infos aménageurs j'ai une erreur de l'API.

PUT http://localhost:8081/tabou2/v2/operations

Voici ce que j'envoi : 

```
	"amenageurs": [{
		"nom": "test nom",
		"typeAmenageur": {
			"id": 1,
			"code": "COMMUNE",
			"libelle": "Commune",
			"dateInactif": null,
			"createUser": "d.cottencin",
			"createDate": null
		}
	}],
```

Voici ce qui est attendu : 

```
  "amenageurs": [
    {
      "id": 0,
      "nom": "string",
      "typeAmenageur": {
        "code": "string",
        "createDate": "2022-07-20T16:11:24.976Z",
        "createUser": "string",
        "dateInactif": "2022-07-20T16:11:24.976Z",
        "id": 0,
        "libelle": "string"
      }
    }
  ],
```

Seul l'id est absent mais en même temps je ne saurai pas quoi mettre comme valeur qui devrait être automatiquement remplie par l'API...

Voici l'erreur retournée (peu parlante...) : 

`{"status":"BAD_REQUEST","message":"ConstraintViolationException : la requête ne peut être exécutée","errors":["ERROR: null value in column \"id_operation\" violates not-null constraint\n  Détail : Failing row contains (3, null, 1, test nom)."]}`

**Comment by Gaetanbrl** [comment]
Idem avec un nom saisi pour un type Privé  : 
`
{"status":"BAD_REQUEST","message":"ConstraintViolationException : la requête ne peut être exécutée","errors":["ERROR: null value in column \"id_operation\" violates not-null constraint\n  Détail : Failing row contains (4, null, 4, test nom privé)."]}`

**Comment by dcottenc** [comment]
Testée et validée en PF de test
