### ISSUE TITLE
APU - Types fonciers et types financements vides

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#231]
## Description

Les WS types foncier et types financement ne retournent rien.

https://portail-test.sig.rennesmetropole.fr/tabou2/types-fonciers?asc=true

```
{
  "elements": [],
  "totalElements": 0
}
```

https://portail-test.sig.rennesmetropole.fr/tabou2/types-financements-operations?asc=true

```
{
  "elements": [],
  "totalElements": 0
}
```

Avant la migration de la base (récente), des valeurs étaient retournée par le WS type foncier.

Des valeurs me permettront de tester le fonctionnement attendu par l'issue #174.

**Comment by dcottenc** [comment]
> Les WS types foncier et types financement ne retournent rien.

Les deux tables ont été initialisées

**Comment by Gaetanbrl** [comment]
le type foncier ne retourne toujours rien ?

https://portail-test.sig.rennesmetropole.fr/tabou2/types-fonciers?asc=true

**Comment by Gaetanbrl** [comment]
Ok pour pour le type financement merci
https://portail-test.sig.rennesmetropole.fr/tabou2/types-financements-operations?asc=true

**Comment by dcottenc** [comment]
> le type foncier ne retourne toujours rien ?

C'est ok maintenant

**Comment by Gaetanbrl** [comment]
Pour info, régression en cours de réparation sur le front car les code ont changés pour le type foncier : 

avant c'était FONCIER_PUBLIC maintenant c'est PUBLIQUE (idem pour privé).
