### ISSUE TITLE
Front - Fiche info PA ne fonctionne plus

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#232]
## Description
La fiche Info des PA n'affiche plus le contenu des blocs.

Question : lié à la migration prod -> Test ?

**Comment by dcottenc** [comment]
> La fiche Info des PA n'affiche plus le contenu des blocs.

Tu parles bien de l'impression de la fiche PA ?
Si oui, tu as l'impression qu'il n'y a rien mais c'est uniquement lié au fait que les saisies en prod sont pratiquement nulles. Je viens de faire le test sur le programme N de Baud et les infos que j'ai saisies sont bien présentes dans l'impression.

**Comment by Gaetanbrl** [comment]
non je parle des blocs (accordéons) pour les PA j'ai plus rien

**Comment by Gaetanbrl** [comment]
build et déploiement correctif en cours

**Comment by Gaetanbrl** [comment]
Corrigé, visible sur PF test
