### ISSUE TITLE
API BUG - PUT operation v2 avec type financement operation

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#233]
Ref. #174 

Idem que issue #230 .

@dcottenc lorsque j'envoi les infos aménageurs j'ai une erreur de l'API.

PUT http://localhost:8081/tabou2/v2/operations

Voici ce que j'envoi : 

```
    "financements": [{
        "typeFinancement": {
            "id": 1,
            "code": "ZAC",
            "libelle": "ZAC",
            "dateInactif": null,
            "createUser": "d.cottencin",
            "createDate": null
        },
        "description": "test"
    }],
```

Voici ce qui est attendu : 

```
  "financements": [
    {
      "description": "string",
      "id": 0,
      "typeFinancement": {
        "code": "string",
        "createDate": "2022-07-21T08:37:00.494Z",
        "createUser": "string",
        "dateInactif": "2022-07-21T08:37:00.494Z",
        "id": 0,
        "libelle": "string"
      }
    }
  ],
```

Seul l'id est absent mais en même temps je ne saurai pas quoi mettre comme valeur qui devrait être automatiquement remplie par l'API...

Voici l'erreur retournée (peu parlante...) : 

`{"status":"BAD_REQUEST","message":"ConstraintViolationException : la requête ne peut être exécutée","errors":["ERROR: null value in column \"id_operation\" violates not-null constraint\n  Détail : Failing row contains (2, null, 1, test)."]}`

**Comment by dcottenc** [comment]
Organisation en cours pour des tests ce jour

**Comment by dcottenc** [comment]
Testée et validée en PF de test
