### ISSUE TITLE
API - PUT operation v2 avec actions et acteurs

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#235]
## Description

Ref. #174 

idem que #230 #233 #234

⚠️  **Ce problème se pose aussi avec les champ lié à l'attribut acteur**

@dcottenc lorsque j'envoi les infos de maitrise foncière privé et publique j'ai une erreur de l'API.

PUT http://localhost:8081/tabou2/v2/operations

`{"status":"BAD_REQUEST","message":"ConstraintViolationException : la requête ne peut être exécutée","errors":["ERROR: null value in column \"id_operation\" violates not-null constraint\n  Détail : Failing row contains (2, null, 1, tests)."]}`

Voici ce que j'envoi : 

```
    "actions": [{
        "description": "tests",
        "typeAction": {
            "id": 1,
            "code": "ACTION",
            "libelle": "Action",
            "dateInactif": null,
            "createUser": "d.cottencin",
            "createDate": null
        }
    }],
```

Voici ce qui est attendu : 

```
  "actions": [
    {
      "description": "string",
      "id": 0,
      "typeAction": {
        "code": "string",
        "createDate": "2022-07-21T14:12:01.435Z",
        "createUser": "string",
        "dateInactif": "2022-07-21T14:12:01.435Z",
        "id": 0,
        "libelle": "string"
      }
    }
  ],
```

Seul l'id est absent mais en même temps je ne saurai pas quoi mettre comme valeur qui devrait être automatiquement remplie par l'API.

**Comment by dcottenc** [comment]
Organisation en cours pour des tests ce jour

**Comment by dcottenc** [comment]
Testée et validée en PF de test
