### ISSUE TITLE
API - v2 et v1 - DELETE EVENEMENT ne fonctionne pas

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#236]
## Description

Il est impossible de supprimer un événement.
l'API retourne un code 200 OK mais l'événement n'est pas supprimé.

## Etapes pour reproduire le bug

Dans Swagger : 

1. Observer les événement d'une OA
https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/evenements?asc=true

Voici l'event à supprimer :

```
    {
      "id": 724,
      "eventDate": "2022-07-18T10:33:31.743+00:00",
      "description": "test jdev 2",
      "systeme": false,
      "createUser": "gbruel",
      "createDate": "2022-07-25T10:33:41.300+00:00",
      "modifUser": "gbruel",
      "modifDate": "2022-07-25T10:33:41.300+00:00",
      "typeEvenement": {
        "id": 9,
        "libelle": "Echéancier 2020-2025",
        "dateInactif": null,
        "code": "2020-25",
        "systeme": false
      }
    },
```

2. Supprimer un événement non system (ex: 724) avec l'API V1

id oa 100
id event 724
==> Résultat OK

3. Supprimer un event avec l'API v2
id oa 100
id event 724
==> Résultat OK

4. Observez les événement pour voir qu'il a été supprimé
Résultat KO
L'événement est toujours présent.

https://portail-test.sig.rennesmetropole.fr/tabou2/operations/100/evenements?asc=true

```
    {
      "id": 724,
      .........
    },
```

## Comportement attendu

Supprimer un événement du journal de bord.

**Comment by dcottenc** [comment]
Ticket suivi dans le JiRa Open (1033)
