### ISSUE TITLE
API GED - POST Error 500 - l'Ajout ne fonctionne plus

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#237]
## Description

Lors de l'ajout d'un document, l'API retourne une erreur 500.

Voici le cas reproductible avec le type existant suivant : 

```
    {
      "id": 2,
      "nom": null,
      "libelle": "Illustration fiche suivi",
      "dateInactif": null
    },
```

![image](https://user-images.githubusercontent.com/16317988/181200132-c78a24e8-e104-4853-a1fb-6da7b69423e3.png)

![image](https://user-images.githubusercontent.com/16317988/181200203-e5b60d47-573a-4fe0-8191-72bcafd287d6.png)

## Etapes pour reproduire le bug

1. Aller sur le swagger
2. Ajouter un document

## Comportement attendu

Le document est sauvegardé, le serveur renvoi un code 200.

## Informatons complémentaires

L'ajout fonctionné le 26/07/2022.

**Comment by dcottenc** [comment]
Analyse effectuée => action coté DSI, correction en cours

**Comment by dcottenc** [comment]
Progrès de la DSI : l'ajout fonctionne de nouveau mais partiellement (le contenu ne s'enregistre pas...)

**Comment by dcottenc** [comment]
Cause identifiée par la DSI (script plan de classement)

Testée et corrigée en PF Alfresco de test
