### ISSUE TITLE
Fiche PA - Disparition de bloc et d'attributs 

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#238]
## Description

Il semble que les travaux sur la fiche OA  #174 ont eu des conséquences sur la fiche PA. 
Les blocs suivants et leurs attributs ont disparus :
- "Suivi opérationnel"
- "Programmation Habitat"

Le bloc "Modalités de réalisation" et à renommer en "Gouvernance" uniquement pour les PA.

## Etapes pour reproduire le bug

1. Ouvrir Urb@map
2. Sélectionner un programme
3. Constater que les éléments de la description ne sont pas conformes

## Comportement attendu

La fiche PA doit être identique à celle de la version précédente (avant livraison #174)

## Environnement

Portail Test

**Comment by Gaetanbrl** [comment]
Correction poussée,
En attente de test sur PF de test pour cloture.

**Comment by dcottenc** [comment]
Testé et validé en PF de test
