### ISSUE TITLE
[Edition] - Fiche OA/SA - Champ Consommation espace en doublon

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#239]
## Description

Le champ Consommation espace apparait dans les blocs Identification et descriptif des fiches OA/SA

## Comportement attendu

Le champ Consommation espace doit apparaitre uniquement dans le bloc Identification (cf #174)

## Média / captures d'écran

![image](https://user-images.githubusercontent.com/76009802/181728369-f2149318-4c37-45cb-b5bc-8ebc2e8edad9.png)

## Environnement

Portail Test RM

**Comment by Gaetanbrl** [comment]
commit fait => A déployer pour test

**Comment by Gaetanbrl** [comment]
Déployé en PF de test ==> A tester pour cloture @dcottenc

**Comment by dcottenc** [comment]
Teste et validé en Test. Merci
