### ISSUE TITLE
[Edition] - Fiche OA/SA - Champ Financement en lecture seule

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#240]
## Description

Le champ financement de la fiche OA/SA n'est pas modifiable (lecture seule)

## Comportement attendu

Le champ financement doit être modifiable (cf. #174) 

## Média / captures d'écran

![image](https://user-images.githubusercontent.com/76009802/181755687-b7fe9365-b7fa-4e3f-a846-bb3ff0fbf84a.png)

## Environnement

Portail test RM

**Comment by Gaetanbrl** [comment]
@dcottenc Corrigé, testé en PF de test.

**Comment by dcottenc** [comment]
Testé et validé en PF de test RM

**Comment by dcottenc** [comment]
**Informations complémentaires :** 
Erreur de ma part, le fonctionnement de ce champ devrait être le même que celui d'aménageur privé, cad : 

- si type financement est à Null alors le champ financement doit être en lecture seule et vide ;
- si type financement non null alors le champ financement est modifiable.

L'anomalie était donc à corriger uniquement sur le second cas...
