### ISSUE TITLE
[Edition] - Fiche OA/SA - Effacement des modifications Date lors de la modification d'un champ num ou txt

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#241]
## Description

Lors de la saisie d'un champ texte ou numérique dans la Fiche OA/SA, tous les champs Date modifiés reprennent leurs valeurs initiales (celles à l'ouverture de la fiche.

## Etapes pour reproduire le bug

1. Ouvrir le plugin Urb@map sur une OA ou un SA
2. Modifier des champs Date (vide ou existant)
3. Modifier un champ Texte ou numérique => voir que les champs Date ont repris leur valeurs initiales

## Comportement attendu

Les modifications des champs Date ne doivent pas etre annulées

## Média / captures d'écran

Etape 1
![image](https://user-images.githubusercontent.com/76009802/181757564-83858684-ca74-44fa-805c-5d9318baf8b4.png)

Etape 2
![image](https://user-images.githubusercontent.com/76009802/181757814-67e81061-4f62-442f-a611-01f3d01ec7e3.png)

Etape 3
![image](https://user-images.githubusercontent.com/76009802/181758016-62d4a88a-cbe8-499a-b79e-c75d83cbd3c0.png)

## Environnement

Portail test RM

## Informations complémentaires

Ce problème n'existe pas sur la fiche PA.

**Comment by Gaetanbrl** [comment]
Correction livrée et testée en PF de test => A tester pour fermer @dcottenc

**Comment by dcottenc** [comment]
Je ne vois pas de correction. J'ai bien vidé mon cache ctrl + F5 dans Firefox. J'ai toujours le même comportement

**Comment by dcottenc** [comment]
Informations complémentaires : 

- l'anomalie n'est pas présente dans la fiche programme et dans la fenêtre vocation. Elle ne concerne que les OA/SA ;
- il n'y a pas que les dates qui sont concernées, les listes déroulantes aussi (ex : Décision, Maîtrise d'ouvrage urbaine et
Mode de réalisation).

**Comment by dcottenc** [comment]
Testé et validé en PF Test RM. Merci
