### ISSUE TITLE
[Edition] - Fiche OA/SA Vocation -  Bouton "Retour à la fiche" KO

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#242]
## Description

Le bouton "Retour à la fiche" ne fonctionne pas dans la fenêtre vocation d'une opération à partir du moment où on modifie un attribut. Cela rend impossible l'enregistrement des modifications des attributs vocations.

## Etapes pour reproduire le bug

1. Ouvrir Urb@map
2. Cliquer sur une Opération
3. Ouvrir la fenêtre Vocation
4. Cliquer sur "Retour fiche" => vérifier que le bouton permet de revenir à la fiche OA
5. Ouvrir la fenêtre Vocation
6. Modifier un attribut
7. Cliquer sur "Retour fiche" => vérifier que le bouton ne déclenche aucune action

## Comportement attendu

Le bouton permet de fermer la fenêtre, puis l'enregistrement de la fiche OA permet de sauvegarder les modifications des attributs de la fenêtre vocation.

## Environnement

Portail test RM

## Informations complémentaires

Le bouton "Retour à la fiche" fonctionne si on ne modifie aucun attribut et si on clique sur "Réinitialiser" juste avant

**Comment by Gaetanbrl** [comment]
**Erreur en console :** 

```
Uncaught RangeError: Maximum call stack size exceeded
    at Zs (geOrchestra.js?06b510054a1cec239960:2:7869655)
    at zs (geOrchestra.js?06b510054a1cec239960:2:7868922)
    at ha (geOrchestra.js?06b510054a1cec239960:2:7848272)
    at changeVocation (Tabou2DescribeAccord.jsx:215:5)
```

**Analyse rapide :**

Après modification d'un champ et clic sur "Retour à la fiche", une boucle sans fin semble se déclencher avec pour conséquence un blocage de la fonctionnalité par React pour éviter un blocage de l'application totale.

**Action :** 

Revoir le changement des attributs  

https://github.com/sigrennesmetropole/geor_tabou2_front/blob/main/js/extension/components/form/identify/Tabou2DescribeAccord.jsx

**Comment by Gaetanbrl** [comment]
Je viens de tester ==> OK.
Testable sur la pf de test.

**Comment by dcottenc** [comment]
@Gaetanbrl Le bouton fonctionne mais les données modifiées ne sont pas enregistrées.

**Reproduire**
1. Ouvrir Urb@map
2. Sélectionner une OA
3. Modifier des attributs dans la fiche OA
4. Ouvrir la fenêtre vocation
5. Modifier des attributs dans la fenêtre vocation
6. Cliquer sur "Retour fiche"
7. Cliquer sur Enregistrer => Seules les attributs modifiés dans la fiche OA sont enregistrés

**Informations complémentaires**
Vérifié dans la console, les attributs ne sont pas présents dans l'appel au WS

**Comment by Gaetanbrl** [comment]
vu.
Je suis en train de corriger.

**Comment by Gaetanbrl** [comment]
@dcottenc correctif déployé en PF de test et testé 

1. Ouvrir Urb@map
2. Sélectionner une OA
3. Modifier des attributs dans la fiche OA
4. Ouvrir la fenêtre vocation
5. Modifier des attributs dans la fenêtre vocation
6. Cliquer sur "Retour fiche"
7. Cliquer sur Enregistrer => Seules les attributs modifiés dans la fiche OA sont enregistrés

**Résultat ==> OK**

### Attention : le choix de la vocation ZA entraine une erreur 500.

**Comment by dcottenc** [comment]
@Gaetanbrl partiellement corrigé

La vocation ne s'initialise pas avec la valeur (liste déroulante "choisir une vocation" en haut toujours vide).
Seul les attributs du premier onglet "composition" sont sauvegardes, ceux des autres ongelts non

**Comment by Gaetanbrl** [comment]
> partiellement corrigé

Corrigé normalement, vu en direct avec @dcottenc

**Comment by dcottenc** [comment]
Testé et validé en PF Test

Informations complémentaires les anomalies HTTP 400 sur les programmations et les contributions sont suivies directement avec Open.
