### ISSUE TITLE
[Edition] Fiche Tiers avec filtre - fonctionnement incorrect du bouton associer  

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#244]
## Description

Lorsqu'on utilise les boutons "tiers" avec filtre (cad à coté des champs réfèrent, moa, moe), la fenêtre Tiers s'ouvre avec le filtre lié au champ mais si on clique sur "associer" tous les boutons disparaissent.

Cette fonctionnalité appartient à la commande fin 2021. Prise en charge de la correction à discuter

## Etapes pour reproduire le bug

1. Ouvrir Urb@map
2. Cliquer sur une entité OA, SA ou PA
3. Cliquer sur le bouton Tiers à coté des champs réfèrent, moa ou moe
4. La fenêtre Tiers s'ouvre
5. Cliquer sur le bouton associer => tous les boutons disparaissent , on ne peut rien faire à part fermer la fenêtre 

## Comportement attendu

Le clic sur le bouton associer doit permettre d'ajouter une ligne dans le tableau (si possible avec le type du filtre pré sélectionné). Cf. Fonctionnement en cliquant sur le boutons Tiers en haut de la fiche.

## Environnement

Portail Test

## Informations complémentaires

Le bouton ajouter un tiers fonctionne correctement

**Comment by Gaetanbrl** [comment]
@dcottenc correctif déployé sur PF de test.

![image](https://user-images.githubusercontent.com/16317988/182591696-83221994-3d4f-4f24-8ba4-d3be5b1d292c.png)

**Comment by dcottenc** [comment]
Testé et validé en PF Test
