### ISSUE TITLE
[Edition] Fiche OA/SA - Popup résultat API - Message "Enregistrement réussi" même si http500 

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#245]
## Description

Lors de l'enregistrement d'une fiche OA/SA, le popup résultat API affiche toujours "Succès" même en cas d'http 400 ou 500

## Etapes pour reproduire le bug

1. Ouvrir Urb@map
2. Cliquer sur une OA/SA
3. Saisir un financement mais pas de type financement
4. Enregistrer => vérifier que l'on a un message "Enregistrement réussi" alors que l'API renvoi une http 500 (ano gestion financement sans type dans le back)

## Comportement attendu

Le popup doit être rouge et indiquer que l'enregistrement a échoué

## Environnement

Portail test RM

**Comment by Gaetanbrl** [comment]
Correctif poussé, visible et testable sur https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/Tabou-lot2

**Comment by LVP35** [comment]
Cohérence du message d'erreur constatée : 
![image](https://user-images.githubusercontent.com/115083062/195376288-7bef2454-81a9-44ef-9aab-120cf129d987.png)
