### ISSUE TITLE
Erreur 500 avec choix liste vocation ZA

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#246]
## Description

Lorsqu'on sauvegarde une OA avec une valeur sélectionnée dans la liste vocationZa, et qu'on sauvegarde la fiche, alors l'API retourne une erreur 500.

1. Voici les specs

<html>
<body>

Vocation ZA | Texte | Liste déroulante /!\ | --- | --- | /v2/operations | vocationZa.libelle
-- | -- | -- | -- | -- | -- | --

</body>
</html>

2. Voici ce qui est envoyé : 

```
    "vocationZa": {
        "libelle": {
            "id": 2,
            "code": "ARTISANAT",
            "libelle": "Artisanat",
            "dateInactif": null,
            "createUser": "d.cottencin",
            "createDate": null
        }
    },
```

3. Voici ce qui semble être attendu via la consultation du swagger (v2/operation/id) : 
```
   "vocationZa": {
    "code": "string",
    "createDate": "2022-08-03T08:35:22.682Z",
    "createUser": "string",
    "dateInactif": "2022-08-03T08:35:22.682Z",
    "id": 0,
    "libelle": "string"
  }
```

Après tentative dans le swagger directement avec cette valeur de vocationZa, il y a toujours une erreur 500 : 
```
    "vocationZa": {
        "id": 2,
        "code": "ARTISANAT",
        "libelle": "Artisanat",
        "dateInactif": null,
        "createUser": "d.cottencin",
        "createDate": null
    },
```

## Etapes pour reproduire le bug

1. Cliquer sur une OA ou SA
2. Ouvrir la fenêtre des attributs de la vocation
3. Choisir une valeur dans vocationZa
4. Cliquer sur "Retour à la fiche"
5. Sauvegarder la fiche
6. Voir une erreur 500 dans le flux réseau (console dev chrome)

## Comportement attendu

Pouvoir sauvegarder la vocationZa.

## Informatons complémentaires

URL de requête: https://portail-test.sig.rennesmetropole.fr/tabou2/v2/operations
Mode de requête: PUT
Code d'état: 500 Server Error

**AUCUN MESSAGE D'ERREUR FOURNI PAR L'API**

**Comment by dcottenc** [comment]
Je viens de faire plusieurs tests avec Swagger : 
1) Test réussi (vérifié sur deux OA) avec semble-t-il la même chose que toi :
```
  "vocationZa": {
    "id": 2,
    "code": "ARTISANAT",
    "libelle": "Artisanat",
    "dateInactif": null,
    "createUser": "d.cottencin",
    "createDate": null
  },
```
2) Test avec structure minimale (uniquement l'id) réussi.
```
  "vocationZa": {
    "id": 3
  },
```

Je vais faire des tests complémentaires avec le json issu du front

**Comment by Gaetanbrl** [comment]
Après plusieurs modification ca semble bien se comporter. Je n'ai plus l'erreur.
Je clos.
