### ISSUE TITLE
GED - Afficher un scroll sur la liste des documents

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#247]
## Description

Lorsque plusieurs documents sont affichés, rien n'indique à l'utilisateur qu'il doit descendre avec la molette de la souris (scroll down).

Il est demandé qu'une barre de défilement (ou un autre moyen) indique à l'utilisateur qu'il est nécessaire de descendre pour voir d'autre documents dans la liste.

Ref #226

**Comment by Gaetanbrl** [comment]
Correctif poussé, visible et testable sur https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/Tabou-lot2

**Comment by Gaetanbrl** [comment]
testé sur FF et Chrome 15" => Une seule barre

## FF

![image](https://user-images.githubusercontent.com/16317988/195376981-7fa7cba2-4606-47e8-a9ac-3aa2a8394cee.png)


## Chrome

![image](https://user-images.githubusercontent.com/16317988/195377142-743d11be-2cda-4936-bbb4-3bef685fd2f3.png)

**Comment by LVP35** [comment]
Une seule barre constatée sur Edge également : 
![image](https://user-images.githubusercontent.com/115083062/195377675-d2b356c6-62ce-4c37-999b-d27db9ee147b.png)

Problème de double barre causé par zoom sur la résolution écran dans les paramètres Windows -> ne relève donc pas d'une anomalie côté front.
