### ISSUE TITLE
[Navigation] Accès journal des événements KO

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#249]
## Description

Lorsqu'on souhaite accéder au journal des événements des OA/SA/PA, le clic sur le bouton déclenche une erreur MapStore

## Etapes pour reproduire le bug

1. Ouvrir Urb@map
2. Sélectionner une OA, SA ou PA
3. Cliquer sur "journal de bord" => plantage MapStore

## Comportement attendu

Le clic sur le bouton doit faire apparaitre la modale de gestion des événements de l'entité sectionnée

## Environnement

Portail RM de test et de prod (Plugin v2.2, API, v1.2.7)

**Comment by Gaetanbrl** [comment]
Correctif visible sur PF de test @dcottenc 
Je fais la release (hotfix) dès validation de ta part que c'est corrigé

**Comment by dcottenc** [comment]
Testé et validé en PF Test
