### ISSUE TITLE
[Edition] Journal de bord - Disfonctionnement bouton Enregistrer en ajout

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#251]
## Description

Le bouton Enregistrer ne permet pas d'ajouter un événement dans la modale Journal de bord d'une OA ou d'un PA

## Etapes pour reproduire le bug

1. Ouvrir Urb@map
2. Sélectionner une OA ou un PA
3. Cliquer sur le bouton Journal de bord
4. Cliquer sur Ajouter un événement et saisir les champs (en modifiant manuellement la date)
5. Cliquer sur Enregistrer => l'ajout de la ligne ne se déclenche pas (et le comportement des boutons devient incorrect)

## Comportement attendu

Le bouton Enregistrer doit permettre l'ajout des évènements en base et l'actualisation de la liste de la modale 

## Environnement

Portail RM Test et Prod. Plugin v2.2.1 et API v1.2.7

**Comment by dcottenc** [comment]
**Modification de la description**
Suite à des tests complémentaires, il apparait que cette anomalie ne se voit visible que dans certains cas. La piste la plus probable serait la saisie manuelle de la date.

**Comment by dcottenc** [comment]
**Changement de criticité => Majeur**
La MOA n'a pas reussi à créer de commentaire. Mème sans changer la date le curseur devient inoerent quand on veut cliquer sur Valider (curseur avec image non autorisée)

**Comment by Gaetanbrl** [comment]
après correction du champ date, un autre soucis survient à la validation.
La saisie est bien réalisée, mais la saisie ne semble pas être validée, alors que la donnée est bien envoyée en base.

![image](https://user-images.githubusercontent.com/16317988/191052881-5ac2ea93-d309-495b-bdf2-fcf412308f4c.png)

**Comment by Gaetanbrl** [comment]
L'événement validé apparait alors en tant que saisie en cours mais reste non validable. 
Ce comportement n'est pas désirable et devrait être le suivant : 

Après la validation, l'événement devrait être supprimé et un rappel de la liste entière devrait avoir lieu pour mettre à jour la liste.

**Comment by Gaetanbrl** [comment]
Correctif, poussé, à tester.
Pour le moment uniquement visible sur la branche develop.

**Comment by dcottenc** [comment]
@Gaetanbrl commentaire précédent à annuler. J'ai bien reçu le zip

**Comment by dcottenc** [comment]
@Gaetanbrl je constate après enregistrement de l'événement qu'il disparait de la liste. Si je quitte la fenêtre et je reviens alors la liste est ok (avec le nouvel événement). Fais-tu le même constat ?

**Comment by dcottenc** [comment]
> @Gaetanbrl je constate après enregistrement de l'événement qu'il disparait de la liste. Si je quitte la fenêtre et je reviens alors la liste est ok (avec le nouvel événement). Fais-tu le même constat ?

En complément , le PUT de l'événement est OK et le GET de la liste contient bien l’élément ajouté

**Comment by Gaetanbrl** [comment]
> En complément , le PUT de l'événement est OK et le GET de la liste contient bien l’élément ajouté

Oui, la données est bien sauvegardée, on réceptionne bien mais il doit y avoir un petit soucis de contrôle pour refresh le component React (donc refresh du HTML).

**Comment by LVP35** [comment]
Point non testable sur l'environnement portail-test suite à la montée de version de Mapstore2, en attente du roolback sur l'ancienne version pour qualifier.

**Comment by sigrmed** [comment]
Testé et validé sur portail-test.
