### ISSUE TITLE
[Edition] Journal de bord - Date évènement non modifiable (restauration sur perte focus) 

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#252]
## Description

Dans la modale journal de bord et lors de la modification d'un événement, il n'est pas possible de modifier la date événement car sa valeur est restaurée dès que l'utilisateur clique sur un autre champ ou sur le bouton Enregistrer (perte focus)

## Etapes pour reproduire le bug

1. Ouvrir Urb@map
2. Cliquer sur une OA ou un PA
3. Cliquer sur Journal de bord
4. Cliquer sur modifier un événement
5. Modifier la date de l'événement manuellement
6. Cliquer sur un autre attribut ou sur Enregistrer => Constater que la date est restaurée (et dans le cas de l'enregistrement c'est la valeur restaurée qui est envoyée à l'API)

## Comportement attendu

La valeur de la date événement ne doit pas etre restaurée sur perte du focus.

## Environnement

Portail Test et prod, Plugin v2.2.1, API v1.2.7

**Comment by dcottenc** [comment]
**Modification de la description**
Il reste possible de modifier la date en utilisant le composant. Seule la saisie manuelle entraine la restauration lors de la perte de focus

**Comment by Gaetanbrl** [comment]
Correctif, poussé, à tester.
Pour le moment uniquement visible sur la branche develop.

**Comment by dcottenc** [comment]
Testé et validé en production
