### ISSUE TITLE
[Edition] GED - Utilisation du bouton valider non autorisée lors de l'ajout et de la modification d'un document

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#253]
## Description

Lors de l'ajout ou de la modification d'un document, l'utilisation du bouton Valider n'est jamais autorisée (changement du curseur en sens interdit) ce qui bloque la fonctionnalité "Ajouter un document".

## Étapes pour reproduire le bug

1. Ouvrir Urb@map
2. Sélectionner une OA ou un PA
3. Cliquer sur le bouton "Documents"
4. Cliquer sur "Ajouter un document" ou "Éditer un document" => vérifier que l'utilisation du bouton Valider n'est pas autorisée (normal pas de métadonnées saisies)
5. Saisir les métadonnées du documents et son contenu
=> Constater que l'utilisation du bouton Valider n'est pas autorisée malgré la saisie correcte des éléments du document 

## Comportement attendu

L'utilisation bouton Valider doit être autorisée dès que les champs obligatoires sont saisis afin de permettre l'enregistrement du fichier

## Environnement

Portail de prod RM

**Comment by Gaetanbrl** [comment]
@dcottenc peux-tu me confirmer que seul les référents peuvent ajouter un document ?

**Comment by dcottenc** [comment]
> peux-tu me confirmer que seul les référents peuvent ajouter un document ?
Les rôles Contributeur ET Referent ont les droits d'ajouter / Modifier / Consulter / supprimer un document.
Seul le role consult ne peut que consulter un document

**Comment by Gaetanbrl** [comment]
Lié à #254 , lors de la saisie de la date il y a une suppression des autres champs (soucis constatés précédemment lors des développements de la dernière release).

**Comment by Gaetanbrl** [comment]
@dcottenc donc la correction de la #254 va permettre de "logiquement" corriger ce ticket aussi.

**Comment by dcottenc** [comment]
> la correction de la https://github.com/sigrennesmetropole/geor_tabou2_front/issues/254 va permettre de "logiquement" corriger ce ticket aussi.

C'est possible mais à tester car il me semble avoir constaté qu'en modification, il n'est pas possible de cliquer sur Valider même si tu ne changes aucun champ (donc pas de suppression sur perte focus)

**Comment by Gaetanbrl** [comment]
> C'est possible mais à tester car il me semble avoir constaté qu'en modification, il n'est pas possible de cliquer sur Valider même si tu ne changes aucun champ (donc pas de suppression sur perte focus)


En local, je peux modifier un élément ou non, tant que les champs sont bien saisis je peux valider et sauvegarder (sauvegarde vu / testée).

Seul la modification d'une date pour un nouveau document ne me permet pas de valider alors que les autres champs avaient été saisis (cas conforme à la description du bug).

**Comment by Gaetanbrl** [comment]
- [ ] Comportement corrigé à l'ajout (avec #254)
- [ ] Comportement corrigé à la modification

**Comment by Gaetanbrl** [comment]
**Autre bug :**
Effet de bord >> en POST, La requête n'est plus bonne en raison de la correction de #189 par OPEN.

**Comment by dcottenc** [comment]
Testé et validé (en ajout et modification)
