### ISSUE TITLE
[Edition] GED - Suppression d'attributs lors de la perte de focus du composant "date document"

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#254]
## Description

Lors de l'ajout ou de la modification d'un document, la perte de focus après la sélection d'une date entraine la suppression des attributs nom (en ajout) et nom/type document (en modification).

## Étapes pour reproduire le bug

1. Ouvrir Urb@map
2. Sélectionner une OA ou un PA
3. Cliquer sur le bouton "Document"
4. Cliquer sur Ajouter ou modifier un document
5. Saisir un nom et un type document
6. Sélectionner une date
=> constater la suppression du nom (et du type en modification)

## Comportement attendu

Les attributs saisis ne doivent pas être supprimés.

## Environnement

Portail prod RM

**Comment by Gaetanbrl** [comment]
Vu,
Lors de la modification des champs, la date récupère les valeurs de l'état précédent (scope différents - problème connu avec le champ date).
Composant `DateTimePicker `à remplacer par `Tabou2Date.jsx`.

**Comment by Gaetanbrl** [comment]
Comportement fixé ce jour.
Correctif actuellement / uniquement disponible sur la branche develop.

**Comment by dcottenc** [comment]
Testé et validé (en ajout et modification)
