### ISSUE TITLE
[Edition] GED - Suppression d'attribut lors de la perte de focus du composant "type document"

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#255]
## Description

Lors de de la modification d'un document, la perte de focus après la sélection d'un type document entraine la suppression du type.

## Étapes pour reproduire le bug

1. Ouvrir Urb@map
2. Sélectionner une OA ou un PA
3. Cliquer sur le bouton "Document"
4. Cliquer sur modifier un document
5. Cliquer sur type (sans le changer)
6. Cliquer sur Nom
=> constater la suppression du type existant

## Comportement attendu

Les attributs saisis ne doivent pas être supprimés.

## Environnement

Portail prod RM - Plugin branche develop

**Comment by Gaetanbrl** [comment]
#267 - l'api retourne une erreur 500 actuellement

**Comment by sigrmed** [comment]
L'action n'entraîne pas de modification des données dans la GED ni d'appel sur le endpoint programmes/{id}/documents. Par ailleurs, l'utilisateur ne peut pas valider la modification si aucun type n'est sélectionné. Par ailleurs, la modification du type n'entraîne pas d'erreur. Je suggère donc de clôre cette issue.
