### ISSUE TITLE
[Filtre] Evolution - Fonctionnement filtre Financement

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#257]
## Description

En tant qu'utilisateur Urb@map
Je souhaite pouvoir utiliser le filtre "4 PA - Financement"
Afin de filtrer les PA et OA/SA correspondants au financement sélectionné

## (Si) Règles spécifiques - Règles métiers

Afin d’exécuter le filtre, il convient de :

- filtrer les PA avec pour chaque valeur de financement un critère décrit ci-dessous ;
- filtrer les OA et SA en fonction des PA filtrés (similaire aux fonctionnements des autres filtres du groupe  "4 - Définir les critères liés aux programmes").

Filtres des PA (si possible mettre en paramétrable les attributs en gras ci-dessous dans la config du plugin)  : 

- Accession aidée => **logements_access_aide** > 0
- Accession libre => **logements_access_libre** > 0
- Accession maîtrisée => **logements_access_maitrise** > 0
- Locatif aidé => **logements_locatif_aide_prevu** > 0
- Locatif régulé HLM => **logements_locatif_regule_hlm_prevu** > 0
- Locatif régulé privé => **logements_locatif_regule_prive** > 0

## (Si) Tests d'acceptabilité

1. Ouvrir Urb@map
2. Sélectionner une valeur dans le filtre "4- Financement"
3. Appliquer le filtre
4. Vérifier que tous les PA affichés ont bien une valeur non nulle pour le type de financement sélectionné
5. Vérifier que les OA et SA affichés contiennent au moins un PA filtré

**Comment by Gaetanbrl** [comment]
Voici un détail pour les filtres appliqués avec pour exemple la sélection de la valeur `Accession Libre` dans la liste des types de financements :

1. Expression du filtre CQ à appliquer sur la couche PA (`v_oa_programmes`) :
`logements_access_libre > 0`

Ce filtre sera appliqué directement sur la couche comme un filtre attributaire simple afin d'avoir uniquement les programmes donc la valeur de l'attribut `logements_access_libre` est supérieure à 0.

2. Expression du filtre CQ à appliquer sur les couche opération et secteurs (filtre identique sur les deux couches):

`(INTERSECTS(the_geom,collectGeometries(queryCollection('tabou:tabou_v_oa_programme', 'the_geom','(id_tabou IS NOT NULL AND logements_access_libre > 0)'))))`

Ce filtre permettra, pour la couche OA, de récupérer les OA qui intersectent une entité de la couche PA (programmes) dont la valeur de l'attribut `logements_access_libre` est supérieures à 0 .

**Comment by Gaetanbrl** [comment]
@LVP35 testable sur la plateforme de test.

1. Ouvrir le context
https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/Tabou-lot2

2. Ouvrir le plugin Urbamap

3. Sélectionner dans la liste "Tous financement" la valeur : 
`Accession maitrisée`

![image](https://user-images.githubusercontent.com/16317988/213764209-74cf9a6c-f69d-476f-9898-4f6c025edba5.png)

5. Appliquer le filtre

![image](https://user-images.githubusercontent.com/16317988/213764343-174d3b3e-6468-4d0a-8de2-a2cafcd434d6.png)

![image](https://user-images.githubusercontent.com/16317988/213765519-94cf5fea-8a76-4ede-b4ef-62881dcb9656.png)


7. Fair un zoom sur Baud Chardonnet et voir que le filtre s'applique bien sur la carte

![image](https://user-images.githubusercontent.com/16317988/213764472-87d499e4-ab98-4a87-9263-61de800afa78.png)


9. Fermer Urbamap

10. Cliquer sur un des programme filtré visible et constater que sa valeur pour l'attribut `logements_access_maitrise` est supérieure à 0

![image](https://user-images.githubusercontent.com/16317988/213764578-66c84a22-4444-45d1-9c8b-36c2c3ff0411.png)

11. Supprimer tous les filtres et voir que toutes les entités sont visibles

12. Refaire le filtre sur Acces maitrisé et rajouté la commune `Rennes` et le quartier `Bourg l'Evesque - La Touche - Moulin du Comte`
![image](https://user-images.githubusercontent.com/16317988/213765386-0b0ed089-ef2d-449f-beb7-e01bc243e62a.png)

14. Appliquer le filtre et voir le résultat 

![image](https://user-images.githubusercontent.com/16317988/213765660-e7958904-1037-4172-b215-00f6dc33999b.png)

15. Supprimer les filtres et voir que toutes les entités sur la carte sont de nouveau visibles

**Comment by LVP35** [comment]
Test réalisé sur le portail-test le 27/01/2023.
