### ISSUE TITLE
[Mapstore2] - Erreur de fonctionnement plugin suite à montée de version

### ISSUE THREAD

**Issue by LVP35** [sigrennesmetropole/geor_tabou2_front#259]
## Description

Erreurs de fonctionnement du plugin tabou sur le geoportail-test suite à la montée de version de mapstore2-georchestra 2022. 

## Environnement 

geoportail-test, sur tous les navigateurs.

**Comment by Gaetanbrl** [comment]
Suite à une commande pour analyser les travaux nécessaires au fonctionnement, voici ce que nous avons pu voir.

# Analyse

## Attendu par les évolutions

> Ref doc : https://mapstore2.readthedocs.io/en/latest/developer-guide/extensions/#managing-drawing-interactions-conflict-in-extension

### 1 ] Adaptation UI Urb@map

Des évolutions concernent l'affichage des plugins dans MapStore2 depuis MapStore 2022.x.

Les évolutions sont déjà faites sur le plugin `mapstore2-cadastrapp` et peuvent comporter un modèle et exemple : 
https://github.com/georchestra/mapstore2-cadastrapp/blob/master/js/extension/selectors/maplayout.js

 Il est décrit : 

> All extensions using DockPanel or DockablePanel components have to be updated if their dock panel is rendered on the right side of the screen, next to the new sidebar menu.

> Make your extension aware of the map layout changes by getting corresponding state value using following selector

> Replace DockPanel, DockablePanel, ContainerDimensions (if used) with the ResponsiveContainer and make sure that dock content is a child of ResponsiveContainer

Le plugin Urbamap utilisant le volet à droite, est concerné. Les étapes 1 et 2 suivantes doivent donc être apportées : 


**1. Détecter les modifications d'affichage via le selecor `mapLayoutValuesSelector` et y connecter le volet DockPanel**

```
createSelector(
    ...
    state => mapLayoutValuesSelector(state, { height: true, right: true }, true),
    ...
    (dockStyle) => ({
        dockStyle
    })
)
```

La liste des selectors devra alors être complétée par ce selector : 

https://github.com/sigrennesmetropole/geor_tabou2_front/blob/main/js/extension/selectors/tabou2.js

**2. Utiliser `ResponsivePanel` à la place de `DockPanel`, `ContainerDimensions `, `DockablePanel`**

Il sera donc nécessaire de modifier le DockPanel du composant suivante pour utiliser le composant ResponsivePanel : 

https://github.com/sigrennesmetropole/geor_tabou2_front/blob/main/js/extension/components/tabou2panel/Tabou2MainPanel.jsx#L27

> Le composant ResponsivePanel est bien disponible dans le dépôt actuel MapStoreExtension et pourra être reporté dans Urb@map

**3. Fermer les autres fenêtre à l'ouverture du panel Urb@map**

Il est préférable de désactiver les autres panel (DockPanel) ouverts lors de l'ouverture du plugin Urb@map.
Cette modification se fera en utilisant l'action : updateDockPanelsList

Cette action permet de mettre à jour dans la vue courante de MapStore, la liste des DockPanel ouverts.

Note documentaire liée : 

> Array at state.maplayout.dockPanels.right contains list of panels that can be extended or modified by extension by dispatching updateDockPanelsList action.

Please note that adding dock into the list will automatically close previously active panel, so it's a good idea to dispatch the action on app initializing or when dock panel is open. Measurement plugin can be used as a reference of implementation, see openMeasureEpic & closeMeasureEpic in epics/measurement.js.

### 2 ] Remplacement du BurgerMenu par SideBarMenu

Cette modification affecte le fichier localConfig.json. Cette modification est préférable mais ne consiste pas une obligatoire car le plugin Urbamap s'intègre fans la Toolbar lattéral droite et non dans le BurgerMenu. 

Cette modification est à apportée par l'administrateur du contexte.

### 3 ] Mise à jour du coeur du plugin et process de chargement
> L'ensemble de ces modifications sont visibles dans le template par défaut des extensions MapStore2
> https://github.com/geosolutions-it/MapStoreExtension/tree/master/js

Des modifications ont été détectées dans les fichiers propre  à l'environnement de développement.
Il faudra alors mettre à jour les fichiers : 

https://github.com/sigrennesmetropole/geor_tabou2_front/blob/main/js/extensions.js

```
// NOUVEAU FICHIER A UTILISER AVEC L'AJOUT D'UN FICHIER js/Module.js
import {toModulePlugin} from "@mapstore/utils/ModulePluginsUtils";
import { name } from '../../../config';

export default toModulePlugin(name, () => import(/* webpackChunkName: 'extensionName' */ './Module'));
```

et

https://github.com/sigrennesmetropole/geor_tabou2_front/blob/main/js/app.jsx

```
// NOUVELLE SYNTAXE A UTILISER >>>>
import Extension from './extension/plugins/Extension';
import { name } from '../config';


export default {
    [name]: Extension
};
```

Un dernier fichier `Module.jsx` pourra compléter le répertoire /js comme visible ici : 
https://github.com/geosolutions-it/MapStoreExtension/tree/master/js/extension/plugins

**Comment by Gaetanbrl** [comment]
Etant d'avancement @LVP35 :

- [ ] Récupération du[ template à jour ](https://github.com/geosolutions-it/MapStoreExtension)
- [ ] intégration du plugin urb@map dans ce projet à jour
- [ ] Mise à jour du coeur du plugin et process de chargement (point 3 dans le commentaire précédent)
- [ ] Utiliser ResponsivePanel à la place de DockPanel, ContainerDimensions , DockablePanel
- [ ] Détecter les modifications d'affichage via le selecor mapLayoutValuesSelector et y connecter le volet DockPanel
- [ ] Fermer les autres fenêtre à l'ouverture du panel Urb@map
