### ISSUE TITLE
Icône en doublon avec Cadastrapp

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#265]
## Description

Comme remonté par @catmorales, l'icône Tabou est en doublon avec Cadastrapp.

Je viens de réaliser un icône qui permettrait d'éviter le doublon @LVP35 :
![image](https://user-images.githubusercontent.com/16317988/214820521-f139ce71-aad0-4052-a739-ff1ee5105c9c.png)

C'est une structure de bâtiment avec un graphique à l'intérieur. Il fait référence à l'urbanisme et au suivi / gestion que doit représenter les outils urbamap.

Voici le rendu, qu'en pensez-vous ?

![image](https://user-images.githubusercontent.com/16317988/214820588-4fef6cb9-6031-4975-a690-664f0041aeb5.png)

**Comment by sigrmed** [comment]
Point validé en recette et en test.
