### ISSUE TITLE
Position du plugin dans SidebarMenu

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#266]
## Description

@LVP35 il semblerait que les plugins doivent se positionner dans la sidebar afin de garder une homogénéité entre les extensions chez Rennes Métropole.
La version en cours de release contient cette modification avec le nouveau logo, est-ce bon pour la MOA ?

**Comment by sigrmed** [comment]
Point validé en recette et en prod.
