### ISSUE TITLE
API - Erreur 500 - get operation/id/documents

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#267]
## Description

L'appel des documents ne fonctionne plus.
Le problème doit être actuel sur la PROD.

## Etapes pour reproduire le bug

1.Ouvrir le swagger : 
2. Utiliser l'API pour avoir les documents de l'operations id 100

https://portail-test.sig.rennesmetropole.fr/tabou2/swagger-ui.html#/operation-api-controller/searchDocuments

3. voir l'erreur

```
Request URL: https://portail-test.sig.rennesmetropole.fr/tabou2/v2/operations/100/documents?start=0&resultsNumber=5&asc=true&nom=**&libelleTypeDocument=**&typeMime=**
Request Method: GET
Status Code: 500 Server Error
```

Paramètres envoyés : 

`start=0&resultsNumber=5&asc=true&nom=**&libelleTypeDocument=**&typeMime=**`

## Comportement attendu

Obtenir la liste des documents et non une erreur 500.

**Comment by LVP35** [comment]
L'erreur 500 était due à une migration de la GED Alfresco à laquelle le backend Urbamap ne pouvait plus accéder. Le point est en cours de traitement avec la DSI RM et ne concerne pas le frontend Urbamap.
