### ISSUE TITLE
[Urbamap] - Vocations - Attributs non sauvegardés

### ISSUE THREAD

**Issue by LVP35** [sigrennesmetropole/geor_tabou2_front#268]
## Description

l'attribut "type de vocation" saisi dans la modale "Vocations" n'est pas sauvegardé. 

## Etapes pour reproduire le bug

1. Se rendre sur l'opération ZAC Courrouze (id == 16) 
2. Ouvrir la modale "Vocations" (bouton "Voir les attributs") 
3. Dans la liste déroulante "Choisir une vocation", changer la vocation
4. Cliquer sur le bouton "Retour à la fiche"
5. Sur la fiche de l'opération, valider la saisie

## Comportement attendu

Le type de vocation de l'opération est modifié

## Média / captures d'écran

![image](https://user-images.githubusercontent.com/115083062/215151861-60ac3d3a-912e-4ba0-8b96-4f5c7b513b89.png)

## Environnement

Merci de remplir ces informations si connues :
 - OS: Windows
 - Navigateur / browser Firefox
 - Version 102.7.0esr

## Informatons complémentaires

Préciser par exemple si le problème a été vu suite à l'installation d'une nouvelle version ou suite à des modifications que vous auriez faites ou bien par inadvertance.

**Comment by Gaetanbrl** [comment]
Issue noté, reproduite.
Analyse en cours.

**Comment by Gaetanbrl** [comment]
@LVP35 correctif disponible sur le ZIP de la branche develop.
Testable.

**Comment by Gaetanbrl** [comment]
Je viens de déployer le plugin sur le portail test.
Correctif testé. 

@LVP35 a clore quand tu auras également testé.

**Comment by Gaetanbrl** [comment]
on peut clore ?
