### ISSUE TITLE
[Programme] - Affichage tableau DDS

### ISSUE THREAD

**Issue by sigrmed** [sigrennesmetropole/geor_tabou2_front#271]
Erreur dans le peuplement du tableau DDS. Le champ à récupérer dans le response body de getpermis est "datDate" et non "datDatePrevu ". 

https://github.com/sigrennesmetropole/geor_tabou2_front/blob/49244fac0e6aa069283cd6c66e25cdd511194abc/js/extension/components/form/identify/Tabou2DdsAccord.jsx#L85

**Comment by Gaetanbrl** [comment]
voir https://github.com/sigrennesmetropole/geor_tabou2_front/issues/217

et ce commit : 

https://github.com/sigrennesmetropole/geor_tabou2_front/commit/39ef4a72201b35422ea6f8449f071cd052601d6e

Modifié suite aux specs de l'API... qui ont du changé depuis...

**Comment by Gaetanbrl** [comment]
Poussé et ZIP déployé.

A tester par @LVP35 :
https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/Tabou-lot2

**Comment by Gaetanbrl** [comment]
Vu testé corrigé pour l'affichage du format de la date

![image](https://user-images.githubusercontent.com/16317988/225387198-935dbff5-c7fc-4240-9e07-66e6430e83d8.png)
