### ISSUE TITLE
Erreur au picking sur Firefox

### ISSUE THREAD

**Issue by LVP35** [sigrennesmetropole/geor_tabou2_front#273]
## Description

Le picking ne fonctionne pas sur Firefox

## Etapes pour reproduire le bug

Etapes à suivre pour reproduire votre problème du type : 

1. Se rendre sur https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/Tabou-lot2
2. Activer le plugin Urbamap dans la barre latérale
3. Cliquer sur un programme ou une opération
4. La fiche de détail du programme ou de l'opération ne s'affiche pas

## Comportement attendu

Au clic sur un programme ou sur une opération, la fiche de détail de celui-ci s'ouvre. 

## Média / captures d'écran

La console du avigateur affiche l'erreur suivante : 

`Error in epic "onTabouMapClick". Original error: TypeError: a.tocLayer is undefined
    list webpack://Tabou2/./js/extension/epics/layer.js?:97
    onTabouMapClick webpack://Tabou2/./js/extension/epics/layer.js?:97
    _next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    u https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    u https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    default https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    b https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    componentDidMount https://portail-test.sig.rennesmetropole.fr/mapstore/dist/4590.1faa21f224be9b76ea80.chunk.js:1
    dispatchEvent https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    handleMapBrowserEvent https://portail-test.sig.rennesmetropole.fr/mapstore/dist/8256.1faa21f224be9b76ea80.chunk.js:1
    dispatchEvent https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    clickTimeoutId_ https://portail-test.sig.rennesmetropole.fr/mapstore/dist/8256.1faa21f224be9b76ea80.chunk.js:1
    setTimeout handler*emulateClick_ https://portail-test.sig.rennesmetropole.fr/mapstore/dist/8256.1faa21f224be9b76ea80.chunk.js:1
    handlePointerUp_ https://portail-test.sig.rennesmetropole.fr/mapstore/dist/8256.1faa21f224be9b76ea80.chunk.js:1
    i https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    handlePointerDown_ https://portail-test.sig.rennesmetropole.fr/mapstore/dist/8256.1faa21f224be9b76ea80.chunk.js:1
geOrchestra.js:2:1186474
    r https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    error https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _error https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    error https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _error https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    error https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _error https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    error https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    _next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    next https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    u https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    u https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    default https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    b https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    componentDidMount https://portail-test.sig.rennesmetropole.fr/mapstore/dist/4590.1faa21f224be9b76ea80.chunk.js:1
    dispatchEvent https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    handleMapBrowserEvent https://portail-test.sig.rennesmetropole.fr/mapstore/dist/8256.1faa21f224be9b76ea80.chunk.js:1
    dispatchEvent https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    clickTimeoutId_ https://portail-test.sig.rennesmetropole.fr/mapstore/dist/8256.1faa21f224be9b76ea80.chunk.js:1
    (Asynchrone : setTimeout handler)
    emulateClick_ https://portail-test.sig.rennesmetropole.fr/mapstore/dist/8256.1faa21f224be9b76ea80.chunk.js:1
    handlePointerUp_ https://portail-test.sig.rennesmetropole.fr/mapstore/dist/8256.1faa21f224be9b76ea80.chunk.js:1
    (Asynchrone : EventListener.handleEvent)
    i https://portail-test.sig.rennesmetropole.fr/mapstore/dist/geOrchestra.js?1faa21f224be9b76ea80:2
    handlePointerDown_ https://portail-test.sig.rennesmetropole.fr/mapstore/dist/8256.1faa21f224be9b76ea80.chunk.js:1`

## Environnement

Merci de remplir ces informations si connues :
 - OS: Windows
 - Navigateur : Firefow
 - Version : 115.4.0esr (32 bits)

**Comment by Gaetanbrl** [comment]
Testé ce jour en FF 119.0.1 - Non reproduis.

**Comment by Gaetanbrl** [comment]
Vu avec @LVP35 - suite à ces actions, l'erreur n'apparaît plus :

- ajouter le module "vider la session"
- Utiliser le module pour "vider la session"
