### ISSUE TITLE
[Consultation] - Fiche PA - Associer documents

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#28]
## Description

**En tant que** Maire,
**Je souhaite** visualiser les documents d'une entité de la couche PA
**Afin de** m'informer sur les documents d'une entité visible sur la carte.

## (Si) Tests / Cas

1. Cliquer sur la couche PA dans la TOC
2. Cliquer sur une entité de la couche PA sur la carte
3. Voir la Fiche PA
4. Cliquer sur "Associer documents"
5. Voir la fenêtre "Associer documents"
6. Voir que les informations ne sont pas modifiables
7. Voir que le bouton "Sauvegarder" n'est pas cliquable ou grisé ou invisible
8. Voir que je peux ouvrir ou télécharger les documents en diffusion non restreinte
9. Voir que les documents en diffusion restreinte ne sont pas consultable ou téléchargeables

**Comment by dcottenc** [comment]
En complément de la description ci-dessus.

**WS** 
Pour les PA
```
GET /programmes/{programmeId}/documents/{documentId}
GET /programmes/{programmeId}/documents/{documentId}/content
```

**Règle de gestion**
La consultation de la liste des documents s'effectue à l'aide de l'Id de celle-ci (obligatoire) et peut être filtrée, triée et paginée (cf. swagger).
Tous les utilisateurs peuvent consulter les documents
La consultation s'effectue en utilisant deux WS, l'un pour les métadonnées et l'autre pour son contenu.

**Contrôles**
Nous n'avons pas encore défini la taille maximum acceptée (tests en cours)

**Comment by dcottenc** [comment]
Testé et validé en VA. Merci
