### ISSUE TITLE
[Consultation] - Fiche OA ou SA - Associer tiers

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#30]
## Description

**En tant que** Maire,
**Je souhaite** visualiser les tiers d'une entité de la couche OA & SA
**Afin de** m'informer sur les tiers d'une entité visible sur la carte.

## (Si) Tests / Cas

1. Cliquer sur la couche OA ou SA dans la TOC
2. Cliquer sur une entité de la couche OA ou SA sur la carte
3. Voir la Fiche OA & SA
4. Cliquer sur "Associer tiers"
5. Voir la fenêtre "Associer tiers"
6. Voir les tiers dans l'interface de la fenêtre "Associer tiers"
7. Cliquer sur un tiers
8. Voir les informations relatives à ce tiers
9. Voir que les informations ne sont pas modifiables
8. Voir que le bouton "Sauvegarder" n'est pas cliquable ou grisé ou invisible
9. Voir que seul le bouton "Fermer" est visible et cliquable pour fermer la fenêtre

**Comment by dcottenc** [comment]
Associer/dissocier testé et validé (Portail test RM)
