### ISSUE TITLE
Fiche PA ou Fiche OA & SA - Ajouter un tiers

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#34]
## Description

**En tant que** DAUH,
**Je souhaite** ouvrir une fiche de la couche PA, OA ou SA,
**Afin de** d'ajouter un tiers

## Règles : validation de la saisie

- Une validation est nécessaire sur les champs Type et Tiers
- Une API est nécessaire pour récupérer la liste des tiers existants
- Soumis à condition d'accès (droit d'ajout / modification)

## (Si) Tests / Cas

Ces tests sont à reproduire et valider pour les couches PA, OA et SA :
1. Cliquer sur une couche PA, OA ou SA
2. Cliquer sur une entité PA, OA ou SA visible sur la carte
3. Visualiser la fiche PA ou OA & SA
4. Voir que les champs ne sont pas modifiables
5. Cliquer sur le bouton "Associer tiers"
6. Cliquer sur le bouton "Ajouter un tiers"
7. Observer qu'une nouvelle ligne encadrée en rouge apparaît avec des informations manquantes par défaut
8. Sélectionner le type de tiers dans la liste
9. Sélectionner le tiers parmi une liste de tiers déjà disponible
10. Modifier le champ Tiers et ajouter un nouveau tiers
11. Cliquer sur "Enregistrer"
12. Observer que la ligne n'est plus encadrée et qu'un nouveau tiers consultable existe

**Comment by Gaetanbrl** [comment]
Données en cours de mise à jour.
Etapes à suivre : 
- Adaptation selon les données
- Tests
- Correctifs

**Comment by dcottenc** [comment]
Testé et validé (Portail test RM)
