### ISSUE TITLE
Fiche PA ou Fiche OA & SA - Modifier un tiers

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#35]
## Description

**En tant que** DAUH,
**Je souhaite** ouvrir une fiche de la couche PA, OA ou SA,
**Afin de** modifier, supprimer un tiers

## Règles : validation de la saisie

- Une validation est nécessaire sur les champs Type et Tiers
- Une API est nécessaire pour récupérer la liste des tiers existants
- Soumis à condition d'accès (droit d'ajout / modification)

## (Si) Tests / Cas

Ces tests sont à reproduire et valider pour les couches PA, OA et SA :
1. Cliquer sur une couche PA, OA ou SA
2. Cliquer sur une entité PA, OA ou SA visible sur la carte
3. Visualiser la fiche PA ou OA & SA
4. Voir que les champs ne sont pas modifiables
5. Cliquer sur le bouton "Associer tiers"
6. Cliquer sur le bouton "Modifier un tiers"
7. Observer que tous les champs Type et Tiers pour les tiers sont modifiables
8. Modifier un tiers dans la liste
9. Cliquer sur "Enregistrer"
10. Observer que le tiers modifié contient bien les nouvelles informations
11. Sur la ligne d'un tiers, cliquer sur "Supprimer"
12. Voir une fenêtre de confirmation s'affiche avec les boutons "Annuler", "Confirmer"
13. Cliquer sur "Valider la suppression"
14. Voir que le tiers est supprimé
15. Sur la ligne d'un tiers, cliquer sur "Supprimer"
16. Cliquer sur "Annuler" dans la fenêtre de confirmation
17. Voir que le tiers existe toujours

**Comment by Gaetanbrl** [comment]
En attente de livraison correctif API 1.2

**Comment by dcottenc** [comment]
@Gaetanbrl 

Vu avec Gaëtan le fonctionnement actuel de l'API n'est pas satisfaisant.
En effet,  le SW GET /operations/{operationId}/tiers ne contient aucun des id nécessaire au fonctionnement du CU
@dcottenc : Demande de correctif encours

**Comment by dcottenc** [comment]
@Gaetanbrl Les WS GET /operations/{operationId}/tiers et programme sont corrigés.

**Comment by dcottenc** [comment]
Testé et validé (Portail test RM)
