### ISSUE TITLE
Fiche OA & PA - Ajouter et retirer un document

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#36]
## Description

**En tant que** DAUH,
**Je souhaite** ouvrir une fiche de la couche PA, OA ou SA,
**Afin de** d'ajouter un document.

## Règles : validation de la saisie

- Une validation est nécessaire sur les champs Nom et Date et si un document n'est pas chargé
- Une API est nécessaire pour la sauvegarde des documents
- Soumis à condition d'accès (droit d'ajout / modification)

## (Si) Tests / Cas

Ces tests sont à reproduire et valider pour les couches PA, OA et SA :
1. Cliquer sur une couche PA, OA ou SA
2. Cliquer sur une entité PA, OA ou SA visible sur la carte
3. Visualiser la fiche PA (si entité PA cliquée) ou OA & SA (si entité OA ou SA cliquée)
4. Voir que les champs ne sont pas modifiables
5. Cliquer sur le bouton "Associer documents"
6. Voir que les documents sont initialisés avec les informations des documents existants pour cette entité
7. Cliquer sur le bouton "Ajouter un document"
8. Voir que les champs Nom et Date sont vides et encadrés en rouge (selon la validation)
9. Voir qu'un lien ou un bouton "Importer un document" est cliquable
10. Voir que le champ Diffusion est une case à cocher "Restreindre"
11. Voir que le champ Type est une liste de choix des types de documents
12. Voir que le bouton Enregistré est grisé si les champs obligatoires ne sont pas saisis
13. Saisir les informations et importer un document
14. Cliquer sur "Enregistrer"
15. Voir qu'un nouveau document et ses informations sont consultables dans la fenêtre du plugin "Associer un document"
16. Saisir et importer un nouveau document
17. Cliquer sur le bouton "Annuler" sur la ligne du document ou dans la fenêtre
18. Constater que le document n'apparaît pas parmi les autres documents (non sauvegardés)

**Comment by dcottenc** [comment]
En complément de la description ci-dessus.

**WS** 
```
POST /operations/{operationId}/documents pour les OA / SA
POST /programmes/{programmeId}/documents pour les PA
```

**Règle de gestion**
Les champs obligatoires sont Id de l'entité, Nom du document et type du document.
Le versionnement est automatique lors de la modification
L'utilisateur doit avoir le rôle contributeur ou réfèrent pour pouvoir exécuter le WS d'ajout. Il est recommandé de ne pas proposer le bouton d'ajout sinon.

**Contrôles**
Nous n'avons pas encore défini la taille maximum acceptée (tests en cours)

**Comment by Gaetanbrl** [comment]
> Les champs obligatoires sont Id de l'entité, Nom du document et type du document.

L'ID est à renseigner par le front ? Sur quel modèle ?

**Comment by Gaetanbrl** [comment]
@dcottenc merci c'est noté, l'id c'est l'id de l'OA ou du PA et non l'id du document importé.

**Comment by dcottenc** [comment]
@Gaetanbrl on est dans le cas de l'ajout, l'id est bien celui de l'OA ou du PA. 
L'ID du document va être générée par l'API après l'appel et il sera dans disponible dans la réponse

**Comment by Gaetanbrl** [comment]
@dcottenc dans la définition initiale de cette issue, il est question d'une checkbox "restreindre". Est-ce toujours d'actualité ?

**Comment by dcottenc** [comment]
@Gaetanbrl Initialement, on devait pouvoir limiter l'accès à certains documents (restreint à true) pour les profils avec les droits. Mais ce blocage "logiciel" par l'API n'est pas géré si l'utilisateur passe par la GED directement (dans un avenir lointain...).
Il n'a donc pas été implémenté. On verra comment vont évoluer les besoins liés à la GED...
Par contre, la date du document est un oubli de ma part car cela me semble assez indispensable en complément de la version.

**Comment by Gaetanbrl** [comment]
> Par contre, la date du document est un oubli de ma part car cela me semble assez indispensable en complément de la version.

Il faut la date d'import ou la date du document à saisir par l'utilisateur ?

**Comment by dcottenc** [comment]
La date d'import est automatique et elle est bien présente.
Par contre, il manque une date saisie par l'utilisateur qui je pense doit leur permettre de savoir si c'est la bonne version ou pas.

**Comment by Gaetanbrl** [comment]
@dcottenc lorsqu'on clique sur une entité qui n'a pas de document(s), j'ai ajouté ce contenu : 

![image](https://user-images.githubusercontent.com/16317988/159710782-eef34173-1289-4c0e-b568-fcc9400e0b05.png)

**Comment by Gaetanbrl** [comment]
Livré > A tester.

**Comment by dcottenc** [comment]
Testé et validé. Merci
