### ISSUE TITLE
Fiche PA ou Fiche OA & SA - Modifier un document

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#37]
## Description

**En tant que** DAUH,
**Je souhaite** ouvrir une fiche de la couche PA, OA ou SA,
**Afin de** modifier, supprimer un document

## Règles : validation de la saisie

- Une validation est nécessaire sur les champs Nom et Date et si un document n'est pas chargé
- Une API est nécessaire pour la sauvegarde des documents
- Soumis à condition d'accès (droit de modification)

## (Si) Tests / Cas

Ces tests sont à reproduire et valider pour les couches PA, OA et SA :
1. Cliquer sur une couche PA, OA ou SA
2. Cliquer sur une entité PA, OA ou SA visible sur la carte
3. Visualiser la fiche PA (si entité PA cliquée) ou OA & SA (si entité OA ou SA cliquée)
4. Voir que les champs ne sont pas modifiables
5. Cliquer sur le bouton "Associer documents"
6. Voir que les champs Nom, Date, Type sont bien initialisés avec les informations des documents de l'entité et que les documents sont consultables / téléchargeables
7. Voir que les champs sont directement modifiables et qu'un bouton "supprimer" est visible pour chaque document
8. Supprimer un document
9. Voir que le document n'est plus visible dans la liste des documents
10. Modifier les informations pour un document
11. Sauvegarder
12. Fermer la fenêtre
13. Cliquer sur le bouton "Associer document"
14. Voir que le document supprimé n'est pas visible et que les informations modifiées sont bien inscrites
15. Modifier un document
16. Cliquer sur "Annuler"
17. Cliquer sur "Fermer"
18. Cliquer sur "Associer document"
19. Voir que la modification n'a pas été prise en compte pour le dernier document modifié

**Comment by dcottenc** [comment]
En complément de la description ci-dessus.

**WS** 
Pour les OA / SA 
```
PUT /operations/{operationId}/documents/{documentId}
PUT /operations/{operationId}/documents/{documentId}/content
DELETE /operations/{operationId}/documents/{documentId}
```
Pour les PA
```
PUT /programmes/{programmeId}/documents/{documentId}
PUT /programmes/{programmeId}/documents/{documentId}/content
DELETE /programmes/{programmeId}/documents/{documentId}
```

**Règle de gestion**
Les champs obligatoires sont Id de l'entité, Nom du document et type du document.
Le versionnement est automatique lors de la modification
L'utilisateur doit avoir le rôle contributeur ou réfèrent pour pouvoir exécuter ces WS. Sinon il est recommandé de ne pas proposer la modification ou la suppression.
La modification s'effectue en utilisant deux WS, l'un pour les métadonnées et l'autre pour son contenu. A noter : dès que le métier aura défini son plan de classement, la modification des métadonnées se complexifiera.

**Contrôles**
Nous n'avons pas encore défini la taille maximum acceptée (tests en cours)

**Comment by Gaetanbrl** [comment]
> Les champs obligatoires sont Id de l'entité, Nom du document et type du document.

Les types ne sont pas fournis par l'API (liste vide)
https://portail-test.sig.rennesmetropole.fr/tabou2/types-documents?asc=true

En attente pour traitement @dcottenc .

**Comment by dcottenc** [comment]
@Gaetanbrl J'ai ajouté des types de document.
La table avait été vidée car il manque un attribut code

**Comment by Gaetanbrl** [comment]
@dcottenc lors de la modification d'un document ET son contenu, quel est le nom par défaut à utiliser ? 
- Est-ce que le nom du nouveau fichier doit remplacer le nom du document par défaut (avec possibilité de modification ensuite) ?
- Ou bien est-ce que le nom original doit être conservé ?

![image](https://user-images.githubusercontent.com/16317988/150942744-10388e3c-7eac-4b25-9b88-2f8d04a716db.png)

**Comment by dcottenc** [comment]
> lors de la modification d'un document ET son contenu, quel est le nom par défaut à utiliser ?

Au niveau fonctionnel, le besoin est bien de mettre à jour le nom lors d'une modification. Tout simplement car, le métier à l'habitude de mettre des infos dans le nom (date par exemple).
Au niveau technique, il me semble bien avoir vérifié que le remplacement du nom s'effectue sans soucis (grâce à la clé ID). Je ne peux pas vérifier l'impact sur la version actuellement (pb de droits en cours avec la DSI)

**Comment by dcottenc** [comment]
> Ma question porte sur la valeur lors de l'ajout d'un document dans la zone bleu (voir image précédente)

Pardon, je n'ai effectivement pas bien compris la question.
Ta solution actuelle me parait la plus pertinente. Je ne peux pas anticiper la réaction des métiers mais je prend le risque de le valider.

**Comment by dcottenc** [comment]
Testé et validé en VA, merci
