### ISSUE TITLE
Recherche - Critère Communes RM

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#49]
## Description

En tant que DAUH
Je souhaite pouvoir sélectionner une commune RM comme critère de recherche
Afin de filtrer l'affichage des entités du groupe Aménagements sur cette commune

## (Si) Règles spécifiques - Règles métiers

La liste déroulante contient la liste des noms des Communes RM. Elle est disponible avec l'API : communes?orderBy=nom&asc=true
Pour les trois couches OA, SA et PA, il convient d'appliquer le même filtre standard MapStore :
Filtre de couche avec :
- Couche cible : Limites communes
- Opération : intersecte
- Correspondance : Nom = Critère nom commune sélectionné

## (Si) Tests / Cas

1) Cliquer sur l’icône Tabou dans la barre d'outils à droite
2) Sélectionner l'onglet Recherche
3) Un champ Commune doit être présent avec la possibilité de choisir la commune à filtrer (à partir d'une liste déroulante qui contient toutes les communes triées par ordre alpha)
4) Sectionner une des communes
5) Valider la Recherche
6) les entités des couches OA, SA et PA doivent être filtrées dans l'emprise de la commune sélectionnée.

**Comment by Gaetanbrl** [comment]
@dcottenc est-il possible d'avoir un exemple de réponse (json) pour la requête `communes?orderBy=nom&asc=true` ?

Ceci afin de simuler une réponse (mock) dans l'API de développement utilisée par JDEV (spotlight).

**Comment by Gaetanbrl** [comment]
@dcottenc  Lors de la sélection de la commune, la récupération de la géométrie dans la couche `Commune `du contexte Tabou2 sera réalisée à partir du code de la commune (à préciser si on utilise le code insee, code postal...) selon ce que retourne l'API. 

Actuellement, la couche `Commune `contient le code INSEE et le code postal comme attributs.


```
Results for FeatureType 'https://public.sig.rennesmetropole.fr/ladm_terri:commune_emprise':
--------------------------------------------
objectid = 19
code_insee = 35210
nom = Pacé
commune_agglo = 1
x_centrbrg = 1345019.00000000
y_centrbrg = 7227417.00000000
shape = [GEOMETRY (Polygon) with 237 points]
code_postal = 35740
--------------------------------------------
```

De préférence, nous utiliserons le `code_insee` en attendant la disponibilité de l'API.

**Comment by dcottenc** [comment]
@Gaetanbrl L'objectid ne serait-il pas plus pertinent ? Il en serait de même pour tous les autres critères similaires qui ne disposent pas forcement d'un code mais toujours d'un ID. Normalement, il est bien prévu que les API retournent les ID.

**Comment by Gaetanbrl** [comment]
@dcottenc on a l'habitude de faire des jointure par code (l'objectid pouvant être un champ réservé selon le système, qui de plus peut être différent, voir dynamique si la couche est mise à jour), mais tant qu'on a la même valeur dans le retour d'API et la couche ce n'est pas un soucis, on pourra l'utiliser.

**Comment by Gaetanbrl** [comment]
@dcottenc je viens de vérifier et l'objectid est à proscrire pour une utilisation de ce type. Je conseil vivement de rester sur l'utilisation du code INSEE, à récupérer donc par l'API et que l'on pourra retrouver dans la couche.

**Comment by dcottenc** [comment]
**L'exemple de Response Body de l'API communes**

La valeur de la liste déroulante est le nom de la commune.
Le critère de filtre est le code INSEE

[https://app.zenhub.com/files/321427538/7c04c485-23e9-4065-9f1a-3098b6627950/download](https://app.zenhub.com/files/321427538/7c04c485-23e9-4065-9f1a-3098b6627950/download)
