### ISSUE TITLE
Recherche - Critère zonage PLUi

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#53]
## Description

En tant que DAUH
Je souhaite pouvoir sélectionner un zonage PLUi comme critère de recherche
Afin de filtrer l'affichage des entités du groupe Aménagements sur ce zonage.

## (Si) Règles spécifiques - Règles métiers

La liste déroulante contient la liste des noms des zonages PLUi. Elle est disponible avec l'API : plui?orderBy=libelle&asc=true
Pour les trois couches OA, SA et PA, il convient d'appliquer le même filtre standard MapStore :
Filtre de couche avec :
- Couche cible : zonage PLUi
- Opération : intersecte
- Correspondance : Nom = Critère zonage PLUi sélectionné

## (Si) Tests / Cas

1) Cliquer sur l’icône Tabou dans la barre d'outils à droite
2) Sélectionner l'onglet Recherche
3) Un champ zonage PLUi doit être présent avec la possibilité de choisir le zonage à filtrer (à partir d'une liste déroulante qui contient tous les zonages PLUi triés par ordre alpha)
4) Sectionner un des zonages PLUi
5) Valider la Recherche
6) les entités des couches OA, SA et PA doivent être filtrées dans l'emprise du zonage PLUi sélectionné.

**Comment by dcottenc** [comment]
**Exemple de Response Body de l'API ZonagePLUi**
[https://app.zenhub.com/files/321427538/e3977b4b-451f-4d2f-9b9b-6199e15b5fe3/download](https://app.zenhub.com/files/321427538/e3977b4b-451f-4d2f-9b9b-6199e15b5fe3/download)

La valeur de la liste déroulante est le libelle
Le critère de filtre est le libelle (type "LIKE")

**Comment by Gaetanbrl** [comment]
Le filtre connecté à l'API mock stoplight, mais ma couche est actuellement indisponible et non téléchargeable pour une utilisation dans l'environnement JDEV.

**Comment by Gaetanbrl** [comment]
Liste disponible, mais les données ne sont pas toutes disponibles et utilisée dans la couche actuellement en notre possession : 

https://portail.sig.rennesmetropole.fr/urba_docs_plui:plui_plan_zonage_simplifie

Est-ce la bonne couche, sinon laquelle récupérer @dcottenc ?

**Comment by Gaetanbrl** [comment]
Vu avec @dcottenc , l'appel pour récupérer l'ensemble des valeurs des zonages PLUI est tronqué et renvoi qu'une partie des valeurs.

API en cours de correction.
