### ISSUE TITLE
Recherche - Critère Etape PA

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#55]
## Description

En tant que DAUH
Je souhaite pouvoir sélectionner un étape PA comme critère de recherche
Afin de filtrer l'affichage des entités du groupe Aménagements qui contiennent ou sont des PA avec cette étape

## (Si) Règles spécifiques - Règles métiers

La liste déroulante contient la liste des noms des étapes d'une OA. Elle est disponible avec l'API : (API non disponible)
Les filtres standard MapStore à utiliser sont différents selon les couches :

Couches OA et SA :
Filtre de couche avec :
- Couche cible : PA
- Opération : intersecte
- Correspondance : Etape = Critère Etape PA sélectionné

CouchesPA :
Filtre attribut avec :
- Correspondance : Etape = Critère Etape PA sélectionné

## (Si) Tests / Cas

1) Cliquer sur l’icône Tabou dans la barre d'outils à droite
2) Sélectionner l'onglet Recherche
3) Un champ Etape PA doit être présent avec la possibilité de choisir l'étape à filtrer (à partir d'une liste déroulante qui contient toutes les étapes triées par ordre alpha)
4) Sectionner une des étapes
5) Valider la Recherche
6) les entités des couches OA, SA et PA doivent être filtrées par leurs intersections avec des PA avec cette étape

**Comment by dcottenc** [comment]
API liste déroulante non disponible

**Comment by dcottenc** [comment]
**Exemple de Response Body de l'API EtapePA**
[https://app.zenhub.com/files/321427538/96a14fc8-387c-4024-9888-bbc8a8afc561/download](https://app.zenhub.com/files/321427538/96a14fc8-387c-4024-9888-bbc8a8afc561/download)

La valeur de la liste déroulante est le nom de l'étape
Le critère de filtre est le code de l'étape

**Comment by Gaetanbrl** [comment]
Les champs sont manquants pour EtapeOA et EtapePA.
