### ISSUE TITLE
Recherche - Critère Type financement

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#56]
## Description

En tant que DAUH
Je souhaite pouvoir sélectionner un Type de financement comme critère de recherche
Afin de filtrer l'affichage des entités du groupe Aménagements qui contiennent des programmes Agapéo avec ce type de financement

## (Si) Règles spécifiques - Règles métiers

La liste déroulante contient la liste  des types de financement. Elle est disponible avec l'API : **(API non disponible)**
Pour les trois couches OA, SA et PA, il convient d'appliquer le même filtre standard MapStore :
Filtre de couche avec :
- couche cible : Programmes Agapéo **(non disponible)**
- Opération : intersecte
- Correspondance : TypeFin = Critère Type financement sélectionné

## (Si) Tests / Cas

1) Cliquer sur l’icône Tabou dans la barre d'outils à droite
2) Sélectionner l'onglet Recherche
3) Un champ Type financement doit être présent avec la possibilité de choisir le Type financement à filtrer (à partir d'une liste déroulante qui contient tous les Types financement triés par ordre alpha)
4) Sectionner une des Types financement
5) Valider la Recherche
6) les entités des couches OA, SA et PA doivent être filtrées par leurs intersections avec des programmes Agapéo avec ce type de financement

**Comment by dcottenc** [comment]
**Exemple de Response Body de l'API types_financement**
[https://app.zenhub.com/files/321427538/38e4e4cb-ffc1-4e0a-aadd-2c21fbaf752a/download](https://app.zenhub.com/files/321427538/38e4e4cb-ffc1-4e0a-aadd-2c21fbaf752a/download)

La valeur de la liste déroulante est le nom de l'étape
Le critère de filtre est le code de l'étape

**Comment by Gaetanbrl** [comment]
Filtre connecté à l'API Mock stoplight JDEV, mais la couche n'est pas disponible.
