### ISSUE TITLE
Recherche - Critère Nature

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#60]
## Description

En tant que DAUH
Je souhaite pouvoir sélectionner une Nature comme critère de recherche
Afin de filtrer l'affichage des entités du groupe Aménagements sur cette nature.

## (Si) Règles spécifiques - Règles métiers

La liste déroulante contient la liste des types de nature. Elle est disponible avec l'API : `/natures`
Pour les trois couches OA, SA et PA, il convient d'appliquer le même filtre standard MapStore :

Filtre de type attributaire sur le champ `nature`.

La liste déroulante contient la liste des noms des quartiers de Rennes. Elle est disponible avec l'API : quartiers?orderBy=nom&asc=true
Pour les trois couches OA, SA et PA, il convient d'appliquer des filtres de types différents :

OA, filtre de type attributaire sur le champ `nature` avec la Nature sélectionnée.

SA, PA, filtre de type spatial avec :
- Couche cible : OA avec le filtre sur la Nature sélectionnée
- Opération : intersecte

## (Si) Tests / Cas

1) Cliquer sur l’icône Tabou dans la barre d'outils à droite
2) Sélectionner l'onglet Recherche
3) Une liste de sélection `Nature` doit être présent avec la possibilité de choisir la nature à filtrer (à partir d'une liste déroulante qui contient toutes les natures triées par ordre alpha - ASC).
4) Sectionner une des nature
5) Valider la Recherche
6) les entités des couches OA, SA et PA doivent être filtrées selon leur appartenance à une OA avec la nature sélectionnée.

**Comment by Gaetanbrl** [comment]
@dcottenc 

La liste est chargée des valeurs retournées par l'API.

Le filtre est cependant inutilisable tant que les données carto ne détiennent pas les mêmes natures que les valeurs retournées par l'API.

**Comment by Gaetanbrl** [comment]
Besoin d'ajouter des OA, PA, SA pour tests, correctifs et validation

**Comment by dcottenc** [comment]
> La liste est chargée des valeurs retournées par l'API.
> Le filtre est cependant inutilisable tant que les données carto ne détiennent pas les mêmes natures que les valeurs retournées par l'API.

L'API GET /operations/emprises prend dorénavant l'ID de la nature disponible dans la liste chargée pour la liste déroulante.
