### ISSUE TITLE
Navigation - Afficher la toolbar avec Tabou2

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#67]
## Description

Lorsqu'on ouvre un plugin, la toolbar native reste sous le plugin.
Avec les plugins natifs MapStore, cette toolbar est déplacée sur la gauche selon la largeur du panel.

## Note technique

La gestion du placement (propriété CSS) de la toolbar se fait via l'action UPDATE_MAP_LAYOUT.
Nativement, **MapStore2 ne prévoit pas que la toolbar soit visible avec un plugin custom**.

Il faut donc créer une EPICS sui réagira à cette action via RxJs et Redux.

## Reproduction

1. Aller sur le contexte Tabou2
2. Cliqué sur le logo (bouton) de Tabou2 dans la barre d'outils
3. Constater que le plugin est visible
4. Constater que la toolbar n'est plus visible

**Comportement attendu / Exptected behavior**

La toolbar doit rester visible et utilisable lorsque le plugin Tabou2 est ouvert.

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - OS: *
 - Navigateur: *
 - Version: <= 1.0

**Comment by pierrejego** [comment]
En complément nous pourrions peut être revoir le placement de Tabou2 pour ne pas cacher les menus du haut ( catalogue, etc....)
