### ISSUE TITLE
UI - Affichage fiche PA

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#69]
## Description

**En tant que** DAUH, 
**Je souhaite** afficher les informations d'un PA
**Afin de** les consulter ou de les modifier

## (Si) Règles spécifiques - Règles métiers

L'interface se compose de bloc de données qui peuvent être réduits ou développés indépendamment.

**Bloc Identification**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| ID | Integer | Champ | X | X | /programmes/{programmeId} | id |
| Code | String | Champ |  | X | /programmes/{programmeId} | code |
| Commmune | string | Champ (multi valeur) | X |  |  |  |
| Nature | String | Champ | X | X | /operations/{operationId} | nature |
| Opération | String | Champ |  | X | /operations/{operationId} | nom |
| Nom | String | Champ |  | X | /programmes/{programmeId} | nom |
| Diffusion restreinte | Booleen | Checkbox | X |  | /programmes/{programmeId} | diffusionRestreinte |
| N° ADS | String | Champ |  |  | /programmes/{programmeId} | numAds |

**Bloc Description**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Programme | Texte | Textuel |  |  | /programmes/{programmeId} | programme |
| Descriptif | Texte | Textuel |  |  | /programmes/{programmeId} | description |

**Bloc Gouvernance**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Promoteur | string | Champ (multi valeur) | X |  | /programmes/{programmeId}/tiers | Nom(s) |
| Maître d'œuvre | string | Champ (multi valeur) | X |  | /programmes/{programmeId}/tiers | Nom(s) |

**Bloc Suivi opérationnel**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Étape | string | Liste déroulante |  | X | /programmes/{programmeId} | etape.libelle |
| date livraison  | Date | Calendar |  |  | /programmes/{programmeId} | livraisonDate |
| date cloture | Date | Calendar |  |  | /programmes/{programmeId} | clotureDate |

**Bloc Instruction Droit des Sols**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Date ADS | Date | Calendar |  |  | /programmes/{programmeId} | adsDate |
| Date DOC | Date | Calendar |  |  | /programmes/{programmeId} | docDate |
| Date DAACT | Date | Calendar |  |  | /programmes/{programmeId} | datDate |
| Détail ADS | Liste | Tableau | X |  | /programmes/{programmeId}/permis | (cf. WS) |

Tableau données DDC (/programmes/{programmeId}/permis)

| N° ADS | Date ADS | Date DOC | Date DAACT |
| --- | --- | --- | --- | 
| 03505505U1086 | 27/05/2015 |  |  |

**Bloc Programmation Habitat**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Année attribution foncière | Integer | Champ |  |  | /programmes/{programmeId} | attributionFonciereAnnee |
| Date attribution | Date | Calendar |  |  | /programmes/{programmeId} | attributionDate |
| Date commercialisation | Date | Calendar |  |  | /programmes/{programmeId} | commercialisationDate |
| Logement total | Integer | Champ |  |  | /programmes/{programmeId} | logementsTotal |
| Accession aidée | Integer | Champ |  |  | /programmes/{programmeId} | logementsAccessAidePrevu |
| Accession libre | Integer | Champ |  |  | /programmes/{programmeId} | logementsAccessLibrePrevu |
| Accession maitrisée | Integer | Champ |  |  | /programmes/{programmeId} | logementsAccessMaitrisePrevu |
| Locatif Aidé | Integer | Champ |  |  | /programmes/{programmeId} | logementsLocatifAidePrevu |
| Locatif régulé  HLM | Integer | Champ |  |  | /programmes/{programmeId} | logementsLocatifReguleHlmPrevu |
| Locatif régulé privé | Integer | Champ |  |  | /programmes/{programmeId} | logementsLocatifRegulePrivePrevu |

Tableau données Agapéo (/programmes/{programmeId}/agapeo)

| Année prog | N° dossier | Loc. Aidé | Loc. rég. HLM | Loc. rég. privé | Acc. aidée |
| --- | --- | --- | --- | --- | --- | 
| 2007 | 621 | 24 | 0 | 0 | 0 |

## (Si) Tests / Cas

Ces tests sont à reproduire et valider pour les couches PA :
1. Cliquer sur une couche PA
2. Cliquer sur une entité PA visible sur la carte
3. Visualiser la fiche PA dans le plugin Tabou, onglet "identifier"
4. Vérifier que les blocs et les attributs décrits ci-dessus sont tous visibles 
5. Vérifier que les attributs "ReadOnly" sont en lecture seule

**Comment by Gaetanbrl** [comment]
- [x] Affichage sans infos pour le programme cliqué (UI seul)
- [x] Affichage avec infos du programme cliqué
- [x] Saisie possible
- [ ] Sauvegarde des modifications
- [ ] Annuler la saisie (retour aux infos par défaut)
- [ ] Validation
- [ ] Gestion des droits utilisateurs (modification possible ou pas)

**Comment by dcottenc** [comment]
**Mise à jour de la description**
Ajout des tableau Agapéo et DDS. 
Remarque : à valider par la MOA en démo

**Comment by Gaetanbrl** [comment]
@dcottenc est-ce que ce postionnement est correct ? 

![image](https://user-images.githubusercontent.com/16317988/119159982-16f55f80-ba58-11eb-9610-f9b0510fcf63.png)
