### ISSUE TITLE
UI - Affichage fiche OA / SA

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#70]
## Description

**En tant que DAUH**
**Je souhaite afficher les informations d'une OA ou d'un SA**
**Afin de les consulter ou de les modifier**

## (Si) Règles spécifiques - Règles métiers

L'interface se compose de bloc de données qui peuvent être réduits ou développés indépendamment.

**Bloc Identification**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| ID | Integer | Champ | X | X | /operations/{operationId} | id |  |  |
| Code | String | Champ |  | X | /operations/{operationId} | code |  |  |
| Commune | string | Champ (multi valeur) | X |  |  |  |  |  |
| Nature | String | Champ | X | X | /operations/{operationId} | nature.libelle |  |  |
| Nom | String | Champ |  | X | /operations/{operationId} | nom |  |  |
| Diffusion restreinte | Booleen | Checkbox | X |  | /operations/{operationId} | diffusionRestreinte |  |  |
| N° ADS | String | Champ |  |  | /operations/{operationId} | numAds |  |  |

**Bloc Description**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Opération | Texte | Textuel |  |  | /operations/{operationId} | operation |  |  |
| Descriptif | Texte | Textuel |  |  | /operations/{operationId} | description |  |  |
| Consommation espace | Texte | Liste déroulante |  |  | /operations/{operationId} | consommationEspace.Libelle |  |  |
| Vocation | Texte | Liste déroulante |  |  | /operations/{operationId} | vocation.libelle |  |  |
| Surface totale | Real | Champ |  |  | /operations/{operationId} | surfaceTotale |  |  |

**Bloc Gouvernance**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Décision | Texte | Liste déroulante |  |  | /operations/{operationId} | decision.libelle |  |  |
| Maitrise d'ouvrage | Texte | Liste déroulante |  |  | /operations/{operationId} | maitriseOuvrage.libelle |  |  |
| Mode d'aménagement | Texte | Liste déroulante |  |  | /operations/{operationId} | modeAmenagement.libelle |  |  |
| Aménageur | string | Champ (multi valeur) | X |  | /operations/{operationId}/tiers |  |  |  filtrer type tiers 1 |
| Maître d'œuvre | string | Champ (multi valeur) | X |  | /operations/{operationId}/tiers |  |  | filtrer type tiers 2 |

**Bloc Suivi opérationnel**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Étape | string | Liste déroulante |  | X | /operations/{operationId} | etape.libelle |  |  |
| Date autorisation | Date | Calendar |  |  | /operations/{operationId} | autorisationDate |  |  |
| Date démarrage | Date | Calendar |  |  | /operations/{operationId} | operationnelDate |  |  |
| Date clôture | Date | Calendar |  |  | /operations/{operationId} | clotureDate |  |  |

**Bloc Programmation Habitat**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Nombre de Logement | Integer | Champ |  |  | /operations/{operationId} | nbLogementsPrevu |  |  |
| PLH-Nombre de logements prévus | Integer | Champ |  |  | /operations/{operationId} | plhLogementsPrevus |  |  |
| PLH-Nombre de logements livrés | Integer | Champ |  |  | /operations/{operationId} | plhLogementsLivres |  |  |

**Bloc Programmation activités**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| SCoT | Booleen | Checkbox |  |  | /operations/{operationId} | ql2 |  |  |
| Territoire | Texte | Liste déroulante |  |  | /operations/{operationId} | ql3 |  |  |

**Bloc Secteurs et programmes liés**

| Attribut | Type champ | Affichage | Read only | Mandatory | API Nom | API Reference |
| --- | --- | --- | --- | --- | --- | --- | 
| Liste des programmes de L'OA | Liste | Tableau | X |  | /operations/{operationId}/programmes | [nom, promoteur, etape, DateLiv] |  |  |

## (Si) Tests / Cas

Ces tests sont à reproduire et valider pour les couches OA / SA :
1. Cliquer sur une couche OA ou SA
2. Cliquer sur une entité OA / SA visible sur la carte
3. Visualiser la fiche OA / SAdans le plugin Tabou, onglet "identifier"
4. Vérifier que les blocs et les attributs décrits ci-dessus sont tous visibles 
5. Vérifier que les attributs "ReadOnly" sont en lecture seule

**Comment by Gaetanbrl** [comment]
@dcottenc, pour Aménageur et Maître d'œuvre du bloc "Gouvernance" il faut appeler le service : 
/operations/{operationId}/tiers

Ce service renvoi la liste des tiers. 

Que dois-je afficher ?

**Comment by Gaetanbrl** [comment]
@dcottenc le champ commune du bloc "Identification" n'existe pas dans les OA, SA, PA.
C'est un croisement spatial qui est réalisé pour la recherche sur le critère commune.

D'où l'absence de précision du service dans le tableau j'imagine.

Faut-il prévoir un appel au geoserver ?

**Comment by Gaetanbrl** [comment]
Pour le bloc "Gouvernance" et l'appel des aménageur et promoteur,

Il faut filtrer dans le code JS les tiers de type 1et 2 pour récuéprer les deux types et ensuite les afficher via un champ simple avec séparateur (;) pour chaque tiers retourné.

**Comment by Gaetanbrl** [comment]
- [ ] Affichage sans infos pour l'opération cliquée (UI seul)
- [ ] Affichage sans infos pour le programme cliquée (UI seul)
- [ ] Affichage avec infos de l'opération cliquée
- [ ] Affichage avec infos du secteur cliqué
- [ ] Affichage avec infos pour le programme cliqué
- [ ] Saisie possible
- [ ] Sauvegarde des modifications
- [ ] Annuler la saisie (retour aux infos par défaut)
- [ ] Validation
- [ ] Gestion des droits utilisateurs (modification possible ou pas)

**Comment by Gaetanbrl** [comment]
En attente de test AGAPEO / DDC
