### ISSUE TITLE
CU - Ajouter opérations / secteurs (OA / SA)

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#71]
## Description

**En tant que DAUH**
**Je souhaite ajouter une OA / SA**
**Afin de les visualiser/gérer dans Tabou**

## (Si) Règles spécifiques - Règles métiers

Le principe d'ajout dans Tabou consiste à associer une emprise existante dans le référentiel SIG et une entité de suivi dans Tabou. L'ID de cette dernière est mis à jour dans la table correspondante de l'emprise.
La difficulté pour les OA / SA est que leurs emprises sont stockées dans plusieurs tables en fonction de leur type/nature.

**Cas d'usage**
Les étapes doivent s'effectuer séquentiellement
Étape 1 : Sélection du type (OA ou SA)
Étape 2 : Sélection de la nature
Étape 3 : Sélection de l'emprise
Étape 4 : Sélection ou saisie des attributs (Code, Nom, Secteur, Étape)
Étape 5 : Enregistrement de la création (création de l'entité Tabou, ajout de l'ID_Tabou dans la table de l’emprise correspondante, actualisation de la fenêtre carto (si possible centrage sur l'entité créée))

**Implémentation du CU nominal**
Étape 1 : Accessible depuis le plugin Tabou, onglet création. Sélection à partir d'une liste déroulante
Étape 2 : Sélection à partir d'une liste déroulante (API Nature opération)
Étape 3 : Sélection à partir d'une liste déroulante (API /operations/emprises avec en paramètre EstSecteur = false si OA, true si SA, et la Nature sélectionnée)
Étape 4 : Utilisation des champs de saisie ou de sélection pour renseigner les autres attributs
Étape 5 : Utilisation du bouton enregistrer (si l'utilisateur clique sur un élément de navigation du plugin, proposer l'enregistrement par un popup)

**Implémentation du CU alternatif (facultatif)**
Étape 1/2/3 : Sélection d'une couche du groupe entités d'aménagement (OA / SA) et cliquer sur l'emprise concernée (visible mais sans attributs) => ouverture du pluging Tabou (fonctionnement nominal) mais l'entité n'ayant pas d'ID_Tabou, c'est l'onglet création qui s'ouvre avec une présélection du type, de la nature et de l'emprise concernée.
Étape 4 et 5 : identiques CU nominal

## (Si) Tests / Cas

Exécution des étapes des CU nominal et alternatif => Résultat création de l'entité de suivi Tabou

**Comment by Gaetanbrl** [comment]
> ouverture du pluging Tabou (fonctionnement nominal) mais l'entité n'ayant pas d'ID_Tabou, c'est l'onglet création qui s'ouvre avec une présélection du type, de la nature et de l'emprise concernée.

@dcottenc , le type, `nature` et `emprise` sont-ils déjà présents comme valeur d'attribut d'une emprise sans ID_Tabou ? Est-ce toujours le cas ?

**Comment by Gaetanbrl** [comment]
> Implémentation du CU nominal
Étape 1 : Accessible depuis le plugin Tabou, onglet création. Sélection à partir d'une liste déroulante

Est-ce bien la sélection du type OA / SA ? Il manque peut-être un morceau dans la phrase

**Comment by Gaetanbrl** [comment]
Affichage de l'onglet Ajout : 

![image](https://user-images.githubusercontent.com/16317988/110310749-2c372200-8003-11eb-9ba3-38cfcb850cab.png)

**Comment by Gaetanbrl** [comment]
Ajout d'une OA / SA : 

![image](https://user-images.githubusercontent.com/16317988/110312586-93ee6c80-8005-11eb-814c-e65aa4b22e6d.png)

**Comment by dcottenc** [comment]
> @dcottenc , le type, nature et emprise sont-ils déjà présents comme valeur d'attribut d'une emprise sans ID_Tabou ? Est-ce toujours le cas ?

@Gaetanbrl :
=> le type et l'emprise sont connus, le clic s’effectue sur une des trois couches OA, PA et SA à partir de son emprise.
=> pour les OA, la nature sera fournie par la couche. En effet, cette couche est constituée par l'union des couches zac, za et En diffus. Un attribut Nature sera présent

**Comment by dcottenc** [comment]
>> Implémentation du CU nominal
    Étape 1 : Accessible depuis le plugin Tabou, onglet création. Sélection à partir d'une liste déroulante

> Est-ce bien la sélection du type OA / SA ? Il manque peut-être un morceau dans la phrase

@Gaetanbrl
Ce n'est peut-être pas très clair mais les étapes de l’implémentation se référent à celles du cas d'usage. Ici la sélection porte sur les OA / SA comme indiqué dans l'étape 1 du CU.

**Comment by dcottenc** [comment]
> Ajout d'une OA / SA : 

@Gaetanbrl : c'est ok pour moi. Attention EstSecteur (secteur = Oui (SA) ou Non (PA)) est un booleen (pas de liste)

**Comment by Gaetanbrl** [comment]
l'API prévoit que les emprises pour une OA ne peuvent être retournée que si les infos nature ET EstSecteur sont saisie comme paramètre de requête.
Ce fonctionnement ne correspond pas à l'interface actuellement envisagée @dcottenc qui doit permettre (selon le schéma discuté) : 

* De choisir la nature pour limiter le nombre d'emprise
* De chosir ensuite l'emprise
* De saisir ensuite si c'est emprise est secteur ou non

Test : 

https://portail-test.sig.rennesmetropole.fr/tabou2/operations/emprises?nature=ZA&estSecteur=true

**Comment by dcottenc** [comment]
> l'API prévoit que les emprises pour une OA ne peuvent être retournée que si les infos nature ET EstSecteur sont saisie comme paramètre de requête.
Ce fonctionnement ne correspond pas à l'interface / workflow actuellement envisagée @dcottenc qui doit permettre (selon le schéma discuté) :

Effectivement, la sélection de l'attribut EstSecteur est nécessaire pour appeler l'API (avec la nature). L'API a besoin de cette information car les tables des emprises sont différentes entre les opérations et les secteurs.

**Comment by Gaetanbrl** [comment]
Merci @dcottenc, du coup j'ai mis la checkbox et je propose de changer le message de l'alert comme suit : 

![image](https://user-images.githubusercontent.com/16317988/113993763-12346d80-9855-11eb-811f-3235b61e6b1f.png)

**Comment by Gaetanbrl** [comment]
@dcottenc voici l'enchaînement entre les écran identifier / ajouter à valider :

![CU_ADD](https://user-images.githubusercontent.com/16317988/114740071-cba9ac00-9d49-11eb-8123-2d53c588474c.gif)

**Comment by Gaetanbrl** [comment]
en attente pour même raison que #21
