### ISSUE TITLE
CU - Ajouter programme (PA)

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#72]
## Description

**En tant que DAUH**
**Je souhaite ajouter un programme (PA)**
**Afin de les visualiser/gérer dans Tabou**

## (Si) Règles spécifiques - Règles métiers

Le principe d'ajout dans Tabou consiste à associer une emprise existante dans le référentiel SIG et une entité de suivi dans Tabou. L'ID de cette dernière est mis à jour dans la table correspondante de l'emprise.
La difficulté pour les PA est l’association attributaire avec l'OA parent. 

**Cas d'usage**
Étape 1 : Sélection de l'emprise
Étape 2 : Sélection de l'OA parent (recherche par nom)
Étape 3 : Sélection ou saisie des attributs (Code, Nom, Étape)
Étape 4 : Enregistrement de la création (création de l'entité Tabou, ajout de l'ID_Tabou dans la table de l’emprise correspondante, actualisation de la fenêtre carto (si possible centrage sur l'entité créée))

**Implémentation du CU nominal**
Étape 1 : Sélection de l’emprise à partir d'une liste déroulante (API /programmes/emprises)
Étape 2 : Sélection de l'OA parent à partir d'une liste déroulante (API /operations avec les critères Secteur = False et Nom)
Étape 3 : Utilisation des champs de saisie ou de sélection pour renseigner les autres attributs
Étape 4 : Utilisation du bouton enregistrer (si l'utilisateur clique sur un élément de navigation du plugin, proposer l'enregistrement par un popup)

**Implémentation du CU alternatif (facultatif)**
Étape 1 : Sélection de la couche Programmes du groupe entités d'aménagement et cliquer sur l'emprise concernée (visible mais sans attributs) => ouverture du pluging Tabou (fonctionnement nominal) mais l'entité n'ayant pas d'ID_Tabou, c'est l'onglet création qui s'ouvre avec une présélection du type et de l'emprise concernée.
Étape 3, 4 et 5 : identiques CU nominal

## (Si) Tests / Cas

Exécution des étapes des CU nominal et alternatif => Résultat création de l'entité de suivi Tabou

**Comment by Gaetanbrl** [comment]
> Étape 2 : Sélection de l'OA parent (recherche par nom)

L'API prévoit-elle une recherche type autocomplétions (ex : LIKE %string%) pour récupérer l'OA parent ?

**Comment by Gaetanbrl** [comment]
> Étape 1 : Sélection de la couche Programmes du groupe entités d'aménagement et cliquer sur l'emprise concernée (visible mais sans attributs) => ouverture du pluging Tabou

Question technique : 
Pouvoir ouvrir le plugin sur une action non liée au plugin. Seul un clic sur le bouton du module permet actuellement d'activer le module.

Une analyse doit être réalisée pour être certain que cette action est réalisable. Autrement, le plugin devra être déjà ouvert pour l'ajout d'un d'un programme PA.

**Comment by Gaetanbrl** [comment]
Ajout des attributs + sauvegarde : 

![image](https://user-images.githubusercontent.com/16317988/110313311-8a193900-8006-11eb-802e-de4cb3cd8eb7.png)

**Comment by dcottenc** [comment]
>> Étape 2 : Sélection de l'OA parent (recherche par nom)

> L'API prévoit-elle une recherche type autocomplétions (ex : LIKE %string%) pour récupérer l'OA parent ?

@Gaetanbrl : l'API permet la recherche avec un caractère générique mais il me semble qe Pierre avait indiqué que c'était le composant qui gérait l'autocompletion

**Comment by Gaetanbrl** [comment]
> l'API permet la recherche avec un caractère générique mais il me semble qe Pierre avait indiqué que c'était le composant qui gérait l'autocompletion

Les deux sont possibles. Etant donné que la liste doit de toute façon faire un appel pour récupérer toutes les valeurs à son initialisation, alors l'utilisation du composant évite un second appel, ce qui reste favorable autant que possible.

**Comment by Gaetanbrl** [comment]
@dcottenc quelle est l'API à appeler pour récupérer la liste des emprises programmes ?

Je ne vois pas d'API programmes/emprises dans l'API.

**Comment by dcottenc** [comment]
> Je ne vois pas d'API programmes/emprises dans l'API.

Oui, nous avions évoqué son absence lors de notre point sur les API. Elle fera partie de la prochaine livraison

**Comment by Gaetanbrl** [comment]
> Oui, nous avions évoqué son absence lors de notre point sur les API. Elle fera partie de la prochaine livraison

Ca marche, j'avais oublié ce point je pense... merci .

**Comment by Gaetanbrl** [comment]
Cors de l'objet à envoyer en paramètre pour la création d'un PA.

Objet variable renseigné par saisie UI et géré par le front : 

* Nature
* IdEmprise
* Nom
* Code
* Etape

Les autres valeurs étants gérés par l'API (backend) mais saisi selon ce corps à titre "indicatif" en attendant le correctif de l'API.

```
{
  "adsDate": "2021-02-24T15:15:22.381Z",
  "adsDatePrevu": "2021-02-24T15:15:22.381Z",
  "attributionDate": "2021-02-24T15:15:22.381Z",
  "attributionFonciereAnnee": 0,
  "clotureDate": "2021-02-24T15:15:22.381Z",
  "commercialisationDate": "2021-02-24T15:15:22.381Z",
  "createDate": "2021-02-24T15:15:22.381Z",
  "createUser": "string",
  "datDate": "2021-02-24T15:15:22.381Z",
  "datDatePrevu": "2021-02-24T15:15:22.381Z",
  "description": "string",
  "diffusionRestreinte": false,
  "docDate": "2021-02-24T15:15:22.381Z",
  "docDatePrevu": "2021-02-24T15:15:22.381Z",
  "etape": {    
    "id": 1  
  },
  "logementsAccessAide": 0,
  "logementsAccessAidePrevu": 0,
  "logementsAccessLibrePrevu": 0,
  "logementsAccessMaitrise": 0,
  "logementsAccessMaitrisePrevu": 0,
  "logementsLocatifAide": 0,
  "logementsLocatifAidePrevu": 0,
  "logementsLocatifReguleHLM": 0,
  "logementsLocatifReguleHlmPrevu": 0,
  "logementsLocatifRegulePrive": 0,
  "logementsLocatifRegulePrivePrevu": 0,
  "logementsTotal": 0,
  "modifDate": "2021-02-24T15:15:22.382Z",
  "modifUser": "string",
  "numAds": "string",
  "operationId": 7,
  "nom": "prog2",
  "programme": "prog2",
  "code": "prog2"
}
```

**Comment by Gaetanbrl** [comment]
en attente : idem #71

**Comment by Gaetanbrl** [comment]
Vu avec @dcottenc  ce jour pour le corps de l'objet à envoyer : 

```
{
  "operationId": 84,
  "code": "o1-0305",
  "nom": "O1",
  "programme": "prog2"
  "diffusionRestreinte": false,
  "etape": {
    "id":1
               },
  "numAds": 3111,
}
```
