### ISSUE TITLE
UI - Onglet Ajout opérations / secteurs (OA / SA)

### ISSUE THREAD

**Issue by dcottenc** [sigrennesmetropole/geor_tabou2_front#73]
## Description

**En tant que DAUH**
**Je souhaite pouvoir disposer de l'affichage des champs nécessaires à la création d'une OA / SA**
**Afin de pouvoir les renseigner avant enregistrement**

## (Si) Règles spécifiques - Règles métiers

L'affichage des champs répond aux besoins des étapes 2 à 4 du CU d'ajout d'une OA / SA #71
**Il est important de noter que ces étapes doivent se dérouler séquentiellement. En effet, la liste déroulante citée à l'étape 2 ne peut être constituée que si les saisies des 2 étapes précédentes sont effectuées.**
A noter également qu'il est possible que les champs des étapes 2 et 3 (Type et Nature) puissent être pré-renseignés (cf. CU alternatif #71).

| Attribut | 

| Attribut | Type champ | Affichage | Read only | Mandatory | API liste déroulante | Default |
| --- | --- | --- | --- | --- | --- | --- | 
| Type | String | Liste déroulante |  | X | OA, SA |  |
| Nature | String | Liste déroulante |  | X | /nature |  |
| Emprise | String | Liste déroulante |  | X | /operations/emprises |  |
| Code | String | Champ |  | X |  |  |
| Nom | String | Champ |  | X |  |  |
| Etape | String| Liste déroulante |  | X | /etape | 

## (Si) Tests / Cas

1. Suivre les étapes du CU #71
2. A l'étape 2 : vérifier la sélection du type (OA ou SA)
3. A l'étape 3 : vérifier la sélection de la nature
4. A l'étape 4 : vérifier que la liste déroulante des emprises contient des emprises de type et de nature sélectionnés. Vérifier la sélection d'une emprise
5. Vérifier que les autres attributs décrits ci-dessus sont bien présents et modifiables

**Comment by Gaetanbrl** [comment]
Corps de l'objet à envoyer (en attendant le correctif API) pour création OA.

Champs à modifié selon saisie UI : 
* nature
* Type (EstSecteur)
* IdEmprise
* Nom
* Code
* Etape

```
{
  "autorisationDate": "2021-02-24T15:15:36.426Z",
  "clotureDate": "2021-02-24T15:15:36.426Z",
  "code": "op1",
  "nom": "op1",
  "consommationEspace": {    
    "id": 1
  },
  "createDate": "2021-02-24T15:15:36.426Z",
  "createUser": "string",
  "decision": {    
    "id": 1
  },
  "description": "string",
  "diffusionRestreinte": false,
  "etape": {   
    "id": 1
  },
  "id": 0,
  "idEmprise": 1,
  "maitriseOuvrage": {   
    "id": 1
  },
  "modeAmenagement": {  
    "id": 1
  },
  "modifDate": "2021-02-24T15:15:36.426Z",
  "modifUser": "string",
  "nature": { 
    "id": 1
  },
  "nbEntreprise": 0,
  "nbLogementsPrevu": 0,
  "nbSalarie": 0,
  "numAds": "string",
  "operation": "string",
  "operationnelDate": "2021-02-24T15:15:36.426Z",
  "plhLogementsLivres": 0,
  "plhLogementsPrevus": 0,
  "ql1": "string",
  "ql2": false,
  "ql3": "string",
  "secteur": false,
  "surfaceTotale": 0,
  "vocation": {  
    "id": 1
  }
}
```

**Comment by Gaetanbrl** [comment]
Corps de l'objet à envoyer avec le strict minimum requis : 

```
{
  "diffusionRestreinte": false,
  "nature": {
    "id": 1
  },
  "idEmprise": 84,
  "code": "2015-01",
  "nom": "Baud Chardonnet",
  "operation": "Baud Chardonnet sera un quartier d'habitat mariant une diversité de formes urbaines, de la maison de ville aux "émergences" ouvertes sur le fleuve et la ville en passant par des immeubles de moyenne hauteur... ",
  "description": "A 2 km à l'est du centre-ville, Baud Chardonnet offre à Rennes une possibilité inédite : celle de retrouver un contact direct au fleuve, en plein cœur de ville.",
  "nbLogementsPrevu": 0,
  "secteur": false,
  "surfaceTotale": 0,
  "consommationEspace": {  
    "id": 1
  },
  "decision": {  
    "id": 1
  },
  "etape": {  
    "id": 1
  },
  "maitriseOuvrage": {  
    "id": 1
  },
  "modeAmenagement": {
    "id": 1
  },
  "vocation": {
    "id": 1
  }
}
```

**Comment by Gaetanbrl** [comment]
En attente update des couches carto pour tests et finalisation UI / comportement.
