### ISSUE TITLE
Edition - Associer un tiers

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#80]
## Description

Décrire ici ce qui est attendu par un personnage clairement identifié.

**En tant que** DAUH
**Je souhaite** associer un tier pour une entité,
**Afin de** de lier un tier et l'entité (OA, PA, SA).

## (Si) Règles spécifiques - Règles métiers

Une liste déroulante permet de choisir le tiers parmis les tiers existants (api /programmes/id/tiers ou /operations/id/tiers).
Seuls les tiers actifs sont affichés dans la liste est sélectionnable.

## (Si) Tests / Cas

1. Afficher la liste des tiers
2. Cliquer sur "Associer un tiers"
3. Voir le nouveau tiers sélectionnable dans une liste
4. Pouvoir choisir un tiers dans la liste
5. Sélectionner un tiers
6. Voir que le tiers est dans la liste
7. Cliquer sur "Associer un tier" et voir le nouveau tiers sélectionnable dans une liste
8. Cliquer sur "Annuler" et voir que le tiers n'apparaît pas

## Complément (graphique, capture, schéma, etc.)

![tiers_associate](https://user-images.githubusercontent.com/16317988/113436964-09bbdd00-93e6-11eb-845e-f7f41a09f96b.gif)

**Comment by Gaetanbrl** [comment]
- [ ] Voir uniquement les tiers pour l'OA ou PA identifié
- [ ] Voir le bouton "Associer un tiers"
- [ ] Voir les tiers associables dans une liste déroulantes et uniquement les tiers actifs
- [ ] Pouvoir annuler l'association
- [ ] Ne pas avoir à recharger la page manuellement pour voir le nouveau tiers associé
- [ ] Ne pas avoir à recharger la page manuellement pour voir l'annulation de l'association (avant association)
- [ ] La sélection dans la liste réalise directement l'association
- [ ] Lors de la sélection, il sera obligatoire de cliquer sur "Dissocier" pour supprimer l'association nouvelle comme existante

**Comment by Gaetanbrl** [comment]
L'API pour associer un tiers par OA ou PA n'est pas fonctionnelle actuellement (erreur 500).
Le bouton Dissocier et l'association n'est donc pas finalisable sans l'API.

**Comment by dcottenc** [comment]
> L'API pour associer un tiers par OA ou PA n'est pas fonctionnelle actuellement (erreur 500).
Le bouton Dissocier et l'association n'est donc pas finalisable sans l'API.

L'API pour associer une OA et un tiers fonctionne (curl -X POST "https://portail-test.sig.rennesmetropole.fr/tabou2/operations/1/tiers" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"tiersId\": 6, \"typeTiersId\": 2}" => http 200
Par contre, elle retorune le mauvais objet.

C'est l'API GET /operations/{operationId}/tiers qui plante avec un http 500 (ticket BO créé)

**Comment by dcottenc** [comment]
La dissociation fonctionne https://portail-test.sig.rennesmetropole.fr/tabou2/operations/1/tiers/6 => HTTP 200

@Gaetanbrl : Comment tu affiches la liste des tiers d'une opération dans ta fenêtre de tiers alors que l'API ne fonctionne pas ?

**Comment by Gaetanbrl** [comment]
> Comment tu affiches la liste des tiers d'une opération dans ta fenêtre de tiers alors que l'API ne fonctionne pas

J'appel la liste de tous les tiers sans distinction OA / PA : 

https://portail-test.sig.rennesmetropole.fr/tabou2/tiers?asc=true

**Comment by Gaetanbrl** [comment]
Ensuite je n'aurai qu'à changer l'URL en intégrant la bonne URL.

Donc `https://portail-test.sig.rennesmetropole.fr/tabou2/tiers?asc=true`
Deviendra `https://portail-test.sig.rennesmetropole.fr/tabou2/operations/{id_operation}/tiers?asc=true`

**Comment by Gaetanbrl** [comment]
En attente d'une maquette par @dcottenc pour revue des écrans.

**Comment by Gaetanbrl** [comment]
@dcottenc voir dernier commentaire

**Comment by dcottenc** [comment]
@Gaetanbrl les API nécessaires au fonctionnement de cette fenêtre sont opérationnelles. 
Le WS POST /programmes/{programmeId}/tiers fonctionne mais son appel n'est pas satisfaisant (pas de body). Ticket Open en cours (traitement semaine prochaine)

L'affichage actuel convient
![image](https://user-images.githubusercontent.com/76009802/145225240-067eb748-7543-4640-938b-668cc1dd4604.png)

**Comment by Gaetanbrl** [comment]
Vu ce jour avec @dcottenc 

- [ ] Autocomplétion sur les nom de Tiers lors de l'association

**Comment by dcottenc** [comment]
Le fonctionnement de la colonne Actif est curieux. 
En premier lieu, l'affichage actif non coché doit correspondre à une association avec un tiers qui n'est plus actif (donc plus sélectionnable).
Ce n'est pas le cas actuellement :
- l'association du tiers "1POINT61 ARCHITECTURE" est possible et s'affiche avec la case actif décochée ;
- de plus l'affichage de la case à cocher d'un autre tiers a été affecté,10i2LA ARCHITECTURE (SCOP) est devenu inactif (sur Baud chardonnet).

**Comment by Gaetanbrl** [comment]
En effet ca ne semble pas normal. Je regarde.

**Comment by Gaetanbrl** [comment]
> l'association du tiers "1POINT61 ARCHITECTURE" est possible et s'affiche avec la case actif décochée

L'ajout de l'auto complétion n'intègre pas le paramètre de requête `inactif=false`.

Il faut compléter cette requête :
`/tabou2/tiers?nom=*10*&asc=true`

... afin d'avoir au final cette requête :
`/tabou2/tiers?nom=*10*&asc=true&inactif=false`

`10i2LA ARCHITECTURE (SCOP)` ne pourra donc plus être associable car ne sera plus retourné par la liste de choix du tiers.

**Comment by Gaetanbrl** [comment]
> de plus l'affichage de la case à cocher d'un autre tiers a été affecté,10i2LA ARCHITECTURE (SCOP) est devenu inactif (sur Baud chardonnet).

Sur le retour de l'API, `1POINT61 ARCHITECTURE` et `10i2LA ARCHITECTURE (SCOP)` ont tous deux une valeur pour le champ `dateInactif`. L'affiche me semble donc correcte.

**Comment by dcottenc** [comment]
@Gaetanbrl , ce ticket a bcp évolué et cela fonctionne plutôt bien.
Mais il reste deux soucis : 

- A quoi sert la case "Rechercher Nom" en haut à droite ?
- Si on coche "désactiver", la requête inactivate est bien envoyée mais l'affichage n'est pas mis à jour.

**Comment by dcottenc** [comment]
Testé, anomalies émises en VA

US close
