### ISSUE TITLE
Edition - Créer un tiers

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#81]
## Description

**En tant que** DAUH,
**Je souhaite** pouvoir saisir un nouveau tiers dans Tabou2,
**Afin de** disposer d'un outil de création d'un tiers.

## (Si) Règles spécifiques - Règles métiers

* Un tiers ne peut être supprimé.
* Un tiers ne peut-être créer que si l'utilisateur dispose des droits nécessaire (à préciser par @dcottenc)
* La création peut-être annulée pendant la saisie sans écriture en base

## (Si) Tests / Cas

1. Afficher les tiers pour une entité en consultation (OA ou PA)
2. Cliquer sur "Créer un tiers"
3. Voir une nouvelle ligne avec des informations vides
4. Voir que par défaut le tiers est actif
5. Voir que le bouton "inactif" n'est pas visible (on ne peut créer un tiers inactif)
6. Voir que le bouton "Modifier" est visible
7. Cliquer sur "Modifier" et saisir les informations
8. Cliquer sur "Enregistrer"
9. Voir le nouveau tiers dans la liste de l'entité sans avoir à rafraîchir manuellement la page
10. Cliquer sur "Créer un tiers"
11. Cliquer sur "Modifier"
12. Saisir des informations
13. Cliquer sur "Annuler"

## Complément (graphique, capture, schéma, etc.)

![tiers_create](https://user-images.githubusercontent.com/16317988/113438008-00337480-93e8-11eb-9196-23e5129831e0.gif)

**Comment by Gaetanbrl** [comment]
- [ ] Bouton "Créer un tiers"
- [ ] Voir le tiers au clique sur "Créer un tiers"
- [ ] Cliquer sur le bouton "Modifier"  pour afficher les attributs à saisir
- [ ] Voir le bouton "Annuler" dès que le nouveau tiers est visible (permet la suppression de ce tiers en cours de création)
- [ ] Voir le bouton "Enregistrer" pour sauvegarder le tiers en base
- [ ] Pouvoir voir le tiers dès qu'il est sauvegardé (sans refresh manuel)

**Comment by Gaetanbrl** [comment]
En attente d'une maquette par @dcottenc pour revue des écrans.

**Comment by dcottenc** [comment]
La maquette de la fiche Tiers v1 est disponible ci-dessous.

- [ ] Seuls les champs nom et ville sont mandatory (/!\ l'API ne contrôle que le nom pour l'instant)

- [ ] Le champ Numero est intégré dans l'adresse. Ce champ devra pouvoir comporter plusieurs lignes :
Bâtiment Concorde
1 Place du Bourget
Cedex

- [ ] Le champ Type (indiqué dans le CCTP n'est pas retenu. Seule l'association d'un tiers permet d'associer un type pour le suivi d'une entité
- [ ] Le champ "Est privé" est à remplacer par "Entreprise du secteur privé" et à True par défaut (MAquette non à jour pour ce champ
 
![image](https://user-images.githubusercontent.com/76009802/130094499-a706144f-666f-45de-9e84-cebfa2b14bbf.png)

**Comment by dcottenc** [comment]
Je confirme les informations de mon post du 19/08.

A l'exception du contact qui n'est plus à afficher. En effet, Nous étudions une évolution qui consiste à gérer une liste de contact pour les tiers.

@Gaetanbrl, concrètement tu peux faire les travaux liés à ce ticket

**Comment by dcottenc** [comment]
Testé et validé (Portail test RM)
