### ISSUE TITLE
API Nature - En diffus et EN_DIFFUS

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#82]
**Description du bug / Describe the bug**
Lors qu'on appel le service nature on a la valeur `En diffus`.

https://portail-test.sig.rennesmetropole.fr/tabou2/natures

```
[
  {
    "id": 1,
    "libelle": "ZAC",
    "dateInactif": null
  },
  {
    "id": 2,
    "libelle": "ZA",
    "dateInactif": null
  },
  {
    "id": 3,
    "libelle": "En diffus",
    "dateInactif": null
  }
]
```

Lorsqu'on utilise ensuite cette valeur pour préciser la nature des emprises, on a une erreur car `En diffus` n'est pas la bonne valeur.
La valeur attendues est `EN_DIFFUS`.

![image](https://user-images.githubusercontent.com/16317988/114061003-382e3200-9896-11eb-8ff2-4e1fb0dab48b.png)

OK ==> `https://portail-test.sig.rennesmetropole.fr/tabou2/operations/emprises?nature=EN_DIFFUS&estSecteur=false`

KO ==> `https://portail-test.sig.rennesmetropole.fr/tabou2/operations/emprises?nature=En diffus&estSecteur=false`

Les valeurs de type de natures doivent provenir de la même table ou avoir les mêmes formats pour éviter au code du plugin de modifier les valeurs.

Est-il possible d'harmoniser ce retour, qui normalement devrait être identiques @dcottenc  ?

**Comment by dcottenc** [comment]
> Les valeurs de type de natures doivent provenir de la même table ou avoir les mêmes formats pour éviter au code du plugin de modifier les valeurs.

Le référentiel des libelles des Nature est bien celui de la table correspondante. Il y a donc bien un soucis avec l'API des emprises
Je vais créer un ticket BO pour corriger cela

**Comment by Gaetanbrl** [comment]
Super @dcottenc merci, ces issues nous serviront d'aide-mémoire :)

**Comment by dcottenc** [comment]
> Les valeurs de type de natures doivent provenir de la même table ou avoir les mêmes formats pour éviter au code du plugin de modifier les valeurs.
> Est-il possible d'harmoniser ce retour, qui normalement devrait être identiques @dcottenc ?

@Gaetanbrl  la demande initiale pour le paramètre Nature est son ID et non le libellé. Je sais que tu préfères le libellé mais pour rester cohérent avec les autres API, je souhaiterais demander la correction avec l'utilisation de l'Id. (Je crois que tu conserves l'id lors du remplissage de la liste de choix)

Peux-tu me confirmer que tu es ok avec cela ?

**Comment by Gaetanbrl** [comment]
> Je crois que tu conserves l'id lors du remplissage de la liste de choix

C'est bien un objet de ce type qui est passé pour les service POST / PUT : 

```
"nature": {
  "id": 1
}
```

L'issue portait ici sur le service GET. Donc si je comprends bien, la requête GET suivante : 

`https://portail-test.sig.rennesmetropole.fr/tabou2/operations/emprises?nature=EN_DIFFUS&estSecteur=false`

Deviendra : 
`https://portail-test.sig.rennesmetropole.fr/tabou2/operations/emprises?nature=1&estSecteur=false`

?

**Comment by dcottenc** [comment]
> Deviendra :
https://portail-test.sig.rennesmetropole.fr/tabou2/operations/emprises?nature=1&estSecteur=false

Oui c'est ca

**Comment by Gaetanbrl** [comment]
Ok ca ne devrait pas être problématique pour moi, dans le cas contraire je rajouterai un commentaire.
