### ISSUE TITLE
API - Voir le nombre d'éléments pour identifier les Réponses incomplètes

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#83]
**Description du bug**

Des retours API ne sont pas complets (limités à 100 retours).
On peut détecter que le retour n'est pas complets via une propriété `totalElements` retournée par l'API dans le corps de la réponse (si totalElements est différent du nombre d'éléments retournés).

_Ex :_ https://portail-test.sig.rennesmetropole.fr/tabou2/plui?asc=true

Mais certains services de l'API ne proposent pas ce `totalElements`.

Il serait utile d'avoir le nombre de retour pour tous les services.

On constate que cette information n'est retournée qu'avec les retours qui propose un corps de réponse avec ce schéma : 

```
{
  "elements": [{...}],
  "totalElements": 1
}
```

Ce Schéma de réponse n'étant pas repris pour tous les services, nous n'avons pas cette information `totalElements`.

**Reproduire le bug**

1. Appeler https://portail-test.sig.rennesmetropole.fr/tabou2/operations/emprises?nature=ZAC&estSecteur=true
2. Voir que le nombre d'éléments n'est pas retourné.

**Comportement attendu**

Si possible, avoir le nombre d'éléments pour chaque retour comme pour cette réponse : 

https://portail-test.sig.rennesmetropole.fr/tabou2/plui?asc=true

**Comment by dcottenc** [comment]
> Si possible, avoir le nombre d'éléments pour chaque retour comme pour cette réponse :

Le fait de ne pas avoir la mème structure de réponse est une anomalie qui doit faire l'objet d'une correction par le BO.
Un ticket est ouvert pour cela.

**Comment by dcottenc** [comment]
Pour information, le perimetre des API concernées est : 

- /consommation-espace

- /decisions
- /maitrise-ouvrage
- /vocations
- /mode-amenagement
- /natures
- /operations/{operationId}/etapes
- /operations/{operationId}/evenements
- /operations/emprises
- /programmes/{programmeId}/agapeo
- /programmes/{programmeId}/etapes
- /programmes/{programmeId}/evenements
- /programmes/{programmeId}/permis
- /programmes/{programmeId}/tiers

**Comment by dcottenc** [comment]
API v1.1.2

Traités :

- /consommation-espace
- /decisions
- /maitrise-ouvrage
- /vocations
- /mode-amenagement
- /natures
- /operations/{operationId}/evenements
- /programmes/{programmeId}/agapeo
- /programmes/{programmeId}/evenements
- /programmes/{programmeId}/permis
- /programmes/{programmeId}/tiers
- /programmes/emprises

Non traités (obligatoire) :

- /operations/emprises

Non traités :

- /operations/{operationId}/etapes
- /programmes/{programmeId}/etapes

**Comment by Gaetanbrl** [comment]
@dcottenc Comment obtenir toutes les réponses dans le cas où le nombre d'éléments retrouvés par l'API ne correspond pas au total retourné ? 

Ex : 
https://portail-test.sig.rennesmetropole.fr/tabou2/plui?asc=true

**Comment by dcottenc** [comment]
>@dcottenc Comment obtenir toutes les réponses dans le cas où le nombre d'éléments retrouvés par l'API ne correspond pas au total retourné ?

@Gaetanbrl  Le recours à la pagination est alors nécessaire. Celle-ci n'est pas implémentée dans les API avec peu de résultat.

Le cas de PLUi est à part. La correction des doublons n'est toujours pas active ce qui entraine un nombre de résultats très importants dont peu de visibles

**Comment by Gaetanbrl** [comment]
> @Gaetanbrl Le recours à la pagination est alors nécessaire. Celle-ci n'est pas implémentée dans les API avec peu de résultat.

Ok Il serait aussi intéressant d'avoir une recherche (like) possible pour limiter les retours de l'API selon la saisie de l'utilisateur.

> Le cas de PLUi est à part. La correction des doublons n'est toujours pas active

A voir si tout tiens dans la liste, sinon la remarque précédente sera à prendre en compte (recherche selon la saisie).

**Comment by dcottenc** [comment]
>Ok Il serait aussi intéressant d'avoir une recherche (like) possible pour limiter les retours de l'API selon la saisie de l'utilisateur.

C'est normalement le cas. [Exemple pour PLUi](https://portail-test.sig.rennesmetropole.fr/tabou2/plui?libelle=*AU*&asc=true)

**Comment by Gaetanbrl** [comment]
OK je vois qu'il faut bien mettre les ** pour que ca fonctionne. Je n'avais jamais vu ca...

**Comment by dcottenc** [comment]
Le dernier web service /operations/emprises qui n'avait pas le nombre d'éléments a été corrigé.

**Comment by Gaetanbrl** [comment]
Pour rappel, le comportement par défaut et que l'API renvoie toutes les données sans distinction. 
Dans l'attente d'un correctif, je ne devais rien modifier car on ne devait plus avoir ce problème ensuite.

Donc qu'en est-il de la limite de 100 résultats ?

**Comment by Gaetanbrl** [comment]
Comportement défini en Cotech :

Si le nombre de résultat est < au nombre d'éléments indiqué par l'API, alors on demande à l'utilisateur d'affiner
C'est un développement à rajouter dans le plugin Tabou2 pour avoir une autocomplétions sur l'API et non sur le composant comme prévu initialement.
