### ISSUE TITLE
Droits et rôles

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#87]
## Description

**En tant que** DAUH 
**Je souhaite** avoir un accès différent d'un utilisateur pour les fonctionnalités du Tabou
**Afin de** pouvoir être certain que seuls certains utilisateurs peuvent modifier, créer ou supprimer des informations.

## (Si) Règles spécifiques - Règles métiers

Quatre rôles permettent de caractériser les droits d’accès au portail et à tout ou partie des fonctionnalités :

| Rôle | Code | Description |
| --- | --- | --- |
| Consultation | EL_APPLIS_TABOU_CONSULT | accès aux fonctions de consultation alphanumériques et cartographiques et de requêtes sur les données |
| Contributeur | EL_APPLIS_TABOU_CONTRIB | rôle consultation + accès aux fonctionnalités de consultation et de mise à jour |
| Référent | EL_APPLIS_TABOU_REFERENT | rôle Contributeur + accès aux données avec diffusion restreinte (le Off) |
| Administrateur | MAPSTORE_ADMIN | rôle administrateur MapStore : il permet la mise à jour du contexte Tabou Mapstore  |

Les règles sont les suivantes par rôle / fonctionnalité du plugin Tabou :

| Fonctionnalités | Consultation | Contributeur | Référent | Administrateur |
| --- | --- | --- | --- | --- |
| Mise à jour du contexte |  |  |  | X |
| Consultation du off |  |  |X |  |
| Recherche critère off |  |  |X |  |
| Ajout/modif off |  |  |X |  |
| Ajout/modif (hors off) |  | X |X |  |
| Ajout/modif tiers |  | X |X |  |
| Ajout/modif événement |  | X |X |  |
| Ajout document GED |  | X |X |  |
| Impression fiche suivi | X | X |X |  |
| Recherche (hors off) | X | X |X |  |
| Consultation | X | X |X |  |

**Comment by Gaetanbrl** [comment]
Merci @dcottenc  pour avoir complété cette issue.

Point à préciser : 

* Identifier précisément le nom du Champ "off" par couche / service à appeler
* En attente de précision sur l'action de création (hors ajout / modification / consultation) comme pour la création d'un tiers

**Comment by Gaetanbrl** [comment]
@dcottenc, si un utilisateur ne peux accéder à une interface, faut-il afficher un message ou bien masquer la fonctionnalité.

Je pense ici au volet "Ajout". Doit-il être visible ? 

Si oui dois-je prévoir un message comme cette proposition : 

![image](https://user-images.githubusercontent.com/16317988/116108854-950e5280-a6b4-11eb-97b2-6be6fbcb93c5.png)

**Comment by dcottenc** [comment]
>@dcottenc, si un utilisateur ne peux accéder à une interface, faut-il afficher un message ou bien masquer la fonctionnalité.
Pour les actions comme ajouter / associer etc, le bouton sera masqué.

Il faut que j'interroge la MOA à ce sujet lors de notre point de demain.
