### ISSUE TITLE
API - Retirer association d'un tier

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#94]
**Description**

Lors de l'association d'un tiers, le front doit envoyer un objet de ce type (en POST) à l'API : 

```
{
  "tiersId": 0,
  "typeTiersId": 0
}
```

Je pense que ce serait plus simple si on envoyé que l'ID du tiers. Car lorsqu'on réalise une association, on appel le service GET /tiers au préalable pour avoir la liste des tiers (actif et non déjà associé).

Donc l'API est en capacité de récupérer elle-même le type du tier à envoyer.
Surtout si le type de tiers (id et autres infos) vont être contenu dans le tiers avec l'API v1.2.

On aurait donc 

* Soit une URL sans objet de ce type (en PUT ?): 

`/operations/{operationId}/tiers/{tierId}`

C'est ce qui est fait avec l'inactivation d'un tiers en PUT via `/tiers/{tiersId}/inactivate`

* Soit toujours un objet à envoyer (en POST) sans avoir à préciser le type (car inutile):
```
{
  "tiersId": 0
}
```

**Comment by dcottenc** [comment]
@Gaetanbrl Ce ticket m'a échappé et il doit être ancien

Les WS suivants n'utilisent pas de body pour supprimer l'association d'un tiers à une OA ou un PA : 

- DELETE /programmes/{programmeId}/tiers/{associationTiersId}
- DELETE /operations/{operationId}/tiers/{associationTiersId}

**Comment by dcottenc** [comment]
Testé et validé (Portail RM)
