### ISSUE TITLE
API - Service GET Emprise Programme 

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#96]
/!\ Déjà identifié par @dcottenc - Prévu dans API v1.2

### Description

Le service permettant de récupérer les emprises n'existe pas. 

Sans la liste des emprises d'un programme, on ne peut ajouter un programme (via l'onglet "ajouter").

**Comment by dcottenc** [comment]
Anomalie CDCRM-756 [Tabou] APIs manquantes en cours de correction

**Comment by dcottenc** [comment]
Cette anomalie est corrigée

**Comment by Gaetanbrl** [comment]
A tester

**Comment by Gaetanbrl** [comment]
Comportement défini en Cotech :

Si le nombre de résultat est < au nombre d'éléments indiqué par l'API, alors on demande à l'utilisateur d'affiner

C'est un développement à rajouter dans le plugin Tabou2 pour avoir une autocomplétions sur l'API et non sur le composant comme prévu initialement.
