### ISSUE TITLE
API - id Tabou non conservé

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#97]
/!\ Déjà identifié par @dcottenc - Prévu dans API v1.2

### Description

L'ID Tabou n'existe pas lorsqu'on crée une opération (probablement identique pour SA et PA).

Sans cet ID Tabou, la mécanique rend impossible l'affichage de la fiche attributaire.

**Comment by dcottenc** [comment]
Sauf erreur de ma part, l'objet en retour contient l'attribut id qui correspond à l'id_tabou.

**Comment by Gaetanbrl** [comment]
> Sauf erreur de ma part, l'objet en retour contient l'attribut id qui correspond à l'id_tabou.

Ok, on avait convenu que ce champ s'appelerai "id_tabou", nom du champ visible dans la layer...

**Comment by Gaetanbrl** [comment]
C'est noté en tout cas ;)
