### ISSUE TITLE
CARTO - Couche non mise à jour

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#98]
Vu avec @dcottenc ce jour.

Issue en cours de correction (via actions en cours sur API v1.2).

**Description du bug / Describe the bug**

Lors de la création d'une entité via l'API, les données cartographique ne sont pas mises à jour.

**Reproduire le bug / To Reproduce**

1. Créer une opération via l'API (service /GET)
2. Aller sur le contexte https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/Tabou2_Recette
3. Interroger la feature ajoutée via l'outil natif (et non le plugin)
4. Voir que les informations sont manquantes

**Comportement attendu / Exptected behavior**

La couche devrait afficher les informations saisies.

**Comment by dcottenc** [comment]
L'anomalie a été corrigée pour l'ensemble des cas possibles

**Comment by Gaetanbrl** [comment]
A tester, refresh de la couche à forcer.

**Comment by Gaetanbrl** [comment]
Code disponible sur branche develop, pas encore visible dans le contexte (plugin à redéployer)

**Comment by dcottenc** [comment]
@Gaetanbrl cette anomalie API est corrigée (mise à jour de l'ID_Tabou dans les tables des emprises). Le sujet du rafraichissement ne doit-il pas faire l'objet d'un autre ticket ?

**Comment by Gaetanbrl** [comment]
Pour moi les données cartographiques englobe la visualisation + les données en base.
Mais on peut séparer @dcottenc

**Comment by dcottenc** [comment]
@Gaetanbrl cette anomalie est spécifique à l'API.
Je suis d'accord avec toi que l'enregistrement concerne la visu et la bdd mais c'est l'objet d'une US et actuellement je ne peux pas tester l'enregistrement des PA (erreur systématique).

**Comment by Gaetanbrl** [comment]
ok tickets à séparer

**Comment by dcottenc** [comment]
Correction testée et validée
