### ISSUE TITLE
API - Impression fiche suivi

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/geor_tabou2_front#99]
Identifié par @dcottenc
Correctif en cours de réalisation via travaux sur API v1.2.

**Description du bug / Describe the bug**

La fiche de suivi d'in programme retourne une erreur 500.

**Comment by Gaetanbrl** [comment]
Code implémenté, en attente de finalisation et test après correction #99

**Comment by dcottenc** [comment]
L'anomalie a été corrigée mais une demande d'évolution (tiers) a créé un dysfonctionnement.
En l'état (API v1.1.4), les appels pour la fiche de suivi fonctionnent si le programme ne comporte pas de tiers (ex : ID 3 et 9).

**Comment by Gaetanbrl** [comment]
> En l'état (API v1.1.4), les appels pour la fiche de suivi fonctionnent

A tester / a finaliser / à adapter par @Gaetanbrl pour les PA id 3 et 9.

**Issue encore active**

Pour d'autres ID, un correctif est en cours, à livrer dans une version API > 1.1.4.

**Comment by Gaetanbrl** [comment]
Testé ce jour et retourne une erreur 500.
https://portail-test.sig.rennesmetropole.fr/tabou2/programmes/856/fiche-suivi

**Comment by dcottenc** [comment]
> Testé ce jour et retourne une erreur 500.

De nouveau opérationnel. L'erreur était liée à la reprise de données

**Comment by Gaetanbrl** [comment]
merci @dcottenc je vais regarder ca semaine prochaine.
